### PR TITLE
Fix for Notifications for commenting on Blog post not working on Plat…

### LINKED ISSUE #2326: Notifications for commenting on Blog post not working on Platform v1.5.8
**Describe the bug**
In Platform v1.5.7.3, the Notifications work when someone comments on the Blogs post. The user/author who posted the Blog will received a notification bell that someone commented on his blog. With Platform 1.5.8, this is not working anymore.

**To Reproduce**
1. Install Platform 1.5.7.3 and Theme 1.6.4.1
2. In BuddyBoss > Settings > Activity > Posts in Activity Feeds, enable Blog Posts
3. Create a Blog, with Comments enabled
4. Login to another user and it front end, comment on the created Blog
5. Log back in to the previous user who posted the blog
6. See notification bell
7. Update platform and theme, and do the steps 2 - 6

**Expected behavior**
Notifications should work if intended

**Screenshots**
http://somup.com/crflQ2bSnW

**Support ticket links**
https://secure.helpscout.net/conversation/1478097118/135310

### PR DESCRIPTION
**Pull request by ngolwalkar**
### Changes proposed in this Pull Request:

Fixes #2326

### How to test the changes in this Pull Request:

1. In BuddyBoss > Settings > Activity > Posts in Activity Feeds, enable Blog Posts
2. Create a Blog, with Comments enabled
3. log in to another user and its front end, comment on the created Blog
4. Log back into the previous user who posted the blog
5. See notification bell

### Proof Screenshots or Video

https://www.loom.com/share/edb0726f0d014f079e9b2c07a7c0816a

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]

**Comment by mohit-buddyboss** [comment]
@ngolwalkar 

FIXED>Tested on the dev branch of the platform.
1.Tested by creating new blog post . 
2.Commented it on via  user XYZ. 
3. Checked notification as a author.
4. replied back
5. Check notification for user XYZ.

Notifications for blog post comment is working now.
Video: https://www.loom.com/share/489891c4c7494c95901b9be4a43aacca

Related issue is resolve now and PR is ready to merge.

cc @sourabhmatolia @chetansatasiya

File: src/bp-blogs/bp-blogs-functions.php [hunk 1]
```diff
@@ -832,6 +832,10 @@ function bp_blogs_comment_sync_activity_comment( &$activity_id, $comment = null,
 			 * reply from blog or custom post types.
 			 */
 			remove_action( 'bp_activity_before_save', 'bp_blogs_sync_activity_edit_to_post_comment', 20 );
+
+			// Added the filter to bypass the content check on blog or custom post types comments.
+			add_filter('bp_has_activity_comment_content', '__return_false()');
```
Comment (KartikSuthar) [inline src/bp-blogs/bp-blogs-functions.php:837]: @ngolwalkar Can you please do this change?

```suggestion
			add_filter( 'bp_has_activity_comment_content', '__return_false' );
			
```

Ref: https://developer.wordpress.org/reference/functions/__return_false/

Comment (ngolwalkar) [reply src/bp-blogs/bp-blogs-functions.php]: @KartikSuthar I updated the file with the required changes.
