### PR TITLE
Fixed - Group name is not syncing between BuddyBoss and LearnDash

### LINKED ISSUE #1327: Group name is not syncing between BuddyBoss and LearnDash.
**Describe the bug**
Group name is not syncing between BuddyBoss Social Groups and LearnDash. If you change the group's name from the frontend, it is not syncing in LearDash Group at the backend.

**To Reproduce**
1. Make sure that you activated  **Enable group sync functionality FROM BuddyBoss Social Groups TO LearnDash Groups** and **Enable group sync functionality FROM LearnDash Groups TO BuddyBoss Social Groups**.
(BuddyBoss > Integration > LearnDash)
2. Create a Group in LearnDash LMS > Groups. Example name: "Group Sync"
3. Go to the frontend, go to Groups page. Then, select the Group Sync, go to Manage, and try to edit the name.

https://prnt.sc/tx36bb
http://prnt.sc/tx36e6

4. Go back at the backend, go to LearnDash > Groups. You will see that it still has the old name which in my testing "Group Sync" instead of the new name "Sync this Groups chochocho".

https://prnt.sc/tx36jr

**Expected behavior**
Group name should sync

**Support ticket links**
https://secure.helpscout.net/conversation/1247016391/86971

### PR DESCRIPTION
**Pull request by jitendrabanjara1991**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1327 .

### How to test the changes in this Pull Request:

1. Make sure that you activated Enable group sync functionality FROM **BuddyBoss Social Groups TO LearnDash Groups** and Enable group sync functionality FROM **LearnDash Groups TO BuddyBoss Social Groups**.
(BuddyBoss > Integration > LearnDash)
2. Create a Group in LearnDash LMS > Groups. Example name: "Group Sync"
3. Go to the frontend, go to Groups page. Then, select the Group Sync, go to Manage, and try to edit the name.
4. Go back at the backend, go to LearnDash > Groups. You will see that it still has the old name which in my testing "Group Sync" instead of the new name "Sync this Groups chochocho".

### Proof Screenshots or Video

https://screencast-o-matic.com/watch/crVTqk9soP

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

File: src/bp-integrations/learndash/library/SyncGenerator.php [hunk 1]
```diff
@@ -753,4 +753,57 @@ protected function getLastSyncTimestamp( $type = 'bp' ) {
...
+		groups_create_group(
+			array(
+				'group_id'    => $groupId,
+				'creator_id'  => $ldGroup->post_author,
+				'name'        => $ldGroup->post_title ?: "For Social Group: {$this->ldGroupId}",
+				'status'      => $settings->get( 'learndash.default_bp_privacy' ),
+				'description' => $ldGroup->post_content,
+				'slug'        => $ldGroup->post_name,
+			)
+		);
```
Comment (chetansatasiya) [inline src/bp-integrations/learndash/library/SyncGenerator.php:803]: @jitendrabanjara1991
```suggestion
if ( ! empty ( $groupId ) ) {
		groups_create_group(
			array(
				'group_id'    => $groupId,
				'creator_id'  => $ldGroup->post_author,
				'name'        => $ldGroup->post_title ?: "For Social Group: {$this->ldGroupId}",
				'status'      => $settings->get( 'learndash.default_bp_privacy' ),
				'description' => $ldGroup->post_content,
				'slug'        => $ldGroup->post_name,
			)
		);
		}
```

File: src/bp-integrations/learndash/library/SyncGenerator.php [hunk 2]
```diff
@@ -753,4 +753,57 @@ protected function getLastSyncTimestamp( $type = 'bp' ) {
...
+			array(
+				'ID'           => $ld_group_id,
+				'post_title'   => $bpGroup->name,
+				'post_author'  => $bpGroup->creator_id,
+				'post_content' => $bpGroup->description,
+				'post_status'  => 'publish',
+				'post_type'    => learndash_get_post_type_slug( 'group' ),
+			)
+		);
+	}
```
Comment (chetansatasiya) [inline src/bp-integrations/learndash/library/SyncGenerator.php:779]: Check before the update.

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@jitendrabanjara1991 Check id not empty before update

**Comment by jitendrabanjara1991** [comment]
Hello @chetansatasiya 
I have added conditions before the update. Please check it and let me know if anything else. Thanks

File: src/bp-integrations/learndash/library/SyncGenerator.php [hunk 3]
```diff
@@ -753,4 +753,61 @@ protected function getLastSyncTimestamp( $type = 'bp' ) {
...
 	}
+
+	/**
+	 * Update a ld group based on current bp group
+	 *
+	 * @param string $ld_group_id Group id for learndash
+	 *
+	 * @param int    $groupId Group id for buddyboss
+	 *
+	 * @since BuddyBoss 1.5.8
```
Comment (chetansatasiya) [inline src/bp-integrations/learndash/library/SyncGenerator.php:764]: @jitendrabanjara1991 Next release is `1.5.7`
```suggestion
	 * @since BuddyBoss 1.5.7
```

File: src/bp-integrations/learndash/library/SyncGenerator.php [hunk 4]
```diff
@@ -753,4 +753,61 @@ protected function getLastSyncTimestamp( $type = 'bp' ) {
...
+	}
+
+	/**
+	 * Update a bp group based on current ld group
+	 *
+	 * @param string $ld_group_id Group id for learndash
+	 *
+	 * @param int    $groupId Group id for buddyboss
+	 *
+	 * @since BuddyBoss 1.5.8
```
Comment (chetansatasiya) [inline src/bp-integrations/learndash/library/SyncGenerator.php:790]: Same here

**Review by chetansatasiya — COMMENTED** [review]
@jitendrabanjara1991 Need to check the since tags

**Comment by jitendrabanjara1991** [comment]
@chetansatasiya 
Changed since tag 1.5.8 to 1.5.7. Please check it and let me know if anything else. Thanks

**Review by chetansatasiya — APPROVED** [review]
@jitendrabanjara1991 LGTM 🚀 

Merge in dev and add in testing

**Comment by jitendrabanjara1991** [comment]
@chetansatasiya 
Merged in dev and assing label for testing. Thanks

**Comment by sumitbuddyboss** [comment]
Hello @jitendrabanjara1991 

Fixed > Related issue has been resolved and now  Group name is sync between BuddyBoss and LearnDash. For the proof please check the below video.

Video:
https://www.loom.com/share/22c9383d65fe4191b45abaaad178e210

@chetansatasiya @mehulkaklotar 
The related issue is resolved now and PR is ready to merge.

Thank you
