### PR TITLE
PROD-720 Fixed #3059 Reset the video player on theatre model close

### LINKED ISSUE #3059: JS console error on closing the video media model container
**Describe the bug**
Getting js console error on the browser when we closing the video modal. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the video page
2. Click on the video ( it will open the full-width modal)
3. After playing it, close the modal
4. See error on browser console

**Expected behaviour**

**Screenshots**
https://drive.google.com/file/d/1-g1fw8wSVS7uQTB2aj4uLtsWv4de4fMD/view?usp=sharing

**Environment**
Customer site
dev site

**Support ticket links**
https://secure.helpscout.net/conversation/1653608984/167722?folderId=3709082

**Jira issue** : [PROD-720]

[PROD-720]: https://buddyboss.atlassian.net/browse/PROD-720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by bb-yudhisthir**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Instead to assigning the video src="" (which was causing the issue),  used reset() to reset the video player

Fixes #3059.

### How to test the changes in this Pull Request:

1. On videos page goto videos and click to open it in fullscreen popup and close and see the error in console
2. Try the same on the timeline/activity feed, open the video in popup and close and open the picture

### Proof Screenshots or Video

https://somup.com/crl2620HKJ

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Used reset() to reset the video player

### CODE REVIEW

**Review by dipskakadiya — APPROVED** [review]

File: src/bp-templates/bp-nouveau/js/buddypress-media.js [hunk 1]
```diff
@@ -6204,7 +6204,6 @@ window.bp = window.bp || {};
 			var currentVideo =  document.getElementById( $( '.bb-media-model-wrapper.video video' ).attr('id') );
 			if( currentVideo ) {
 				currentVideo.pause();
-				currentVideo.src = '';
```
Comment (amincdev) [inline src/bp-templates/bp-nouveau/js/buddypress-media.js:6207]: Same functionalitu we have when user open document theater. Because there is a case when user has a document in comment area and opens it then also needs to stop playing video.

Comment (amincdev) [reply src/bp-templates/bp-nouveau/js/buddypress-media.js:6207]: This change does not require because closeTheater function changes fix the issue already.

**Review by amincdev — DISMISSED** [review]

File: src/bp-templates/bp-nouveau/js/buddypress-media.js [hunk 2]
```diff
@@ -6414,7 +6413,7 @@ window.bp = window.bp || {};
 			
 			$('.bb-media-model-wrapper.media .bb-media-section').find('img').attr('src', '');
 			if( $('.bb-media-model-wrapper.video .bb-media-section').find('video').length ){
-				$('.bb-media-model-wrapper.video .bb-media-section').find('video').attr('src', '');
+				videojs( $('.bb-media-model-wrapper.video .bb-media-section').find('video').attr('id') ).reset();
```
Comment (jitendrabanjara1991) [inline src/bp-templates/bp-nouveau/js/buddypress-media.js:6416]: @bb-yudhisthir Need to define videojs as global at top of the file.
Please check line number 2 in this file - src/bp-templates/bp-nouveau/js/buddypress-video.js

**Review by jitendrabanjara1991 — CHANGES_REQUESTED** [review]
Need changes

**Review by jitendrabanjara1991 — APPROVED** [review]
LGTM
