### PR TITLE
Fix for #2423 Selecting "Discussions by Last Post" returning /topics/ page 404 error.

### LINKED ISSUE #2423: Selecting "Discussions by Last Post" returning /topics/ page 404 error
**Describe the bug**
When "Discussions by Last Post" is selected on "Forums Directory show" the /topics/ page returning 404 error 

**To Reproduce**
1. Go to **BuddyBoss > Settings > Forums > Scroll down to Forums Directory shows > Select "Discussions by Last Post"**
2. Go to https://site-url/forums/
3. Scroll down to pagination then click 2
4. Scroll down again to pagination then go back to page 1

**Screenshots**
https://www.loom.com/share/de7f61dbae7943b683b1fd74f2d2c068

**Support ticket links**
https://secure.helpscout.net/conversation/1516970176/142831

### PR DESCRIPTION
**Pull request by ngolwalkar**
### Changes proposed in this Pull Request:

Fixes #2423 

### How to test the changes in this Pull Request:

1. Go to BuddyBoss > Settings > Forums > Scroll down to Forums Directory shows > Select "Discussions by Last Post"
2. Go to https://site-url/forums/
3. Scroll down to pagination then click 2
4. Scroll down again to pagination then go back to page 1
5. It will work fine now.

### Proof Screenshots or Video

https://www.loom.com/share/486a30a797504149a830542f6dc3fd0b

### CODE REVIEW

File: src/bp-forums/classes/class-bbpress.php [hunk 1]
```diff
@@ -483,7 +483,7 @@ public static function register_post_types() {
 						'capabilities'        => bbp_get_topic_caps(),
 						'capability_type'     => array( 'topic', 'topics' ),
 						'menu_position'       => 555555,
-						'has_archive'         => ( 'forums' === bbp_show_on_root() ) ? bbp_get_topic_archive_slug() : false,
+						'has_archive'         => true,
```
Comment (chetansatasiya) [inline src/bp-forums/classes/class-bbpress.php:486]:
```suggestion
						'has_archive'         => ( 'forums' === bbp_show_on_root() ) ? true : false,,
```

Can't we do this? Need to check why bbpress have this condition is there any option like not to be archive page

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
Need changes

File: src/bp-forums/classes/class-bbpress.php (hunk 1 above)
Comment (ngolwalkar) [reply src/bp-forums/classes/class-bbpress.php:486]: @chetansatasiya Okay looking into it.

Comment (ngolwalkar) [reply src/bp-forums/classes/class-bbpress.php:486]: @chetansatasiya I checked with bbpress, the option to choose what should be on the forum root.
- Forum or
- Topics
image
If we select the first option "Forum Index", so It means if the Forum root is showing forums, so there should be a separate archive for topics, whereas if we select the second option "Topics by Last Post", so it will show topics on forums page so there is no need for a separate topics archive. That's what the below line of code says 
`'has_archive'         => ( 'forums' === bbp_show_on_root() ) ? bbp_get_topic_archive_slug() : false,`
and in bbpress the pagination shows the the pagination link something like this.

**Review by KartikSuthar — APPROVED** [review]

**Comment by mohit-buddyboss** [comment]
@ngolwalkar 

Tested on dev branch of the platform.
Video:  https://loom.com/share/0c239e8021e944f6a25f696e6f935b74

Related issue is resolve now and PR is ready for release.

cc @sourabhmatolia @KartikSuthar
