### PR TITLE
Fixed the issue  Sharing Document link in Private message

### LINKED ISSUE #2369: Sharing Document link in Private message breaks the Layout
**Check Video for More details:**
https://www.loom.com/share/969af54810a3452399b2bea57d920216

**Again Note from the Video:**
- Allow sharing documents, photos, or any link in Private messages instead of embedding.
- Should be allowed to share the link in Activity post, Forums Discussions, Replies, Post Comments, etc.
- We will allow sharing of Documents and Photos but it will be accessible based on the privacy configured.

### PR DESCRIPTION
**Pull request by krunal-buddyboss**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2369 

Check Video for More details:
https://www.loom.com/share/969af54810a3452399b2bea57d920216

**Themes Related PR:** https://github.com/buddyboss/buddyboss-theme/pull/1468

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

File: src/bp-core/classes/class-bp-embed.php [hunk 1]
```diff
@@ -312,7 +312,7 @@ public function autoembed( $content, $type = '' ) {
 		// Replace line breaks from all HTML elements with placeholders.
 		$content = wp_replace_in_html_tags( $content, array( "\n" => '<!-- wp-line-break -->' ) );
 
-		if ( ! $link_embed && preg_match( '#(^|\s|>)https?://#i', $content ) ) {
+		if ( ! $link_embed && preg_match( '#(^|\s|>)https?://#i', $content ) && ! ( strpos($content, 'download_document_file') || strpos($content, 'download_media_file') ) ) {
```
Comment (KartikSuthar) [inline src/bp-core/classes/class-bp-embed.php:315]: @krunal-buddyboss 
```suggestion
		if ( ! $link_embed && preg_match( '#(^|\s|>)https?://#i', $content ) && ! ( strpos( $content, 'download_document_file' ) || strpos( $content, 'download_media_file' ) ) ) {
```

**Review by KartikSuthar — CHANGES_REQUESTED** [review]
@krunal-buddyboss Please do the phpcbf fixes.

**Review by KartikSuthar — DISMISSED** [review]
@krunal-buddyboss Approved. Merged to dev and pass to QA.

**Comment by mohit-buddyboss** [comment]
@krunal-buddyboss 

Tested this on dev branch of the platform. I tested this for Messages, Activity feed, Forums reply and Post comments also tested this using external and internal links. 

Now in Private messages instead of embed Links are appearing and user can download documents if user have access as per privacy settings. Also, external links are appearing in messages and access is working fine for external links. Documents privacy settings are working fine and user access is working as per document access settings. 
**Videos:**
Issue>https://www.loom.com/share/28bb1b4a896d48b3b24c8e57a3954c91
Private message links sharing and access settings> https://www.loom.com/share/c18347b2c8b541c18bcf2d1c369f1cd5

**ISSUE>**
In activity feed and forum replies when user share links then it creates embed only instead of only embed both link and embed preview must appear so that user can access internal documents download links. 
Video: https://www.loom.com/share/35ad9247f9664d9b9192806c8c668526

cc @chetansatasiya

**Comment by krunal-buddyboss** [comment]
@mohit-buddyboss 
I have applied the changes to do not embed internal link in  Activity feed, Forums reply and Post comments etc also tested as well. Please test it from your side as well. Thanks.

File: src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js [hunk 2]
```diff
@@ -1568,6 +1568,10 @@ window.bp = window.bp || {};
 						return false;
 					}
 
+					if ( url.includes( window.location.hostname ) ) {
```
Comment (KartikSuthar) [inline src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js:1571]: @krunal-buddyboss Please update the logic here, If the user wants to share a site blog here then, It will not embed.

**Review by KartikSuthar — CHANGES_REQUESTED** [review]

File: src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js (hunk 2 above)
Comment (krunal-buddyboss) [reply src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js]: @KartikSuthar 
I have applied changes as we have discussed on slack.
FYI @sourabhmatolia @chetansatasiya @mohit-buddyboss

**Comment by mohit-buddyboss** [comment]
@krunal-buddyboss 

Tested on dev branch of the platform and theme.
Issue > On forums discussion and in replies downloaded link for documents are converting into embed and for external links embeds are not appearing.
Video: https://www.loom.com/share/9d988962018e4a35bdfc720c2d014fa6

cc @chetansatasiya @sourabhmatolia

**Review by chetansatasiya — APPROVED** [review]

**Comment by mohit-buddyboss** [comment]
@krunal-buddyboss 

Tested on dev branch of the platform.

1) In post comments embed link will not appear for external ,internal , doc  link and photos download link it is working same as demo. 
Demo : > https://prnt.sc/13h7znd
Dev branch> https://prnt.sc/13h8k21

2) In forums replies and discussion also embed link will not appear for external and internal links. 
https://www.loom.com/share/99854bdb3eec4a90b50f323ad2b307cb

3) On news feed page embed will appear for internal pages and external pages except document download link, photo download and album download link . 
Video : https://www.loom.com/share/d862954d18794c03bafdc89fcc5ed43e

Issue 1:
Photo can be access through downloaded link by any user if it is restricted for other users.
Video: https://www.loom.com/share/fcf9d1a6300347cda190c6f24abf6775

Issue 2: 
On pasting doc or media download in forum replies. Embed also appears with the link and it will get disappear once user refresh the page.
Video: https://www.loom.com/share/2bc4039f2f724c1aaa7ebedd0ac542f3

cc @sourabhmatolia @chetansatasiya

**Comment by mohit-buddyboss** [comment]
@krunal-buddyboss 

FIXED>Tested on dev branch on the platform.
Issue 1: Not reproducible and Media files access as per privacy settings.
Issue 2 : FIXED by Theme PR :  buddyboss/buddyboss-theme#1468

Video: https://www.loom.com/share/3e6e4442cfa24ccaad0ae705ebee8ae8

Related issue is resolve now and PR is ready for release.

cc @chetansatasiya @sourabhmatolia
