### PR TITLE
PROD-923 - Backslash (\) in the forum post is not showing in Activity Feed

### LINKED ISSUE #1337: Backslash (\) in the forum post is not showing in Activity Feed
**Describe the bug**
When a backslash (\) is included in the post from to the forum, it does not show in the activity feed.

**To Reproduce**
1. Go to the Forum
2. Reply on an existing discussion or create a new discussion with backslash example: wp-content\themes\buddyboss-theme
3. Navigate to the Activity
4. And see the backslash is not showing

**Expected behavior**
Backslash should show in the feed.

**Screenshots**
https://prnt.sc/txn614
https://prnt.sc/txn6iz

**Support ticket links**
https://secure.helpscout.net/conversation/1242425934/86138

**Jira issue** : [PROD-923]

[PROD-923]: https://buddyboss.atlassian.net/browse/PROD-923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by janakkaneriya007**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1337 .

### How to test the changes in this Pull Request:

1. Go to the Forum
2. Reply on an existing discussion or create a new discussion with backslash example: wp-content\themes\buddyboss-theme
3. Navigate to the Activity
4. And see the backslash is not showing

### Proof Screenshots or Video
https://www.loom.com/share/2466b711c1ed4630bf99b610c38d0e2c

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

File: src/bp-activity/bp-activity-filters.php [hunk 1]
```diff
@@ -80,7 +80,6 @@
 add_filter( 'bp_acomment_name', 'stripslashes_deep', 5 );
 add_filter( 'bp_get_activity_action', 'stripslashes_deep', 5 );
 add_filter( 'bp_get_activity_content', 'stripslashes_deep', 5 );
-add_filter( 'bp_get_activity_content_body', 'stripslashes_deep', 5 );
```
Comment (chetansatasiya) [inline src/bp-activity/bp-activity-filters.php:83]: @janakkaneriya007 I don't think we need to remove this filter as I post the content into the activity `wp-content\themes\` then it showing the correct see here https://prnt.sc/wcvsb9 maybe something wrong with the discussion content.

**Review by chetansatasiya — COMMENTED** [review]
@janakkaneriya007 I don't think we need to remove this filter as I post the content into the activity wp-content\themes\ then it showing the correct see here https://prnt.sc/wcvsb9 maybe something wrong with the discussion content.

**Review by chetansatasiya — APPROVED** [review]

File: src/bp-activity/bp-activity-filters.php [hunk 2]
```diff
@@ -85,9 +85,12 @@
 add_filter( 'bp_get_activity_latest_update', 'stripslashes_deep', 5 );
 add_filter( 'bp_get_activity_latest_update_excerpt', 'stripslashes_deep', 5 );
 add_filter( 'bp_get_activity_feed_item_description', 'stripslashes_deep', 5 );
-add_filter( 'bbp_activity_reply_create_excerpt', 'addslashes', 5 );
 add_filter( 'bp_activity_primary_link_before_save', 'esc_url_raw' );
 
+// Allow slash in topic reply.
+add_filter( 'bbp_activity_topic_create_excerpt', 'addslashes', 5 );
+add_filter( 'bbp_activity_reply_create_excerpt', 'addslashes', 5 );
```
Comment (KartikSuthar) [inline src/bp-activity/bp-activity-filters.php:92]: Please move this filter on the file: src/bp-forums/activity.php

**Review by KartikSuthar — CHANGES_REQUESTED** [review]

**Review by KartikSuthar — APPROVED** [review]
