### PR TITLE
Fix/1082 - Repeater field issue generate sometime when add fieldset with name Repeater Fieldset

### LINKED ISSUE #1082: Repeater fields - if you add too many at once it will duplicate the fields in the admin
**Describe the bug**
"It is an issue where a regular user adds a basic repeater field (one text field) from the front end enough times (like 10 times) and it actually duplicates those fields inside the admin panel. I was able to replicate it on your demo."

**To Reproduce**
1. Create a repeater field
2. In your profile, add a basic repeater field (one text field) from the front end enough times (like 10 times) 
3. Save your profile
4. View the field group in the admin

**Expected behavior**
It should not create any extra fields in the admin

**Support ticket links**
Posted in Youtube by user "Anna DiTommaso"
https://www.youtube.com/watch?v=ofIf0VTQxok&lc=Ugz6p7u-ShTD1GaSfl94AaABAg&feature=em-comments

### PR DESCRIPTION
**Pull request by jitendrabanjara1991**
### All Submissions:

https://github.com/buddyboss/buddyboss-platform/pull/2031

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1082.

### How to test the changes in this Pull Request:

1.  Add fieldset with this name - Repeater Fieldset
2.  Add new field in above fieldset with this name - Text Field
3.  Save it and add repeater field at front side in profile section.
4.  Sometimes it generated duplicate fields.

### Proof Screenshots or Video

Only one time replicate in local after that didn't replicate same issue again. When I replicate this issue then checked in DB its cloned from multiple added ids. So, I have changed in code and after that I didn't replicate same issue.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### API PR: 
https://github.com/buddyboss/buddyboss-platform-api/pull/291

### CODE REVIEW

**Comment by jitendrabanjara1991** [comment]
Hello @chetansatasiya 
cc - @sourabhmatolia 
I have changed some code for the repeater field issue. So, Please review it. 
Thanks.

**Comment by jitendrabanjara1991** [comment]
@chetansatasiya 
cc - @sourabhmatolia 
Ready for review code.
Please check it and let me know if need any changes.
Note - I have added code for the background process. So, I don't think we need to add option in Repair Community option in the Tools. Right now I have added it. So, Please confirm with me so I can check based on suggestion.
Thanks.

File: src/bp-templates/bp-nouveau/js/buddypress-xprofile.js [hunk 1]
```diff
@@ -142,9 +143,17 @@ window.bp = window.bp || {};
     if ( repeater_set_count === 1 ) {
         //$( '#profile-edit-form .repeater_group_outer .repeater_set_delete' ).addClass( 'disabled' );
     }
+    // Remove attr from button after page successfully load.
+    if ( window.location.href.indexOf('#bpxpro') > 0 ) {
+        document.addEventListener('DOMContentLoaded', function () {
+            console.log('loaded');
```
Comment (chetansatasiya) [inline src/bp-templates/bp-nouveau/js/buddypress-xprofile.js:149]: Remove debug code

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@sadrul now we are not using the`bp_` prefix in newly introduce function instead of we are using the `bb_` so need to change in this pr in all the new functions

**Comment by sadrul** [comment]
@chetansatasiya I updated accordingly

File: src/bp-xprofile/bp-xprofile-filters.php [hunk 2]
```diff
@@ -1061,3 +1062,201 @@ function bp_xprofile_exclude_display_name_profile_fields( $args ){
...
+ *
+ * @param int     $offset
+ * @param boolean $callback
+ *
+ * @return array
+ */
+function bb_xprofile_repeater_field_migration( $offset, $callback ) {
+	global $wpdb;
+	$bp               = buddypress();
+	$recipients_query = "SELECT DISTINCT id FROM {$bp->profile->table_name_groups} WHERE can_delete= 1 LIMIT 2 OFFSET $offset ";
```
Comment (chetansatasiya) [inline src/bp-xprofile/bp-xprofile-filters.php:1115]: Use the $wpdb->prepare for query

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
add the since tag on all the newly added function and run the phpcs in all the newly added a code and fix all of them.

**Review by chetansatasiya — DISMISSED** [review]
@sadrul LGTM merge to dev and put in testing

**Comment by sadrul** [comment]
@sumitbuddyboss this one ready for testing

**Comment by sadrul** [comment]
Fixed this issue here as well https://github.com/buddyboss/buddyboss-platform/issues/1823
Proof: https://www.loom.com/share/7273e1029739453899d59687eaae17a9

File: src/bp-xprofile/bp-xprofile-filters.php [hunk 3]
```diff
@@ -111,10 +111,11 @@
 add_action( 'update_option_bp-disable-avatar-uploads', 'bp_core_xprofile_clear_all_user_progress_cache' ); // When avatar photo setting updated in wp-admin > Settings > profile.
 add_action( 'update_option_bp-disable-cover-image-uploads', 'bp_core_xprofile_clear_all_user_progress_cache' ); // When cover photo setting updated in wp-admin > Settings > profile.
 
-
-
 //Display Name setting support
 add_filter( 'bp_after_has_profile_parse_args', 'bp_xprofile_exclude_display_name_profile_fields' );
+// Repair repeater field repeated in admin side.
+add_filter( 'bp_repair_list', 'bb_xprofile_repeater_field_repair' );
+add_action( 'admin_init', 'bb_xprofile_repeater_field_repair_with_background' );
```
Comment (KartikSuthar) [inline src/bp-xprofile/bp-xprofile-filters.php:118]: @sadrul Please remove the background update here. If we have provided the repair tool that's enough.

File: src/bp-xprofile/bp-xprofile-filters.php [hunk 4]
```diff
@@ -1061,3 +1061,187 @@ function bp_xprofile_exclude_display_name_profile_fields( $args ){
...
 }
+
+/**
+ * Add xprofile notification repair list item.
+ *
+ * @param array $repair_list Repair list items.
+ *
+ * @return array Repair list items.
+ *
+ * @since BuddyBoss 1.6.2
```
Comment (KartikSuthar) [inline src/bp-xprofile/bp-xprofile-filters.php:1072]: @sadrul Update the since to latest release.

File: src/bp-xprofile/bp-xprofile-filters.php [hunk 5]
```diff
@@ -1061,3 +1061,187 @@ function bp_xprofile_exclude_display_name_profile_fields( $args ){
...
+ */
+function bb_xprofile_repeater_field_repair( $repair_list ) {
+	$get_bp_xprofile_migration = (bool) bp_get_option( 'bp_xprofile_migration' );
```
Comment (KartikSuthar) [inline src/bp-xprofile/bp-xprofile-filters.php:1075]: Remove the option as we provide the tool always.

File: src/bp-xprofile/bp-xprofile-filters.php [hunk 6]
```diff
@@ -1061,3 +1061,187 @@ function bp_xprofile_exclude_display_name_profile_fields( $args ){
...
+}
+
+/**
+ * This function will work as migration process which will remove duplicate repeater field from database by repair tool.
+ * Also remove remove unnecessary data that may have remained after the migration process.
+ * This function will be called only once.
+ *
+ * @uses bb_xprofile_repeater_field_migration
+ *
+ * @since BuddyBoss 1.6.2
```
Comment (KartikSuthar) [inline src/bp-xprofile/bp-xprofile-filters.php:1093]: Update the since to latest release.

File: src/bp-xprofile/bp-xprofile-filters.php [hunk 7]
```diff
@@ -1061,3 +1061,187 @@ function bp_xprofile_exclude_display_name_profile_fields( $args ){
...
+ * This function will work as migration process which will remove duplicate repeater field from database.
+ * Also remove remove unnecessary data that may have remained after the migration process.
+ * This function will be called only once.
+ *
+ * @param int     $offset offset.
+ * @param boolean $callback callback.
+ *
+ * @return array
+ *
+ * @since BuddyBoss 1.6.2
```
Comment (KartikSuthar) [inline src/bp-xprofile/bp-xprofile-filters.php:1116]: Update the since to latest release.

File: src/bp-xprofile/bp-xprofile-filters.php [hunk 8]
```diff
@@ -1061,3 +1061,187 @@ function bp_xprofile_exclude_display_name_profile_fields( $args ){
...
+ */
+function bb_xprofile_repeater_field_migration( $offset, $callback ) {
```
Comment (KartikSuthar) [inline src/bp-xprofile/bp-xprofile-filters.php:1118]: @sadrul I have checked the code and it's not working for me. Can you please test and update accordingly?

File: src/bp-xprofile/bp-xprofile-filters.php [hunk 9]
```diff
@@ -1061,3 +1061,187 @@ function bp_xprofile_exclude_display_name_profile_fields( $args ){
...
+}
+
+/**
+ * This function will remove unnecessary data that may have remained after the above migration process.
+ *
+ * @param int $group_id Group id.
+ *
+ * @return boolean
+ *
+ * @since BuddyBoss 1.6.2
```
Comment (KartikSuthar) [inline src/bp-xprofile/bp-xprofile-filters.php:1196]: Update the since to latest release.

File: src/bp-xprofile/bp-xprofile-repeaters.php [hunk 10]
```diff
@@ -365,43 +378,46 @@ function bp_clone_field_for_repeater_sets( $field_id ) {
...
 			$new_field_column_data_types
 		);
-
 		if ( $inserted ) {
 			$new_field_id = $wpdb->insert_id;
 			$metas        = $wpdb->get_results( "SELECT * FROM {$bp->profile->table_name_meta} WHERE object_id = {$template_field_id} AND object_type = 'field'", ARRAY_A );
 			if ( ! empty( $metas ) && ! is_wp_error( $metas ) ) {
 				foreach ( $metas as $meta ) {
-					bp_xprofile_update_meta( $new_field_id, 'field', $meta['meta_key'], $meta['meta_value'] );
+					bp_xprofile_add_meta( $new_field_id, 'field', $meta['meta_key'], $meta['meta_value'] );
```
Comment (KartikSuthar) [inline src/bp-xprofile/bp-xprofile-repeaters.php:386]: I think it's not needed. Please revert with `bp_xprofile_update_meta`

File: src/bp-xprofile/bp-xprofile-repeaters.php [hunk 11]
```diff
@@ -365,43 +378,46 @@ function bp_clone_field_for_repeater_sets( $field_id ) {
...
 			}
-
 			$current_clone_number = 1;
-
 			// get all clones of the template field
 			$all_clones = $wpdb->get_col( "SELECT object_id FROM {$bp->profile->table_name_meta} WHERE meta_key = '_cloned_from' AND meta_value = {$template_field_id}" );
 			if ( ! empty( $all_clones ) && ! is_wp_error( $all_clones ) ) {
+				/**
+				 * MAX( CAST(meta_value AS DECIMAL) ) - Dont use space between CAST(meta_value AS DECIMAL) those brackets.
+				 * It will issuing in query.
```
Comment (KartikSuthar) [inline src/bp-xprofile/bp-xprofile-repeaters.php:395]: Update the typo.

File: src/bp-xprofile/bp-xprofile-repeaters.php [hunk 12]
```diff
@@ -921,3 +942,42 @@ function bp_profile_repeaters_search_change_filter( $f ) {
 	$f->filter = 'contains';
 	return $f;
 }
+
+/**
+ * Function will delete duplicate field order which inserted last from DB.
+ *
+ * @since BuddyBoss 1.6.2
```
Comment (KartikSuthar) [inline src/bp-xprofile/bp-xprofile-repeaters.php:949]: Update the since to latest release.

File: src/bp-xprofile/bp-xprofile-filters.php [hunk 13]
```diff
@@ -1061,3 +1061,89 @@ function bp_xprofile_exclude_display_name_profile_fields( $args ){
...
 }
+
+/**
+ * Add xprofile notification repair list item.
+ *
+ * @param array $repair_list Repair list items.
+ *
+ * @return array Repair list items.
+ *
+ * @since BuddyBoss 1.7.2.3
```
Comment (KartikSuthar) [inline src/bp-xprofile/bp-xprofile-filters.php:1072]: @sadrul update the since tag to latest release.

File: src/bp-xprofile/bp-xprofile-filters.php [hunk 14]
```diff
@@ -1061,3 +1061,89 @@ function bp_xprofile_exclude_display_name_profile_fields( $args ){
...
+}
+
+/**
+ * This function will work as migration process which will remove duplicate repeater field from database by repair tool.
+ * Also remove remove unnecessary data that may have remained after the migration process.
+ * This function will be called only once.
+ *
+ * @uses bb_xprofile_repeater_field_migration
+ *
+ * @since BuddyBoss 1.7.2.3
```
Comment (KartikSuthar) [inline src/bp-xprofile/bp-xprofile-filters.php:1090]: update the since tag to the latest release.

File: src/bp-xprofile/bp-xprofile-filters.php [hunk 15]
```diff
@@ -1061,3 +1061,89 @@ function bp_xprofile_exclude_display_name_profile_fields( $args ){
...
+ * This function will work as migration process which will remove duplicate repeater field from database.
+ * Also remove remove unnecessary data that may have remained after the migration process.
+ * This function will be called only once.
+ *
+ * @param int     $offset offset.
+ * @param boolean $callback callback.
+ *
+ * @return array
+ *
+ * @since BuddyBoss 1.7.2.3
```
Comment (KartikSuthar) [inline src/bp-xprofile/bp-xprofile-filters.php:1108]: update the since tag to the latest release.

File: src/bp-xprofile/bp-xprofile-repeaters.php [hunk 16]
```diff
@@ -921,3 +951,42 @@ function bp_profile_repeaters_search_change_filter( $f ) {
 	$f->filter = 'contains';
 	return $f;
 }
+
+/**
+ * Function will delete duplicate field order which inserted last from DB.
+ *
+ * @since BuddyBoss 1.7.2.3
```
Comment (KartikSuthar) [inline src/bp-xprofile/bp-xprofile-repeaters.php:958]: update the since tag to the latest release.

**Review by KartikSuthar — CHANGES_REQUESTED** [review]

**Review by KartikSuthar — DISMISSED** [review]

**Comment by sadrul** [comment]
@sumitbuddyboss @mohit-buddyboss Merged to dev and ready for testing
cc: @sourabhmatolia

**Comment by sumitbuddyboss** [comment]
Hello @sadrul 

Fixed >
I have checked in dev and fix/1082 branch and related issue are resolved now, for the proof please check the below video.

**Video:**
https://www.loom.com/share/3aa90c31abc54d9786bf7bebf7a9e167

Ready to release 🚀 

Thank you

**Review by KartikSuthar — APPROVED** [review]
