### PR TITLE
PROD-829 Fixed #2346 - Searching with ampersand character is not working

### LINKED ISSUE #2346: Searching with ampersand character is not working
**Describe the bug**
When searching for

**To Reproduce**
1. Try to  create a post, forum, or a group with a title that contains ampersand like "Sample & Test"
2. Now go to the frontend and use the Global Search field
3. Input the title
4. Notice the issue

**Screenshots**
ss

**Support ticket links**
https://secure.helpscout.net/conversation/1486276552/136971

**Jira issue** : [PROD-829]

[PROD-829]: https://buddyboss.atlassian.net/browse/PROD-829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by kent-carlo**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2346 

### How to test the changes in this Pull Request:

1. Try to  create a post, forum, or a group with a title that contains ampersand like "Sample & Test"
2. Now go to the frontend and use the Global Search field
3. Input the title
4. Notice the issue

### Proof Screenshots or Video

ss

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

File: src/bp-search/classes/class-bp-search.php [hunk 1]
```diff
@@ -253,7 +253,9 @@ public function ajax_search() {
 			}
 
 			$args = array(
-				'search_term'   => $_REQUEST['search_term'],
+
+				// Needed to replace '&' with '&amp;' so it matches the data in db. '&' symbol usually be replaced with '&amp;' when saving in database.
+				'search_term'   => str_replace('&', '&amp;', $_REQUEST['search_term']),
```
Comment (dipskakadiya) [inline src/bp-search/classes/class-bp-search.php:258]: @kent-carlo Instead of `str_replace` you should use `htmlspecialchars` function to encode HTML. 
I'm assuming we need to replace all HTML special chars except quote. 

```echo htmlspecialchars($str, ENT_NOQUOTES);```

You need to do some test with adding aal HTML special chars.

**Review by dipskakadiya — CHANGES_REQUESTED** [review]
@kent-carlo Please check my comment.

File: src/bp-search/classes/class-bp-search.php (hunk 1 above)
Comment (kent-carlo) [reply src/bp-search/classes/class-bp-search.php:258]: @dipskakadiya I will try, thanks

**Comment by kent-carlo** [comment]
@dipskakadiya I have changed it and also tested with the rest of html special chars

**Review by dipskakadiya — DISMISSED** [review]
@kent-carlo Approved. Prepare for testing.

**Comment by varunqa** [comment]
Verifier Result- Fixed 

Screen Short - https://prnt.sc/1s5stgi  ,  https://prnt.sc/1s5sxoi
 Steps- 
 1.Login in Web and App and go to the group , Activity, etc.
 2.Search for any Group or any Activity in App  and Web
 3.Observe

Build Version For iOS - 3.0.9 (310)

**Comment by varunqa** [comment]
Verified Result - Not Fixed

Tested on Site : https://bb-app-platform.flywheelsites.com/

Attached Screenshot - 
By entering Sample : 
image

By entering "Sample & group test"
image

**Comment by varunqa** [comment]
Verify Result - Not Fixed

Screen short - https://prnt.sc/1se9adt

**Comment by kent-carlo** [comment]
@varunqa Checking

**Comment by kent-carlo** [comment]
> Verify Result - Not Fixed
> 
> Screen short - https://prnt.sc/1se9adt

@varunqa  I just tested https://prnt.sc/1sf3oiw

**Review by dipskakadiya — APPROVED** [review]

**Review by chetansatasiya — APPROVED** [review]

**Comment by joeytoribio** [comment]
Hi @kent-carlo,

This has been tested in qa-ongoing and still getting a no result.

### Test Case Title:
Searching with ampersand character is not working

**To Reproduce:**

1] Create a post in **Activity Feed**, **forum** and **group** with a title that contains ampersand like "Sample & Test"
2] Now go to the frontend and use the Global Search field
3] Input the title

**Result: FAILED**

**Remarks:**
The fix is still not merged in qa-only and it only works for the post in activity feeds. For a post with an ampersand in forum or group, it's still not working

**Video:**
https://www.loom.com/share/8d46937d245e4003b713771b5c10ef5b

Thank you!

**Comment by joeytoribio** [comment]
Hi @kent-carlo,

This has been retested in the qa-ongoing branch with 1 issue found in Forum.

### Test Case#1
News Feed: Searching with ampersand character is not working

**To Reproduce:**

1] Create a post in Activity Feed with a title that contains ampersand like "Sample & Test".
2] Now go to the frontend and use the Global Search field
3] Input the title and wait for the suggestion

**Result: PASSED**

**Video:**
https://www.loom.com/share/0700ad18526f4338b5e568532330be51

### Test Case#2
Forum: Searching with ampersand character is not working

**To Reproduce:**

1] Create a Forum and create a new discussion in the forum with a title that contains ampersand like "Sample & Test".
2] Now go to the frontend and use the Global Search field
3] Input the title and wait for the suggestion

**Result: FAILED**

**Remarks:**
Testing in Master branch without any issue however, in qa-ongoing the created Forum is no longer showing in the suggestion. Only post is only showing

**Video:**
https://www.loom.com/share/d124423ef95942de8fc9409e10f0711d 

### Test Case#3
Group: Searching with ampersand character is not working

**To Reproduce:**

1] Create a Group and create a new post in the Group feed with a title that contains ampersand like "Sample & Test".
2] Now go to the frontend and use the Global Search field
3] Input the title and wait for the suggestion

**Result: PASSED**

**Video:**
https://www.loom.com/share/735038fef9cc42ca9794163c9d1874f9

**Review by KartikSuthar — APPROVED** [review]

**Comment by joeytoribio** [comment]
Hi @kent-carlo,

As per checking the issue still not fixed in qa-ongoing branch.

### Test Case#2
Forum: Searching with ampersand character is not working

**To Reproduce:**

1] Create a Forum and create a new discussion in the forum with a title that contains ampersand like "Sample & Test".
2] Now go to the frontend and use the Global Search field
3] Input the title and wait for the suggestion

**Result: FAILED**

**Remarks:**
Testing in Master branch without any issue however, in qa-ongoing the created Forum is no longer showing in the suggestion. Only post is only showing

**Video:**
https://www.loom.com/share/d0dcbccae66a42218befab99db44cc3c
