### PR TITLE
Fixed : Group members can't see their hidden group when a group page …

### LINKED ISSUE #1171: Group members can't see their hidden group when a group page is created with the group type shortcode
**Describe the bug**
Group members can't see their hidden group when a group page is created with the group type shortcode. It works when the group privacy is public and private.

**To Reproduce - Video Explanation**
Steps to reproduce the behavior: https://www.loom.com/share/4ae51e6e43354b748622f44d497a7f2c

**Expected behavior**
Group members see their hidden groups.

**Support ticket links**
https://secure.helpscout.net/conversation/1218549643/82261

### PR DESCRIPTION
**Pull request by shohelbuddyboss**
…is created with the group type shortcode #1171

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1171 .

### How to test the changes in this Pull Request:

1. replaced bp_displayed_user_id() with bbp_get_current_user_id(), Cause it's not returning actual user ID when user switched and switched users on a page.
2. `wp-content/plugins/buddyboss-platform/src/bp-groups/bp-groups-template.php`
3. Line number `426`

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fixed: Group members can't see their hidden group when a group page is created with the group type shortcode #1171

### CODE REVIEW

File: src/bp-groups/bp-groups-template.php [hunk 1]
```diff
@@ -420,7 +423,7 @@ function bp_has_groups( $args = '' ) {
 			'max'                => false,
 			'show_hidden'        => false,
 			'page_arg'           => 'grpage',
-			'user_id'            => bp_displayed_user_id(),
+			'user_id'            => bbp_get_current_user_id(),
```
Comment (chetansatasiya) [inline src/bp-groups/bp-groups-template.php:426]: `bbp_get_current_user_id` function is a part of the forums and when any site have a forum component is disabled then it will trigger a Fatal error and site will be crashed.

**Comment by shohelbuddyboss** [comment]
updated and added Wordpress native function `get_current_user_id()`

File: src/bp-groups/bp-groups-template.php [hunk 2]
```diff
@@ -420,7 +423,7 @@ function bp_has_groups( $args = '' ) {
 			'max'                => false,
 			'show_hidden'        => false,
 			'page_arg'           => 'grpage',
-			'user_id'            => bp_displayed_user_id(),
+			'user_id'            => get_current_user_id(),
```
Comment (chetansatasiya) [inline src/bp-groups/bp-groups-template.php:426]: @shohelbuddyboss @shohel It will not work as I said in Slack. So make the changes in that shortcode as discuseed.

**Comment by shohelbuddyboss** [comment]
@chetansatasiya I've changed as you suggest. Please check now.
