### PR TITLE
PROD-781 Symbolic links settings changed when updating the activity settings - issue fixed

### LINKED ISSUE #2647: Updating the activity settings page reverts the symbolic links option as enabled
**Describe the bug**
Updating the activity settings page reverts the media symbolic link option to enable.

We tested this issue on the dev stage and found whenever we click on the Settings > Activity > save settings 
then enables the Settings > Media > Media Security & Performance > Symbolic link option
Dev staging demo - https://www.awesomescreenshot.com/video/4568225?key=5635263a3e7839589f20b7a42c27bf53
 
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to media settings and disable the Symbolic link option (if enabled)
2. Move on the activity setting page and just click save settings
3. Again back to the media settings and check the Symbolic link option
4. You will see the option is enabled

**Expected behaviour**
Updating activity settings should not affect media settings.

**Screenshots**
Issue from customer- https://www.awesomescreenshot.com/video/4566666?key=cd8791a7a4695cbfca5171371dba5002

**Environment**
BuddyBoss-Platform Version 1.7.2.2 
Customer site as well as on dev staging site

**Support ticket links**
https://secure.helpscout.net/conversation/1577225764/154530?folderId=3709082

**Jira issue** : [PROD-781]

[PROD-781]: https://buddyboss.atlassian.net/browse/PROD-781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by mahedihasannoman**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2647  .

### How to test the changes in this Pull Request:

1. Go to media settings and disable the Symbolic link option (if enabled)
2. Move on the activity setting page and just click save settings
3. Again back to the media settings and check the Symbolic link option
4. You will see the option is not enabled

### Proof Screenshots or Video

https://www.loom.com/share/6518689706da43a18436f801ac5b194b

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

File: src/bp-core/admin/settings/bp-admin-setting-activity.php [hunk 1]
```diff
@@ -67,7 +67,7 @@ public function settings_save() {
 		require_once $bp->plugin_dir . '/bp-core/admin/bp-core-admin-schema.php';
 
 		$bp->active_components = $active_components;
-		bp_core_install( $bp->active_components );
+		bp_core_install( $active_components );
```
Comment (dipskakadiya) [inline src/bp-core/admin/settings/bp-admin-setting-activity.php:70]: @mahedihasannoman this line changes is not needed.

**Review by dipskakadiya — CHANGES_REQUESTED** [review]

File: src/bp-core/admin/bp-core-admin-schema.php [hunk 2]
```diff
@@ -87,7 +87,9 @@ function bp_core_install( $active_components = false ) {
 	if ( ! empty( $active_components['media'] ) ) {
 		bp_core_install_media();
 		bp_core_install_document();
-		bb_core_enable_default_symlink_support();
+		if ( (bool) get_option( 'bp_media_symlink_support', false ) ) {
```
Comment (dipskakadiya) [inline src/bp-core/admin/bp-core-admin-schema.php:90]: @mahedihasannoman 
https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-core/bp-core-functions.php#L5718-L5720
Check above code. 
In `bb_core_enable_default_symlink_support` we already check this condition so i don't think it's needed

**Review by dipskakadiya — CHANGES_REQUESTED** [review]

File: src/bp-core/admin/bp-core-admin-schema.php (hunk 2 above)
Comment (mahedihasannoman) [reply src/bp-core/admin/bp-core-admin-schema.php]: Hi @dipskakadiya , I have removed the condition from here and updated the conditions inside the `bb_core_enable_default_symlink_support` function.

**Review by dipskakadiya — APPROVED** [review]

**Review by KartikSuthar — APPROVED** [review]
