### PR TITLE
bug fix re call to distance search icon for Profile Search

### LINKED ISSUE #1073: Profile Search > Distance: missing icon
**Describe the bug**
The _locator.png_ is called from the wrong dir and results on a 404.

**To Reproduce**

1. Install Version 4.1 of the [BP xProfile Location](https://wordpress.org/plugins/bp-xprofile-location/) plugin
2. In Platform > Profile Search, add a Location field and set _search mode_ to _distance_
3. Go to the members directory
4. Note the missing icon in the Profile Search interface

**Expected behavior**
A pull request for this simple fix has been submitted.

### PR DESCRIPTION
**Pull request by shanebp**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?

### Changes proposed in this Pull Request:

Change the call for the locator.png so that it is loaded from its actual location in Platform. 

Fixes #1073

### How to test the changes in this Pull Request:

1. Install Version 4.1 of the BP xProfile Location plugin
2. In Platform > Profile Search, add a Location field and set search mode to distance
3. Go to the members directory
4. The locator.png should no longer be 404

BP xProfile Location: https://wordpress.org/plugins/bp-xprofile-location/

### CODE REVIEW

File: src/bp-core/profile-search/templates/members/bps-form-default.php [hunk 1]
```diff
@@ -130,7 +130,7 @@
 			$km          = __( 'km', 'buddyboss' );
 			$miles       = __( 'miles', 'buddyboss' );
 			$placeholder = __( 'Start typing, then select a location', 'buddyboss' );
-			$icon_url    = plugins_url( 'bp-profile-search/templates/members/locator.png' );
+			$icon_url    = BP_PLATFORM_API . 'bp-core/profile-search/templates/members/locator.png';
```
Comment (chetansatasiya) [inline src/bp-core/profile-search/templates/members/bps-form-default.php:133]: @shanebp it should be a like this `buddypress()->plugin_url` instead of `BP_PLATFORM_API`
```suggestion
			$icon_url    = buddypress()->plugin_url . 'bp-core/profile-search/templates/members/locator.png';
```

File: src/bp-templates/bp-nouveau/buddypress/common/search/profile-search.php [hunk 2]
```diff
@@ -222,7 +222,7 @@
 					$km          = __( 'km', 'buddyboss' );
 					$miles       = __( 'miles', 'buddyboss' );
 					$placeholder = __( 'Start typing, then select a location', 'buddyboss' );
-					$icon_url    = plugins_url( 'bp-profile-search/templates/members/locator.png' );
+					$icon_url    = BP_PLATFORM_API . 'bp-core/profile-search/templates/members/locator.png';
```
Comment (chetansatasiya) [inline src/bp-templates/bp-nouveau/buddypress/common/search/profile-search.php:225]: @shanebp  same here it should be a like this `buddypress()->plugin_url` instead of `BP_PLATFORM_API`

```suggestion
					$icon_url    = buddypress()->plugin_url  . 'bp-core/profile-search/templates/members/locator.png';
```

Comment (shanebp) [reply src/bp-templates/bp-nouveau/buddypress/common/search/profile-search.php:225]: I have made the changes you suggest. 
It is okay now?
