### PR TITLE
PROD-775 Group & Forum settings field will not show in activity settings when group & forum deactivated

### LINKED ISSUE #2725: Group and Forum modules are disabled but their settings are not.
**Describe the bug**
Group and Forum modules are disabled but their setting options are visible in the activity settings tab.

**To Reproduce**
1. Go to BuddyBoss setting components and disabled **Social Groups** and **Forum Discussions** modules.
2. Go to BuddyBoss Activity settings tab.
3. Find the **Posts in Activity Feeds** settings section.
4. Now you can see some of the setting options are visible ( Member creates a group,  Member joins a group, Group details are updated, Member creates a forum discussion, Member replies to a forum discussion ) that are dependent on Group and Forum modules.

**Expected behavior**
Setting options are should be hide when Group and Forum modules are disabled and should be visible when they are active.

**Screenshots**
https://prnt.sc/1iz27n6

**Environment**
Which site did you replicate this issue on?

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

### PR DESCRIPTION
**Pull request by mahedihasannoman**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2725  .

### How to test the changes in this Pull Request:

1. Go to BuddyBoss setting components and disabled Social Groups and Forum Discussions modules.
2. Go to BuddyBoss Activity settings tab.
3. Find the Posts in Activity Feeds settings section.
4. Now you will not see, some of the setting options like Member creates a group, Member joins a group, Group details are updated, Member creates a forum discussion, Member replies to a forum discussion that are dependent on Group and Forum modules.

### Proof Screenshots or Video

https://www.loom.com/share/f7507297a620450f8e485b0b1c25cd87

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by dipskakadiya — APPROVED** [review]

File: src/bp-core/bp-core-functions.php [hunk 1]
```diff
@@ -4332,49 +4332,58 @@ function bp_core_get_active_custom_post_type_feed() {
...
 				'activity_name'  => 'bbp_reply_create',
 				'activity_label' => __( 'Member replies to a forum discussion', 'buddyboss' ),
 			),
-		)
-	);
+		) );
+	}
 
-	return $activity_type;
+	return apply_filters( 'bp_platform_default_activity_types', $settings_fields );
```
Comment (chetansatasiya) [inline src/bp-core/bp-core-functions.php:4386]: all new filters should start with `bb_` instead of `bp_`

also missed the doc block of the filter with proper info.

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@mahedihasannoman Need requested changes

**Review by jitendrabanjara1991 — APPROVED** [review]
