### PR TITLE
PROD-716 Fix slug accent issue

### LINKED ISSUE #3074: Forum is not visible while creating Group
**Describe the bug**
The client trying to create a group with a forum, however, no option for a forum only a blank page, https://prnt.sc/1uv294r

**To Reproduce**
1. Go to 'BuddyBoss Setting -> Forums'
2. Change slug single forum slug to `fórum`
3. Try to Create group from frontend.
4. See error.

**Screenshots**
https://prnt.sc/1uv294r

**Support ticket links**
https://secure.helpscout.net/conversation/1647570363/0/?folderId=5218799

**Jira issue** : [PROD-716]

[PROD-716]: https://buddyboss.atlassian.net/browse/PROD-716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by kishanjasani**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #3074 

### How to test the changes in this Pull Request:

1. Go to BuddyBoss setting page -> forum
2. Change the forum slug to `fórum`
3. Now go to frontend and check the forum creation is working while creating the group

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

File: src/bp-forums/admin/functions.php [hunk 1]
```diff
@@ -165,8 +165,10 @@ function bbp_sanitize_slug( $slug = '' ) {
 	$value = ltrim( $value, '/' );
 	$value = rtrim( $value, '/' );
 
+	$slug = remove_accents( apply_filters( 'bbp_sanitize_slug', $value, $slug ) );
```
Comment (chetansatasiya) [inline src/bp-forums/admin/functions.php:168]:
```suggestion
	return remove_accents( apply_filters( 'bbp_sanitize_slug', $value, $slug ) );
```

No need to take this in variable just return from here.

File: src/bp-forums/admin/functions.php [hunk 2]
```diff
@@ -165,8 +165,10 @@ function bbp_sanitize_slug( $slug = '' ) {
...
+
 	// Filter the result and return
-	return apply_filters( 'bbp_sanitize_slug', $value, $slug );
+	return $slug;
```
Comment (chetansatasiya) [inline src/bp-forums/admin/functions.php:171]:
```suggestion
	
```
Remove return

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
Need changes

**Review by chetansatasiya — APPROVED** [review]
