### PR TITLE
LearnDash courses count not showing on Groups view #1602

### LINKED ISSUE #1602: LearnDash courses count not showing on Groups view
**Describe the bug**
Courses count on tab not showing on Group view

**To Reproduce**

Issue can be replicated on LearnDash demo

Create a Course
Add course to a group
View group on front end
See error on Courses tab
(you can view this directly on our LearnDash demo, just vising Coffee Addicts group)

**Expected behavior**
Courses count show show in the tab just like Members tab

**Screenshots**
https://user-images.githubusercontent.com/58522224/92922198-040da280-f468-11ea-9e33-439846cff2c1.JPG

**Support ticket links**
https://secure.helpscout.net/conversation/1263411275/89929

### PR DESCRIPTION
**Pull request by shohelbuddyboss**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1602 .

### Changelog entry

> Fixed: LearnDash courses count not showing on Groups view #1602

### CODE REVIEW

**Comment by shohelbuddyboss** [comment]
@chetansatasiya 

Moved this issue from theme to Platform, the course count issue is now solved from the integration.
Please make a review.

cc @sourabhmatolia

File: src/bp-templates/bp-nouveau/includes/template-tags.php [hunk 1]
```diff
@@ -1282,6 +1282,10 @@ function bp_nouveau_nav_has_count() {
 		$count = 0 !== (int) bp_media_get_total_group_media_count();
 	} elseif ( 'groups' === $bp_nouveau->displayed_nav && bp_is_active( 'media' ) && bp_is_group_albums_support_enabled() && 'albums' === $nav_item->slug ) {
 		$count = 0 !== (int) bp_media_get_total_group_album_count();
+	} elseif ( 'groups' === $bp_nouveau->displayed_nav && 'courses' === $nav_item->slug ) {
```
Comment (chetansatasiya) [inline src/bp-templates/bp-nouveau/includes/template-tags.php:1285]: @shohelbuddyboss what will happen if someone change `courses` to something else via `apply_filters( 'bp_ld_sync/courses_group_tab_slug', 'courses' )` this filter.

File: src/bp-templates/bp-nouveau/includes/template-tags.php [hunk 2]
```diff
@@ -1333,6 +1337,10 @@ function bp_nouveau_get_nav_count() {
 		$count = bp_media_get_total_group_media_count();
 	} elseif ( 'groups' === $bp_nouveau->displayed_nav && bp_is_active( 'media' ) && bp_is_group_albums_support_enabled() && 'albums' === $nav_item->slug ) {
 		$count = bp_media_get_total_group_album_count();
+	} elseif ( 'groups' === $bp_nouveau->displayed_nav && 'courses' === $nav_item->slug ) {
```
Comment (chetansatasiya) [inline src/bp-templates/bp-nouveau/includes/template-tags.php:1340]: @shohelbuddyboss what will happen if someone change `courses` to something else via `apply_filters( 'bp_ld_sync/courses_group_tab_slug', 'courses' )` this filter.

**Review by chetansatasiya — CHANGES_REQUESTED** [review]

**Comment by chetansatasiya** [comment]
@shohelbuddyboss See my comment.

File: src/bp-templates/bp-nouveau/includes/template-tags.php (hunk 2 above)
Comment (shohelbuddyboss) [reply src/bp-templates/bp-nouveau/includes/template-tags.php]: Edited and applied the same filters on this sting, so if anyone changes, it will change also here.
Code I wrote, `$coursesSlug     = apply_filters( 'bp_ld_sync/courses_group_tab_slug', 'courses' );`

File: src/bp-templates/bp-nouveau/includes/template-tags.php (hunk 1 above)
Comment (shohelbuddyboss) [reply src/bp-templates/bp-nouveau/includes/template-tags.php]: Edited and applied the same filters on this sting, so if anyone changes, it will change also here.
Code I wrote, `$coursesSlug     = apply_filters( 'bp_ld_sync/courses_group_tab_slug', 'courses' );`

File: src/bp-templates/bp-nouveau/includes/template-tags.php [hunk 3]
```diff
@@ -1333,6 +1339,10 @@ function bp_nouveau_get_nav_count() {
 		$count = bp_media_get_total_group_media_count();
 	} elseif ( 'groups' === $bp_nouveau->displayed_nav && bp_is_active( 'media' ) && bp_is_group_albums_support_enabled() && 'albums' === $nav_item->slug ) {
 		$count = bp_media_get_total_group_album_count();
+	} elseif ( 'groups' === $bp_nouveau->displayed_nav && $coursesSlug === $nav_item->slug ) {
```
Comment (chetansatasiya) [inline src/bp-templates/bp-nouveau/includes/template-tags.php:1347]: @shohelbuddyboss Can you follow the naming convention of the variable name of WP `coursesSlug` should be a `courses_slug` ? Can you make the change please? and also make the tabbing proper here?

File: src/bp-templates/bp-nouveau/includes/template-tags.php [hunk 4]
```diff
@@ -1320,6 +1325,7 @@ function bp_nouveau_get_nav_count() {
 	$bp_nouveau = bp_nouveau();
 	$nav_item   = $bp_nouveau->current_nav_item;
 	$count      = 0;
+	$coursesSlug     = apply_filters( 'bp_ld_sync/courses_group_tab_slug', 'courses' );
```
Comment (chetansatasiya) [inline src/bp-templates/bp-nouveau/includes/template-tags.php]: @shohelbuddyboss Can you follow the naming convention of the variable name of WP `coursesSlug` should be a `courses_slug` ? Can you make the change please? and also make the tabbing proper here?

**Review by chetansatasiya — CHANGES_REQUESTED** [review]

**Review by chetansatasiya — APPROVED** [review]
@ankitguptaindia Need to test this

**Comment by ankitguptaindia** [comment]
@shohel @chetansatasiya 

Issue has been fixed.  Counts are appearing now as per the attached courses.  https://i.imgur.com/g32LHuy.jpg

https://www.loom.com/share/f26e1c7f3c59481c9bf9cd6af05434e3

**Review by ankitguptaindia — APPROVED** [review]
@sourabhmatolia This PR is ready to Release 🚀

**Comment by basil-buddyboss** [comment]
Hi @shohelbuddyboss 

I have tested this using QA ongoing branch and the courses count is still not showing in the course tab on Groups view.

To reproduce:
Pre-condition:
1. LearnDash is activated
2. The LearnDash group sync and Social Group sync is enabled from BuddyBoss> Integration> LearnDash

Steps:
1. Create a public social group and sync with the LearnDash group
2. Add courses in the LearnDash group
3. View the group in the frontend and check the courses tab

Video:
https://watch.screencastify.com/v/l9pj8KFQT5dvVzNHuHF0

Remarks: The fix is still not yet merged on the QA ongoing branch.

cc: @chetansatasiya

**Comment by basil-buddyboss** [comment]
Hi @chetansatasiya 
Added a comment to the new PR: https://github.com/buddyboss/buddyboss-platform/pull/3248

**Comment by basil-buddyboss** [comment]
Hi @shohelbuddyboss 

I mistakenly tested and added a comment on this PR while the commits are into dev.

Chetan created a new PR: https://github.com/buddyboss/buddyboss-platform/pull/3248 for us to be able to QA test this issue.

I already added a comment to the new PR and it is already ready for production.
