### PR TITLE
PROD-708#3095 fix filtered moderated users from the bp_get_followers and bp_get_following functions

### LINKED ISSUE #3095: Follower Widget Count is showing more numbers than actually the members avatars are been shown
**Describe the bug**
Follower Widget Count is showing more numbers than actually the members avatars are been shown, due to the suspended members, currently the count is been taken from the bp_get_follower_ids() which in turn calling get_followers() function, which is not excluding the suspended ones

**To Reproduce**
1. Enable the Moderation Component
2. And allow members to block each other (member blocking) and enable the auto suspend on 1 time blocking from the Moderation Settings( Buddyboss > Settings > Moderation )
3. Login as few multiple members with View As and click Follow
4. Get back to the admin account and add the (BB) Members Following Me Widget to the Activity Page Sidebar
5. Check the follower count in widget should be equal to the numbers of members avatar is showing in the widget
6. But if we suspend the user by going to their profile page and clicking on block, the count still counting the suspended users while the members in widget is not showing the suspended user

**Expected behavior**
Both the count and the members avatars should match

**Screenshots**
http://somup.com/cr63n53yT3

**Environment**
Client and Development site

**Support ticket links**
https://secure.helpscout.net/conversation/1653749940/167748/

**Jira issue** : [PROD-708]

[PROD-708]: https://buddyboss.atlassian.net/browse/PROD-708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by bb-yudhisthir**
Added function and filters to exclude moderated users from the widget earlier the count was also counting the moderated(hidden users) in the following functions:
bp_get_followers()
bp_get_following()

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #3095 .

### How to test the changes in this Pull Request:

1. Enable the Moderation Component
2. And allow members to block each other (member blocking) and enable the auto suspend on 1 time blocking from the Moderation Settings( Buddyboss > Settings > Moderation )
3. Login as few multiple members with View As and click Follow
4. Get back to the admin account and add the (BB) Members Following Me Widget to the Activity Page Sidebar
5. Check the follower count in widget should be equal to the numbers of members avatar is showing in the widget
6. Now suspend or block the user by going to their profile page and clicking on block and check

### Proof Screenshots or Video
https://somup.com/crXZX20YDi

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Added function and filters to exclude moderated users from the bp_get_followers and bp_get_following functions

### CODE REVIEW

File: src/bp-moderation/classes/suspend/class-bp-suspend-member.php [hunk 1]
```diff
@@ -71,6 +71,9 @@ public function __construct() {
 		add_filter( 'get_avatar_url', array( $this, 'get_avatar_url' ), 9999, 3 );
 		add_filter( 'bp_core_fetch_avatar_url_check', array( $this, 'bp_fetch_avatar_url' ), 1005, 2 );
 		add_filter( 'bp_core_fetch_gravatar_url_check', array( $this, 'bp_fetch_avatar_url' ), 1005, 2 );
+		add_filter( 'bp_get_followers', array( $this, 'bb_exclude_moderated_user_ids' ), 9999, 1 );
```
Comment (dipskakadiya) [inline src/bp-moderation/classes/suspend/class-bp-suspend-member.php:74]: @bb-yudhisthir We should exclude users from queries. I think that is the optimized way. This way will create an issue if the hidden user list is very long.

**Review by dipskakadiya — CHANGES_REQUESTED** [review]

**Review by dipskakadiya — APPROVED** [review]

**Review by chetansatasiya — APPROVED** [review]
