### PR TITLE
Fixed - Forum association with groups

### LINKED ISSUE #2112: Forum association with groups
**Describe the bug**
When 1 Forum is associated with 1 group then that forum cannot be associated with any other group. That should be the logic.
So when forum is associated with 1 group then that Forum should not show in dropdown in frontend and backend group screens. Create Group in Frontend, Manage Group in Frontend, Edit Group in Backend.
Also there should be logic while saving Forum settings to check if Forum already associated, if YES then throw error.
I think you can create issue OR note details in existing issue if any.
You have someone work on it. Thanks

-----

**Further UPDATE**

**Check Video**: https://www.loom.com/share/cbb6379fa57d45e3a8369860416398d6

- Do not allow same Forum to be associated with more than 1 Group. (already scoped above)

- Do not allow to associate sub-forums or any level child forums to any group no matter if parent forum associated with Group or No.
Do not allow to associate Forums Type Category also with the Group.
Needs to be taken care of Adding/Editing Group backend, Adding/Editing Group Frontend.

- When Forum associated with Group then Forum and all level child Forums "Visibility" Field should be disabled.

- Disable "Forum Parent" and "Type" Field when the main Forum associated with Group.

- Group Forum's Sub-Forums will inherit the same privacy as Group.
Layout will be same as Parent forum in Groups.
Single Sub-Forum URL in Group:
domain.com/groups/GROUP_SLUG/forums/SUB_FORUM_SLUG
Sub-Forum Single Discussion URL in Group (same as parent forum discussion):
domain.com/groups/GROUP_SLUG/forums/topic/DISCUSSION_SLUG/

- Sub-Forums and all level child forums and discussions always should be linked to Group URL if associated same as Parent Forum from Backend and Frontend.

- Make sure everything here is backward compatible.
IF currently one forum associated with multiple Group then let it work as it is otherwise it will break the existing customer site.
	- Same set of discussion show for both the groups
	- View Forum redirects to any one of the Group. Maybe the one assigned last. That's how it is.
	- Same workflow for child forums.
IF currently any sub-forum associated with Group then also it should work fine.

- Make sure all change here works fine with Forum settings "Allow social groups to have their own forums" both enabled or disabled.
- Settings > Forums > Group Forums Parent, Remove this settings option from BB settings panel.
Make sure everything here is backward compatible.

### Related Platform API PR
https://github.com/buddyboss/buddyboss-platform-api/pull/300

### Related Theme PR
https://github.com/buddyboss/buddyboss-theme/pull/1345

### Related App Native Issue
https://github.com/buddyboss/buddyboss-app-native/issues/1518

### PR DESCRIPTION
**Pull request by asaquzzamanbb**
### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2112.

### How to test the changes in this Pull Request:

**Check Video**: https://www.loom.com/share/cbb6379fa57d45e3a8369860416398d6

- Do not allow same Forum to be associated with more than 1 Group. (already scoped above)

- Do not allow to associate sub-forums or any level child forums to any group no matter if parent forum associated with Group or No.
Do not allow to associate Forums Type Category also with the Group.
Needs to be taken care of Adding/Editing Group backend, Adding/Editing Group Frontend.

- When Forum associated with Group then Forum and all level child Forums "Visibility" Field should be disabled.

- Disable "Forum Parent" and "Type" Field when the main Forum associated with Group.

- Group Forum's Sub-Forums will inherit the same privacy as Group.
Layout will be same as Parent forum in Groups.
Single Sub-Forum URL in Group:
domain.com/groups/GROUP_SLUG/forums/SUB_FORUM_SLUG
Sub-Forum Single Discussion URL in Group (same as parent forum discussion):
domain.com/groups/GROUP_SLUG/forums/topic/DISCUSSION_SLUG/

- Sub-Forums and all level child forums and discussions always should be linked to Group URL if associated same as Parent Forum from Backend and Frontend.

- Make sure everything here is backward compatible.
IF currently one forum associated with multiple Group then let it work as it is otherwise it will break the existing customer site.
	- Same set of discussion show for both the groups
	- View Forum redirects to any one of the Group. Maybe the one assigned last. That's how it is.
	- Same workflow for child forums.
IF currently any sub-forum associated with Group then also it should work fine.

- Make sure all change here works fine with Forum settings "Allow social groups to have their own forums" both enabled or disabled.
- Settings > Forums > Group Forums Parent, Remove this settings option from BB settings panel.
Make sure everything here is backward compatible.

### Proof Screenshots or Video
1. Do not allow same Forum to be associated with more than 1 Group.
https://www.loom.com/share/514dd48fbf534fe5a79f78470cc2c460

2. Do not allow to associate sub-forums or any level child forums to any group no matter if parent forum associated with Group or No.
Do not allow to associate Forums Type Category also with the Group.
https://www.loom.com/share/0a06a56453b84e0e95eb769cb6d581b1

3. When Forum associated with Group then Forum and all level child Forums "Visibility" Field should be disabled.
https://www.loom.com/share/232aaec6c53a4783a44eab43ea03dc30

4. Disable "Forum Parent" and "Type" Field when the main Forum associated with Group.
https://www.loom.com/share/915c2332012944e8bdb7fa59e63c9455

5. Group Forum's Sub-Forums will inherit the same privacy as Group.
https://www.loom.com/share/782df6ed23ae42c5b850f176df246993

6. Sub-Forums and all level child forums and discussions always should be linked to Group URL if associated same as Parent Forum from Backend and Frontend.
https://www.loom.com/share/e58906445715465fb2a83f4f731c8908

7. All change here works fine with Forum settings "Allow social groups " both enabled or disabled.
https://www.loom.com/share/754e3ac467c042eb8047f2af9ed49484

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### Related Platform API PR
https://github.com/buddyboss/buddyboss-platform-api/pull/300

### Related Theme PR
https://github.com/buddyboss/buddyboss-theme/pull/1345

### Related App Native Issue
https://github.com/buddyboss/buddyboss-app-native/issues/1518

### CODE REVIEW

File: src/bp-core/bp-core-update.php [hunk 1]
```diff
@@ -1137,3 +1142,103 @@ function bp_update_to_1_5_5() {
...
+
+/**
+ * Chunk the total groups as pages.
+ *
+ * @since BuddyBoss 1.5.8
+ *
+ * @return array
+ */
+function bb_update_to_1_5_8_get_pages() {
+	$total_groups = groups_get_total_group_count();
```
Comment (mehulkaklotar) [inline src/bp-core/bp-core-update.php:1177]: please check groups component is active or not before using functions from group component, otherwise it will throw fatal error for site which do not have enabled groups component.

File: src/bp-core/bp-core-update.php [hunk 2]
```diff
@@ -1137,3 +1142,103 @@ function bp_update_to_1_5_5() {
...
+ * Migrate group id, associate its forum group id.
+ *
+ * @since BuddyBoss 1.5.8
+ *
+ * @param int $page
+ *
+ * @return boolean
+ */
+function bb_update_to_1_5_8_migrate_group_id_associate_forum( $page ) {
+	$group_data = groups_get_groups( array(
```
Comment (mehulkaklotar) [inline src/bp-core/bp-core-update.php:1205]: please check groups component is active or not before using functions from group component, otherwise it will throw fatal error for site which do not have enabled groups component.

File: src/bp-core/bp-core-update.php [hunk 3]
```diff
@@ -1137,3 +1142,103 @@ function bp_update_to_1_5_5() {
...
+ *
+ * @since BuddyBoss 1.5.8
+ *
+ * @param int   $group_id
+ * @param array $forum_ids
+ *
+ * @return void
+ */
+function bb_update_to_1_5_8_update_forums_group_id( $group_id, $forum_ids ) {
+	$group_ids = array( $group_id );
```
Comment (mehulkaklotar) [inline src/bp-core/bp-core-update.php:1232]: please check groups/forums component is active or not before using functions from group/forum component, otherwise it will throw fatal error for site which do not have enabled groups/forums component.

File: src/bp-forums/admin/forums.php [hunk 4]
```diff
@@ -80,6 +80,36 @@ private function setup_actions() {
...
+		 *
+		 * @param init   post_parent post parent.
+		 * @param init   post_ID     post ID.
+		 * @param array  new_postarr submited post data.
+		 * @param object postarr     post attributes.
+		 *
+		 * @return init
+		 */
+		function filter_forum_parent( $post_parent, $post_ID, $new_postarr, $postarr ) {
+			if ( $new_postarr['post_type'] != 'forum' ) {
```
Comment (mehulkaklotar) [inline src/bp-forums/admin/forums.php:103]: please use Yoda conditions and check your code in PHPCS as well.

File: src/bp-forums/groups.php [hunk 5]
```diff
@@ -289,13 +554,63 @@ public function edit_screen( $group = false ) {
 					<h4 class="bb-section-title"><?php esc_html_e( 'Connected Forum', 'buddyboss' ); ?></h4>
 					<p class="bb-section-info"><?php esc_html_e( 'Only site administrators can reconfigure which forum belongs to this group.', 'buddyboss' ); ?></p>
 					<?php
+						// Fiter forum query for set the selected forum (Group associate forum).
+						add_filter( 'posts_where', array( $this, 'update_forum_dropdown_qeury' ), 10, 2 );
```
Comment (mehulkaklotar) [inline src/bp-forums/groups.php:558]: `update_forum_dropdown_qeury` here `query` is spelled wrong. please check it.

File: src/bp-forums/groups.php [hunk 6]
```diff
@@ -289,13 +554,63 @@ public function edit_screen( $group = false ) {
...
+											'value'   => '', 
+											'compare' => 'NOT EXISTS' 
+										),
+									)
+								)
 							)
 						);
+
+						// Remove forum query filters to prevent the conflict with others queries.
+						remove_filter( 'posts_where', array( $this, 'update_forum_dropdown_qeury' ), 10, 2 );
```
Comment (mehulkaklotar) [inline src/bp-forums/groups.php:613]: update_forum_dropdown_qeury here query is spelled wrong. please check it.

File: src/bp-forums/groups.php [hunk 7]
```diff
@@ -317,6 +632,93 @@ public function edit_screen( $group = false ) {
...
+		 * Set the selected forum in the forum dropdown from the group edit screen.
+		 *
+		 * @since BuddyBoss 1.5.7
+		 *
+		 * @param string $where        where condition forum post query.
+		 * @param object $query_object forum post query property.
+		 * 
+		 * @return string
+		 */
+		public function update_forum_dropdown_qeury( $where, $query_object ) {
```
Comment (mehulkaklotar) [inline src/bp-forums/groups.php:645]: update_forum_dropdown_qeury here query is spelled wrong. please check it.

File: src/bp-forums/groups.php [hunk 8]
```diff
@@ -317,6 +632,93 @@ public function edit_screen( $group = false ) {
...
+		 *
+		 * @since BuddyBoss 1.5.7
+		 *
+		 * @param array $forum_ids
+		 * @param int   $group_id
+		 * @uses bbp_get_forum() To get the forum.
+		 *
+		 * @return array
+		 */
+		public function get_validate_forum_ids( $forum_ids, $group_id ) {
```
Comment (mehulkaklotar) [inline src/bp-forums/groups.php:684]: change the function name to `validate_forum_ids`

File: src/bp-forums/groups.php [hunk 9]
```diff
@@ -383,9 +785,19 @@ public function edit_screen_save( $group_id = 0 ) {
 				$forum_id = (int) ( is_array( $forum_ids ) ? $forum_ids[0] : $forum_ids );
 			}
 
-			// Update the group ID and forum ID relationships
-			bbp_update_group_forum_ids( $group_id, (array) $forum_ids );
-			bbp_update_forum_group_ids( $forum_id, (array) $group_id );
+			// Is the forum associated with others group then exclude it.
+			$filter_forum_ids = $this->get_validate_forum_ids( $forum_ids, $group_id );
```
Comment (mehulkaklotar) [inline src/bp-forums/groups.php:789]: change the function name to `validate_forum_ids`

**Review by mehulkaklotar — CHANGES_REQUESTED** [review]
@asaquzzamanbb Please change all requested items here in the PR.

File: src/bp-forums/forums/template.php [hunk 10]
```diff
@@ -2740,6 +2795,42 @@ function bbp_get_form_forum_visibility_dropdown( $args = '' ) {
 	return apply_filters( 'bbp_get_form_forum_type_dropdown', ob_get_clean(), $r );
 }
 
+/**
+ * Checking whether you can update or not forum visibility.
+ *
+ * When Forum associated with Group then Forum and all level child Forums "Visibility" Field should be disabled.
+ *
+ * @since bbPress (r3563)
```
Comment (chetansatasiya) [inline src/bp-forums/forums/template.php:2803]: @asaquzzamanbb why we have this `@since bbPress (r3563)` is this function forked from bbpress?

File: src/bp-forums/groups.php [hunk 11]
```diff
@@ -32,12 +32,235 @@ class BBP_Forums_Group_Extension extends BP_Group_Extension {
...
 			$this->setup_variables();
 			$this->setup_actions();
 			$this->setup_filters();
 			$this->maybe_unset_forum_menu();
 		}
 
+		/**
+		 * Redirect 404 page when user will input wrong URL from groups forum screen.
+		 *
+		 * @since bbPress (r3552)
```
Comment (chetansatasiya) [inline src/bp-forums/groups.php:50]: @asaquzzamanbb why we have this @since bbPress (r3563) is this function forked from bbpress?

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@asaquzzamanbb This PR have a milestone `1.5.9` so all the new functions which have a since is `1.5.9` and also do the requested change

File: src/bp-forums/admin/forums.php (hunk 4 above)
Comment (asaquzzamanbb) [reply src/bp-forums/admin/forums.php]: #139448c17d98dc5293d88d247b968f9f5052a12d

File: src/bp-forums/groups.php (hunk 5 above)
Comment (asaquzzamanbb) [reply src/bp-forums/groups.php]: Fixed https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/a51489618f8f635d3ef6a0dc7d8b1a511d1be484

File: src/bp-forums/groups.php (hunk 7 above)
Comment (asaquzzamanbb) [reply src/bp-forums/groups.php]: Fixed https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/a51489618f8f635d3ef6a0dc7d8b1a511d1be484

File: src/bp-forums/groups.php (hunk 6 above)
Comment (asaquzzamanbb) [reply src/bp-forums/groups.php]: Fixed https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/a51489618f8f635d3ef6a0dc7d8b1a511d1be484

File: src/bp-forums/groups.php (hunk 8 above)
Comment (asaquzzamanbb) [reply src/bp-forums/groups.php]: Update https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/414560ca0a1366f661b41fee22788390ea057d55

File: src/bp-forums/groups.php (hunk 9 above)
Comment (asaquzzamanbb) [reply src/bp-forums/groups.php]: Update https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/414560ca0a1366f661b41fee22788390ea057d55

File: src/bp-forums/forums/template.php [hunk 12]
```diff
@@ -2552,6 +2554,59 @@ function bbp_get_form_forum_type_dropdown( $args = '' ) {
 	return apply_filters( 'bbp_get_form_forum_type_dropdown', ob_get_clean(), $r );
 }
 
+/**
+ * Checking whether you can update or not forum type.
+ *
+ * Disable "Type" field when the main Forum associated with Group.
+ *
+ * @since bbPress (r3563)
```
Comment (chetansatasiya) [inline src/bp-forums/forums/template.php:2562]: @asaquzzamanbb why we have `@since bbPress (r3563)` instead of Buddyboss

File: src/bp-forums/forums/template.php [hunk 13]
```diff
@@ -2552,6 +2554,59 @@ function bbp_get_form_forum_type_dropdown( $args = '' ) {
...
+function bbp_can_update_forum_type( $forum_id ) {
+	return bbp_has_forum_groups( $forum_id );
+}
+
+/**
+ * Checking whether you can update or not forum parent.
+ *
+ * Disable "Forum Parent" field when the main Forum associated with Group.
+ *
+ * @since bbPress (r3563)
```
Comment (chetansatasiya) [inline src/bp-forums/forums/template.php:2579]: @asaquzzamanbb why we have `@since bbPress (r3563)` instead of Buddyboss

File: src/bp-forums/forums/template.php [hunk 14]
```diff
@@ -2552,6 +2554,59 @@ function bbp_get_form_forum_type_dropdown( $args = '' ) {
...
+ * @return boolean
+ */
+function bbp_can_update_forum_parent( $forum_id ) {
+	return bbp_has_forum_groups( $forum_id );
+}
+
+/**
+ * Is the forum contain any group.
+ *
+ * @since bbPress (r3563)
```
Comment (chetansatasiya) [inline src/bp-forums/forums/template.php:2594]: @asaquzzamanbb why we have `@since bbPress (r3563)` instead of Buddyboss

**Review by chetansatasiya — CHANGES_REQUESTED** [review]

File: src/bp-forums/forums/template.php (hunk 10 above)
Comment (asaquzzamanbb) [reply src/bp-forums/forums/template.php]: Change `@since BuddyBoss 1.5.9`
https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/da785ba8a0338d2bfbd7d4c829c6d554dfa69f8e, 
https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/5890058f4ff3e80122785d2eb17b7dd25403a036,
https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/114240b580109fa63811374aa0a1f1d1f050cf6f

File: src/bp-forums/groups.php (hunk 11 above)
Comment (asaquzzamanbb) [reply src/bp-forums/groups.php]: Change `@since BuddyBoss 1.5.9`
https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/da785ba8a0338d2bfbd7d4c829c6d554dfa69f8e, https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/5890058f4ff3e80122785d2eb17b7dd25403a036, https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/114240b580109fa63811374aa0a1f1d1f050cf6f

File: src/bp-forums/forums/template.php (hunk 12 above)
Comment (asaquzzamanbb) [reply src/bp-forums/forums/template.php]: Change `@since BuddyBoss 1.5.9`
https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/da785ba8a0338d2bfbd7d4c829c6d554dfa69f8e, https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/5890058f4ff3e80122785d2eb17b7dd25403a036, https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/114240b580109fa63811374aa0a1f1d1f050cf6f

File: src/bp-forums/forums/template.php (hunk 13 above)
Comment (asaquzzamanbb) [reply src/bp-forums/forums/template.php]: Change `@since BuddyBoss 1.5.9`
https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/da785ba8a0338d2bfbd7d4c829c6d554dfa69f8e, https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/5890058f4ff3e80122785d2eb17b7dd25403a036, https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/114240b580109fa63811374aa0a1f1d1f050cf6f

File: src/bp-forums/forums/template.php (hunk 14 above)
Comment (asaquzzamanbb) [reply src/bp-forums/forums/template.php]: Change `@since BuddyBoss 1.5.9`
https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/da785ba8a0338d2bfbd7d4c829c6d554dfa69f8e, https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/5890058f4ff3e80122785d2eb17b7dd25403a036, https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/114240b580109fa63811374aa0a1f1d1f050cf6f

File: src/bp-core/bp-core-update.php [hunk 15]
```diff
@@ -1153,6 +1157,59 @@ function bb_update_to_1_5_6() {
...
+		$forum_ids = groups_get_groupmeta( $group_id, 'forum_id' );
+
+		if ( empty( $forum_ids ) ) {
+			continue;
+		}
+
+		$forum_id = array_shift( $forum_ids );
+
+		bbp_update_forum_group_ids( $forum_id, array( $group_id ) );
+	}
```
Comment (KartikSuthar) [inline src/bp-core/bp-core-update.php:1209]: @asaquzzamanbb Please update the migration it will break the current working if one forum assigns to multiple ones.

Comment (asaquzzamanbb) [reply src/bp-core/bp-core-update.php]: @KartikSuthar 
Migration has been updated here https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/f72c830994de3b58496fe6ba31c66dec21e80387

**Comment by asaquzzamanbb** [comment]
@sourabhmatolia 
UPDATE: As discussed in the scoping call with @KartikSuthar & @chetansatasiya, new app scope has been revealed for this PR. Further detail of the scope is described in the bb app native issue - https://github.com/buddyboss/buddyboss-app-native/issues/1518

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@asaquzzamanbb I am facing a wired issue on admin like If any forum is selected as a child forum then I never make any child forum to parent forum.
Screenshot 2021-08-16 at 2 19 12 PM

File: src/bp-core/bp-core-update.php [hunk 16]
```diff
@@ -1191,6 +1195,70 @@ function bb_update_to_1_5_6() {
 }
 
 /**
+ * x.x.x update routine.
```
Comment (chetansatasiya) [inline src/bp-core/bp-core-update.php:1198]: @asaquzzamanbb update x.x.x to proper version

File: src/bp-forums/admin/forums.php [hunk 17]
```diff
@@ -80,6 +80,36 @@ private function setup_actions() {
...
 			// Set forum states
 			add_filter( 'display_post_states', array( $this, 'bbp_set_hidden_forum_states' ), 10, 2 );
+
+			// Filter post parent for forum type post.
+			add_filter( 'wp_insert_post_parent', array( $this, 'forum_parent' ), 10, 3 );
+		}
+
+		/**
+		 * Permission for forum parent, If not then return the current parent.
+		 * - You can not make the forum as a child forum when its associaate with any group.
```
Comment (chetansatasiya) [inline src/bp-forums/admin/forums.php:90]:
```suggestion
		 * You can not make the forum a child forum when it's associated with any group.
```

File: src/bp-forums/common/classes.php [hunk 18]
```diff
@@ -250,6 +250,19 @@ public function start_el( &$output, $object, $depth = 0, $args = array(), $curre
 				$output .= ' value="' . (int) $object->ID . '"' . selected( $args['selected'], $object->ID, false );
 			}
 
+			/**
+			 * Add extra attributes for dropdown options.
+			 * - Default value empty.
```
Comment (chetansatasiya) [inline src/bp-forums/common/classes.php:255]:
```suggestion
			 * Default value empty.
```

File: src/bp-forums/common/template.php [hunk 19]
```diff
@@ -1617,7 +1617,7 @@ function bbp_get_dropdown( $args = '' ) {
 	// Items found so walk the tree
 	if ( ! empty( $posts ) ) {
 		add_filter( 'list_pages', 'bbp_reply_attributes_meta_box_discussion_reply_title', 999, 2 );
-		unset( $r['walker'] );
+		//unset( $r['walker'] );
```
Comment (chetansatasiya) [inline src/bp-forums/common/template.php:1620]:
```suggestion
		// unset( $r['walker'] );
```

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
Need changes

File: src/bp-core/bp-core-update.php (hunk 16 above)
Comment (asaquzzamanbb) [reply src/bp-core/bp-core-update.php:1198]: Done here https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/2de904dabcd9f83f687eb4fcff2b522667b00d93

File: src/bp-forums/common/template.php (hunk 19 above)
Comment (asaquzzamanbb) [reply src/bp-forums/common/template.php:1620]: @chetansatasiya 
How do i disabled specific option from forum drop-down without the above 'walker' parameter?

File: src/bp-forums/common/template.php [hunk 20]
```diff
@@ -1617,7 +1617,7 @@ function bbp_get_dropdown( $args = '' ) {
 	// Items found so walk the tree
 	if ( ! empty( $posts ) ) {
 		add_filter( 'list_pages', 'bbp_reply_attributes_meta_box_discussion_reply_title', 999, 2 );
-		unset( $r['walker'] );
+		// unset( $r['walker'] );
```
Comment (KartikSuthar) [inline src/bp-forums/common/template.php:1620]: @asaquzzamanbb  make it conditionally where you needed.

File: src/bp-forums/forums/template.php [hunk 21]
```diff
@@ -2530,13 +2530,16 @@ function bbp_get_form_forum_type_dropdown( $args = '' ) {
 	}
 
 	// Used variables
-	$tab = ! empty( $r['tab'] ) ? ' tabindex="' . (int) $r['tab'] . '"' : '';
+	$tab        = ! empty( $r['tab'] ) ? ' tabindex="' . (int) $r['tab'] . '"' : '';
+	$group_ids  = bbp_get_forum_group_ids( $r['forum_id'] );
+	$can_update = empty( $group_ids ) ? true : false;
```
Comment (KartikSuthar) [inline src/bp-forums/forums/template.php:2535]:
```suggestion
	$can_update = ! empty( $group_ids ) ? false : true;
```

File: src/bp-forums/forums/template.php [hunk 22]
```diff
@@ -2530,13 +2530,16 @@ function bbp_get_form_forum_type_dropdown( $args = '' ) {
...
 
 	// Start an output buffer, we'll finish it after the select loop
 	ob_start(); ?>
 
     <select name="<?php echo esc_attr( $r['select_id'] ); ?>"
-            id="<?php echo esc_attr( $r['select_id'] ); ?>_select"<?php echo $tab; ?>>
+            id="<?php echo esc_attr( $r['select_id'] ); ?>_select"<?php echo esc_attr( $tab ); ?>
+            <?php echo $can_update ? '' : esc_attr( 'disabled="disabled"' ); ?>>
```
Comment (KartikSuthar) [inline src/bp-forums/forums/template.php:2542]:
```suggestion
            <?php echo $can_update === false ? esc_attr( 'disabled="disabled"' ) : '' ; ?>>
```

File: src/bp-forums/forums/template.php [hunk 23]
```diff
@@ -2740,6 +2744,48 @@ function bbp_get_form_forum_visibility_dropdown( $args = '' ) {
...
+
+	$forum = bbp_get_forum( $forum_id );
+
+	if ( empty( $forum ) ) {
+		return array();
+	}
+
+	// Get all parent ids.
+	$parents = $forum->ancestors;
+	$parents = empty( $parents ) ? array() : $parents;
```
Comment (KartikSuthar) [inline src/bp-forums/forums/template.php:2771]: use function 
```
$parents = get_post_ancestors( $forum_id );
```

File: src/bp-forums/forums/template.php [hunk 24]
```diff
@@ -2740,6 +2744,48 @@ function bbp_get_form_forum_visibility_dropdown( $args = '' ) {
...
+
+	// Set the parameter forum_id in the parents array as its first element.
+	array_unshift( $parents, $forum->ID );
```
Comment (KartikSuthar) [inline src/bp-forums/forums/template.php:2774]:
```suggestion
	array_unshift( $parents, $forum_id );
```

File: src/bp-forums/groups.php [hunk 25]
```diff
@@ -320,6 +368,53 @@ public function edit_screen( $group = false ) {
...
+		 * @since BuddyBoss 1.7.6
+		 *
+		 * @param array $forum_id  Fourm ids.
+		 * @param int   $group_id  Group id.
+		 *
+		 * @uses bbp_get_forum() Get forum.
+		 *
+		 * @return bool
+		 */
+		public function forum_can_associate_wth_group( $forum_id, $group_id ) {
```
Comment (KartikSuthar) [inline src/bp-forums/groups.php:385]:
```suggestion
		public function forum_can_associate_with_group( $forum_id, $group_id ) {
```

File: src/bp-forums/groups.php [hunk 26]
```diff
@@ -384,6 +479,11 @@ public function edit_screen_save( $group_id = 0 ) {
 
 				// No support for multiple forums yet
 				$forum_id = (int) ( is_array( $forum_ids ) ? $forum_ids[0] : $forum_ids );
+
+				$valid_forum = $this->forum_can_associate_wth_group( $forum_id, $group_id );
```
Comment (KartikSuthar) [inline src/bp-forums/groups.php:483]:
```suggestion
				$valid_forum = $this->forum_can_associate_with_group( $forum_id, $group_id );
```

File: src/bp-forums/common/template.php (hunk 20 above)
Comment (asaquzzamanbb) [reply src/bp-forums/common/template.php]: @KartikSuthar 
Make it conditional here https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/73e8af6bd32605bb124c2c27700db51e1c1517a7

File: src/bp-forums/forums/template.php (hunk 23 above)
Comment (asaquzzamanbb) [reply src/bp-forums/forums/template.php]: @KartikSuthar 
Replace with `get_post_ancestores` function here https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/d8411ba9bdc954946c0308c9d0f7e57d817e0649

File: src/bp-forums/groups.php [hunk 27]
```diff
@@ -1390,6 +1494,119 @@ public function replies_pagination( $args ) {
...
 		}
 
+		/**
+		 * Ensure that forum content associated with a BuddyBoss group can only be viewed via the group URL.
+		 *
+		 * @since BuddyBoss 1.7.6
+		 *
+		 * @return void
+		 */
+		public function forum_redirect_canonical() {
```
Comment (KartikSuthar) [inline src/bp-forums/groups.php:1504]: Move this function to the end of the file.

File: src/bp-forums/groups.php [hunk 28]
```diff
@@ -1390,6 +1494,119 @@ public function replies_pagination( $args ) {
...
+		/**
+		 * Get forum page uri from action variables.
+		 *
+		 * @since BuddyBoss 1.7.6
+		 *
+		 * @uses bp_action_variables() URL query parameter.
+		 *
+		 * @return string
+		 */
+		public function page_uri() {
```
Comment (KartikSuthar) [inline src/bp-forums/groups.php:1592]: move this function to the end of the file.

File: src/bp-forums/groups.php [hunk 29]
```diff
@@ -320,6 +369,53 @@ public function edit_screen( $group = false ) {
...
+		 *
+		 * @param array $forum_id  Fourm ids.
+		 * @param int   $group_id  Group id.
+		 *
+		 * @uses bbp_get_forum() Get forum.
+		 *
+		 * @return bool
+		 */
+		public function forum_can_associate_with_group( $forum_id, $group_id ) {
+
```
Comment (KartikSuthar) [inline src/bp-forums/groups.php:387]: move this function to the end of the file.

File: src/bp-forums/groups.php [hunk 30]
```diff
@@ -252,6 +261,45 @@ public function remove_group_forum_meta_cap_map() {
...
+		 * @param string $attr_output Default attributes.
+		 * @param object $object      Froum post data.
+		 * @param array  $args        Froum dropdown arguments.
+		 *
+		 * @uses bbp_get_forum_post_type() Forum post type.
+		 * @uses bbp_get_forum_group_ids() Get forum group id.
+		 *
+		 * @return string
+		 */
+		public function disabled_forum_dropdown_options( $attr_output, $object, $args ) {
```
Comment (KartikSuthar) [inline src/bp-forums/groups.php:278]: move this function to the end of the file.

File: src/bp-forums/forums/template.php [hunk 31]
```diff
@@ -2740,6 +2744,48 @@ function bbp_get_form_forum_visibility_dropdown( $args = '' ) {
...
+ *
+ * @since BuddyBoss 1.7.6
+ *
+ * @param int $forum_id Forum id.
+ *
+ * @uses bbp_get_forum() Get forum.
+ *
+ * @return array
+ */
+function bb_get_child_forum_group_ids( $forum_id ) {
```
Comment (KartikSuthar) [inline src/bp-forums/forums/template.php:2758]: move this function to the end of the file.

File: src/bp-forums/admin/forums.php [hunk 32]
```diff
@@ -80,6 +80,36 @@ private function setup_actions() {
...
+		 *
+		 * @since BuddyBoss 1.7.6
+		 *
+		 * @param init  $post_parent post parent.
+		 * @param init  $post_ID     post ID.
+		 * @param array $new_postarr submited post data.
+		 *
+		 * @return init
+		 */
+		public function forum_parent( $post_parent, $post_ID, $new_postarr ) {
```
Comment (KartikSuthar) [inline src/bp-forums/admin/forums.php:100]: move this function to the end of the file.

File: src/bp-forums/groups.php (hunk 27 above)
Comment (asaquzzamanbb) [reply src/bp-forums/groups.php]: Move the at the end of the file.
https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/b2c663fb81f0630d02690c0ac5064d62ff9f8387

File: src/bp-forums/groups.php (hunk 28 above)
Comment (asaquzzamanbb) [reply src/bp-forums/groups.php]: Move the at the end of the file.
https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/b2c663fb81f0630d02690c0ac5064d62ff9f8387

File: src/bp-forums/groups.php (hunk 29 above)
Comment (asaquzzamanbb) [reply src/bp-forums/groups.php]: Move the function at the end of the file.
https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/b2c663fb81f0630d02690c0ac5064d62ff9f8387

File: src/bp-forums/groups.php (hunk 30 above)
Comment (asaquzzamanbb) [reply src/bp-forums/groups.php]: Move the function at the end of the file.
https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/b2c663fb81f0630d02690c0ac5064d62ff9f8387

File: src/bp-forums/forums/template.php (hunk 31 above)
Comment (asaquzzamanbb) [reply src/bp-forums/forums/template.php]: Move the function at the end of the file.
https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/b2c663fb81f0630d02690c0ac5064d62ff9f8387

File: src/bp-forums/admin/forums.php (hunk 32 above)
Comment (asaquzzamanbb) [reply src/bp-forums/admin/forums.php]: Move the function at the end of the file.
https://github.com/buddyboss/buddyboss-platform/pull/2117/commits/b2c663fb81f0630d02690c0ac5064d62ff9f8387

**Review by KartikSuthar — APPROVED** [review]
@asaquzzamanbb Merged to dev and pass to QA.

**Comment by asaquzzamanbb** [comment]
@KartikSuthar 
Merge done with dev branch.

https://github.com/buddyboss/buddyboss-platform/commit/b3ca66d71bb24f602e7369489110695c46df1637

**Comment by mohit-buddyboss** [comment]
@asaquzzamanbb 

Testing is going on. I'm logging issues under below sheet;
https://docs.google.com/spreadsheets/d/1YQQ3UwUTzh1A12j2ubHpvPWOJ6O4-kNK4Fgv7C9Kx8A/edit?usp=sharing

Kindly look into these issues.

cc @sourabhmatolia @chetansatasiya @KartikSuthar @firozwp

File: src/bp-core/bp-core-update.php [hunk 33]
```diff
@@ -337,6 +337,10 @@ function bp_version_updater() {
 		if ( $raw_db_version < 17401 ) {
 			bb_update_to_1_7_5();
 		}
+
+		if ( $raw_db_version < 18001 ) {
```
Comment (KartikSuthar) [inline src/bp-core/bp-core-update.php:341]:
```suggestion
		if ( $raw_db_version < 17701 ) {
```

File: src/bp-core/bp-core-update.php [hunk 34]
```diff
@@ -1190,7 +1194,7 @@ function bb_update_to_1_5_6() {
 	bp_core_install_moderation_emails();
 }
 
-/**
+/**
```
Comment (KartikSuthar) [inline src/bp-core/bp-core-update.php:1197]:
```suggestion
/**
```

File: src/bp-forums/common/classes.php [hunk 35]
```diff
@@ -250,6 +250,19 @@ public function start_el( &$output, $object, $depth = 0, $args = array(), $curre
 				$output .= ' value="' . (int) $object->ID . '"' . selected( $args['selected'], $object->ID, false );
 			}
 
+			/**
+			 * Add extra attributes for dropdown options.
+			 * Default value empty.
+			 *
+			 * @since BuddyBoss 1.7.7
+			 *
+			 * @param object $object Post data.
```
Comment (KartikSuthar) [inline src/bp-forums/common/classes.php:259]: Add first param
```suggestion
			 * @param string $attribute Option attribute.
```

**Review by KartikSuthar — CHANGES_REQUESTED** [review]

File: src/class-buddypress.php [hunk 36]
```diff
@@ -330,7 +330,7 @@ private function setup_globals() {
 
 		/** Versions */
 		$this->version    = defined( 'BP_PLATFORM_VERSION' ) ? BP_PLATFORM_VERSION : ( defined( 'BP_VERSION' ) ? BP_VERSION : '1.0.0' );
-		$this->db_version = 17401;
+		$this->db_version = 18001;
```
Comment (KartikSuthar) [inline src/class-buddypress.php:333]:
```suggestion
		$this->db_version = 17701;
```

**Review by KartikSuthar — CHANGES_REQUESTED** [review]

**Review by KartikSuthar — APPROVED** [review]

**Comment by mohit-buddyboss** [comment]
@asaquzzamanbb 

Tested this PR using QA-ongoing branch of the platform and theme. Tested all scenarios mentioned in scope. All points mentioned in scope here on : https://github.com/buddyboss/buddyboss-platform/issues/2112#issue-800986639 are tested and working fine.

Please find list of all issues here with status : https://docs.google.com/spreadsheets/d/1YQQ3UwUTzh1A12j2ubHpvPWOJ6O4-kNK4Fgv7C9Kx8A/edit#gid=0

All issues are resolved now.

**Note :** Here we have one know issue related to view forum redirection. If view forum is associated with two groups then it will redirect to one group. But if that group is private then users will not able to access that group. This issue is also exist on Master branch.

Related issues are resolve now and PR is ready for release.

cc @sourabhmatolia @firozwp @chetansatasiya @KartikSuthar

**Comment by JetalDobariya** [comment]
Hello @asaquzzamanbb 

I did verify this PR in qa-approved branch, Related all the issues has been done and working fine.
Here, I attached few Screenshots.
(1) Do not allow same Forum to be associated with more than 1 Group.
--> https://www.loom.com/i/7ed55a58464e4a11bfd5fcf9bd23b19c

(2) Do not allow to associate sub-forums or any level child forums to any group no matter if parent forum associated with Group or No.
Do not allow to associate Forums Type Category also with the Group.
--> Done

(3) When Forum associated with Group then Forum and all level child Forums "Visibility" Field should be disabled.
--> https://www.loom.com/i/1a4cadd446064913866feebed2911a79

(4) Disable "Forum Parent" and "Type" Field when the main Forum associated with Group.
--> https://www.loom.com/i/6c986f6de0b94b57b9f77eea6df8e52d
--> https://www.loom.com/i/6c210c52098f46f891cdcf8d872f94f1

(5) Group Forum's Sub-Forums will inherit the same privacy as Group.
--> https://www.loom.com/i/1bb8e584334348c6be4b940db17f222b
--> https://www.loom.com/i/a265bfc6580249e3a16c42848c608294
--> https://www.loom.com/i/e6b1cdf7868f4fdc88dda6c0b22650f8

(6) Sub-Forums and all level child forums and discussions always should be linked to Group URL if associated same as Parent Forum from Backend and Frontend.
--> https://www.loom.com/i/8a58c660aa9c4219ab2df0dbee1ea6fa
--> https://www.loom.com/i/508cacabbf9248f6b98f18670c1335fc
--> https://www.loom.com/i/c2894540a8d2405bae4ac63afee4f00d

(7) All change here works fine with Forum settings "Allow social groups " both enabled or disabled.
--> https://www.loom.com/i/2750f34deba24e899b9356aa9ddbfaf1
--> https://www.loom.com/i/df4a0336448049f9bc23c4891c516a2d
--> https://www.loom.com/i/328c432d7ced45e4a0c1dffa56e6bdd3
--> https://www.loom.com/i/eddac51e38d14111ba84fe7c1fb01020

Thanks!
CC : @mohit-buddyboss
