### PR TITLE
PROD-735 #2987 - Fix gravity form user registration add-on conflict with user activation email

### LINKED ISSUE #2987: Gravity form user registration add-on conflict with user activation email
**Describe the bug**
When using Gravity form user registration, activation from gravity form is not sending. It seems that filter **add_filter( 'wpmu_signup_user_notification_email', 'bp_email_wpmu_signup_user_notification_email', 999, 5 );** in bp-core/bp-core-wp-emails.php line 1275 is causing a conflict.

**To Reproduce**
1. Override registration with Gravity form user registration.
2. Enable activation on the said form.
3. Test and form and you can't receive any email activation.

**Expected behavior**
Email activation from Gravity form user registration should work with buddyboss platform activated.

**Screenshots**

**Environment**
Which site did you replicate this issue on?
https://dev-kent.flywheelsites.com/

**Support ticket links**
https://secure.helpscout.net/conversation/1617219027/161601/

**Jira issue** : [PROD-735]

[PROD-735]: https://buddyboss.atlassian.net/browse/PROD-735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by kent-carlo**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2987.

### How to test the changes in this Pull Request:

https://www.loom.com/share/ab393ef783a74e79b2806cd24287970b

### Proof Screenshots or Video

https://www.loom.com/share/ab393ef783a74e79b2806cd24287970b

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fixed gravity form user registration add-on conflict with user activation email

### CODE REVIEW

File: src/bp-core/compatibility/bp-incompatible-plugins-helper.php [hunk 1]
```diff
@@ -1020,3 +1020,17 @@ function bbp_remove_page_attributes_metabox_for_forum() {
 }
 
 add_action( 'admin_menu' , 'bbp_remove_page_attributes_metabox_for_forum' );
+
+/**
+ * Helper functions for the gravity forms compatibility.
+ * 
+ * @since [BBVERSION]
```
Comment (chetansatasiya) [inline src/bp-core/compatibility/bp-incompatible-plugins-helper.php:1027]:
```suggestion
 * @since BuddyBoss [BBVERSION]
```

**Review by chetansatasiya — CHANGES_REQUESTED** [review]

**Review by dipskakadiya — APPROVED** [review]
