### PR TITLE
Notifications not working when a user comments on a blog post

### LINKED ISSUE #1276: Notifications not working when a user comments on a blog post
**Describe the bug**
When creating a blog post, other users can comment on it. When they comment, you will receive a notification. When you click the notification in the notification bell, this doesn't remove the notification.

**To Reproduce**
1. Allow commenting on blog post
2. Create a blog post
3. Login as another user
4. Try to comment on that post
5. Go back to previous user, you will receive a notification
6. Click on notification, this is not removed when you click it

**Expected behavior**
Like any other notification, when the notification bell is clicked and it is selected, this should be removed

**Screenshots**
https://drive.google.com/open?id=13Ty7wCN7O7puNNmaIaHKgmvBZ70JUYvR

**Support ticket links**
https://secure.helpscout.net/conversation/1116652812/64163?folderId=3701258
https://secure.helpscout.net/conversation/1221035011/82669?folderId=3701258

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1276 

### How to test the changes in this Pull Request:
1. Allow commenting on a blog post
2. Create a blog post
3. Login as another user
4. Try to comment on that post
5. Go back to the previous user, you will receive a notification
6. Click on the notification, this is not removed when you click it

### Proof Screenshots or Video
http://somup.com/cYiUiv6onm

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by chetansatasiya — DISMISSED** [review]
@KartikSuthar Approved.!!

**Comment by chetansatasiya** [comment]
@ankitguptaindia Need to test

File: src/bp-activity/bp-activity-notifications.php [hunk 1]
```diff
@@ -476,3 +476,45 @@ function bp_activity_screen_notification_settings() {
...
+				'is_new' => false,
+			),
+			array(
+				'user_id' => bp_loggedin_user_id(),
+				'id'      => $comment_id,
+			)
+		);
+	}
+}
+add_action( 'template_redirect', 'bp_activity_remove_screen_notifications_single_post' );
```
Comment (mehulkaklotar) [inline src/bp-activity/bp-activity-notifications.php:520]: @KartikSuthar add new line at the end of the file.

**Review by mehulkaklotar — CHANGES_REQUESTED** [review]

File: src/bp-activity/bp-activity-notifications.php (hunk 1 above)
Comment (KartikSuthar) [reply src/bp-activity/bp-activity-notifications.php]: @mehulkaklotar Added.

**Review by mehulkaklotar — APPROVED** [review]
Looks good! @KartikSuthar 

@ankitguptaindia Needs testing!

**Comment by mohit-buddyboss** [comment]
@KartikSuthar 

FIXED> Tested this on the branch `fix/1276` of the platform.
Now , notification related to blog post are getting remove.
Video: https://www.loom.com/share/e4f177927943465da1e0a4c034e98867

@mehulkaklotar

**Review by mohit-buddyboss — DISMISSED** [review]
Related issue is fixed now and PR is ready to merge.

@mehulkaklotar

**Review by chetansatasiya — APPROVED** [review]

File: src/bp-activity/bp-activity-notifications.php [hunk 2]
```diff
@@ -476,3 +476,45 @@ function bp_activity_screen_notification_settings() {
 	<?php
 }
 add_action( 'bp_notification_settings', 'bp_activity_screen_notification_settings', 1 );
+
+/**
+ * Mark notifications as read when a user visits an single post.
+ *
+ * @since BuddyBoss 1.5.2
```
Comment (chetansatasiya) [inline src/bp-activity/bp-activity-notifications.php:483]:
```suggestion
 * @since BuddyBoss 1.5.4
```

File: src/bp-activity/bp-activity-notifications.php [hunk 3]
```diff
@@ -476,3 +476,45 @@ function bp_activity_screen_notification_settings() {
...
+ */
+function bp_activity_remove_screen_notifications_single_post() {
+
+	if (
+		! is_single()
+		|| (
+			( ! isset( $_GET['rid'] ) || empty( $_GET['rid'] ) )
```
Comment (chetansatasiya) [inline src/bp-activity/bp-activity-notifications.php:490]: @KartikSuthar From now onward we need to start using some WordPress best practice.  
LIKe For REQUEST DATA LIKE $_POST, $_GET, and $_REQUEST, We should filter it before use it  
Ref: https://www.w3schools.com/php/func_filter_input.asp

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@KartikSuthar From now onward we need to start using some WordPress best practice.  
LIKe For REQUEST DATA LIKE $_POST, $_GET, and $_REQUEST, We should filter it before use it  
Ref: https://www.w3schools.com/php/func_filter_input.asp

File: src/bp-activity/bp-activity-notifications.php (hunk 3 above)
Comment (KartikSuthar) [reply src/bp-activity/bp-activity-notifications.php]: Thanks, @chetansatasiya, I will follow always in the future.

**Review by chetansatasiya — APPROVED** [review]

**Review by mehulkaklotar — APPROVED** [review]
approved! 🚀
