### PR TITLE
Fixed-Forums total topic count is not consistent

### LINKED ISSUE #2473: Forums total topic count is not consistent
**Describe the bug**
Forums Topic count is not consistent for forums with spams topics

**To Reproduce**
1. Go to Forums with spams topics
2. Match the total topics count on platform: sites, app

**Expected behavior**
Total topic count should match across all platform

**Screenshots**
https://prntscr.com/14v34tf
http://prntscr.com/14uyh4z
http://prntscr.com/14uyl87

### PR DESCRIPTION
**Pull request by meetmakadiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2473 .

### How to test the changes in this Pull Request:

1. Go to the BuddyBoss > Forums > Discussions
2. Select any Discussions and set them as a Type: Super Sticky
3. switch the theme to Twenty-Twenty.
4. go to the forums listing page and check the count of discussions.

### Proof Screenshots or Video

https://www.loom.com/share/2622ee6e20144d2c92876062f85b03d5

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by KartikSuthar — CHANGES_REQUESTED** [review]
@meetmakadiya We have an issue with the spam topic count, not for the super sticky.
Super sticky works fine.

**Review by KartikSuthar — APPROVED** [review]

**Comment by sumitbuddyboss** [comment]
Hello @krunal-buddyboss 

**Fixed >**
A related issue is resolved now the forum total is accurate, I have checked with a forum with group and without the group with the sticky forum and without the sticky and it's working fine, for the proof please check the below video.

**Video.**
https://www.loom.com/share/3d5fc26ef94d40598cf3f95ab9cf8779

cc @KartikSuthar 

Thank you.

File: src/bp-forums/forums/functions.php [hunk 1]
```diff
@@ -2036,7 +2036,7 @@ function bbp_pre_get_posts_normalize_forum_visibility( $posts_query = null ) {
  *                        and forum id
  */
 function bbp_forum_query_topic_ids( $forum_id ) {
-	$topic_ids = bbp_get_public_child_ids( $forum_id, bbp_get_topic_post_type() );
+	$topic_ids = bbp_get_public_child_ids( $forum_id, bbp_get_topic_post_type(), true );
```
Comment (dipskakadiya) [inline src/bp-forums/forums/functions.php:2039]: @meetmakadiya If we always passing `$force_cache= true` then I don't think cache will useful. instead of this, we need to find action on which cache should be flush.

**Review by dipskakadiya — CHANGES_REQUESTED** [review]
@meetmakadiya Check my comment.

**Review by dipskakadiya — APPROVED** [review]

File: src/bp-forums/forums/functions.php (hunk 1 above)
Comment (krunal-buddyboss) [reply src/bp-forums/forums/functions.php:2039]: @dipskakadiya 
Yes, that's correct this only executing on Post status update.
Thanks

**Comment by JetalDobariya** [comment]
Hello,

I did verify this PR in qa-approved branch, now Discussions counts are proper in the Forum, discussions tab and Front side.
Forum Backend : https://www.loom.com/i/80685e28d51e4a5b8e4b70be6e5c51db
Discussion Backend : https://www.loom.com/i/a5483b5218b84155961be2b10bea7d25
Front side : https://www.loom.com/i/74d07127af834229a6bd8a7de901896a

Thanks!
Jetal Dobariya
