### PR TITLE
Order for All results tab for members fixed

### LINKED ISSUE #2427: Order for all result for members is not proper
**Describe the bug**
Ordering for search result in `All Results` tab is not proper for `Members` https://prnt.sc/13dxti9

**To Reproduce**
1. Search a name with first name & last name
2. Hit `Enter`
3. See the result at `All Results` & `Members` tabs
4. See the ordering for Searched name.

**Expected behavior**
Searched member should display first at `All Results` tab in `Members` section same as `Members` tab

**Screenshots**
https://prnt.sc/13dxti9

**Video Explainer**
https://www.loom.com/share/6a9aa2b154de4fa2aab759fb3146b831

**Support ticket links**
N/A

**Originally Reported from Client**
https://www.dropbox.com/s/gb8gc1pse8auiav/Screen%20Recording%202021-05-21%20at%202.45.09%20PM.mov?dl=0

### PR DESCRIPTION
**Pull request by ngolwalkar**
### Changes proposed in this Pull Request:

Fixes #2427

### How to test the changes in this Pull Request:

1. Search a name with first name & last name
2. Hit Enter
3. See the result at All Results & Members tabs
4. See the ordering for the Searched name.

### Proof Screenshots or Video

https://www.loom.com/share/0ca93e8d7a4f4143bee4a26e962952a0

### CODE REVIEW

File: src/bp-search/classes/class-bp-search.php [hunk 1]
```diff
@@ -522,7 +522,7 @@ public function do_search( $args = '' ) {
 					return;
 				}
 
-				$pre_search_query = implode( ' UNION ', $sql_queries ) . ' ORDER BY relevance, type DESC, entry_date DESC ';
+				$pre_search_query = implode( ' UNION ', $sql_queries ) . ' ORDER BY relevance DESC, type DESC, entry_date DESC ';
```
Comment (KartikSuthar) [inline src/bp-search/classes/class-bp-search.php:525]: @ngolwalkar This change is not needed. We just need to update the order of the member results on the All results page.
Now you can see the order was changed based on the side menu: http://prntscr.com/1dsla0z

**Review by KartikSuthar — CHANGES_REQUESTED** [review]

File: src/bp-search/classes/class-bp-search.php (hunk 1 above)
Comment (ngolwalkar) [reply src/bp-search/classes/class-bp-search.php:525]: @KartikSuthar Do you think we should fix the search filter instead of the search result? As per the query, we are asking for the most relevant result and when I dump the result it shows the relevance for the member as 1 while relevance for the reply as 0. So the member module has the most relevant result so the sequence seems to be good for the result while the search filter has the wrong sequence. Please let me know your views.

**Review by KartikSuthar — APPROVED** [review]
@ngolwalkar looks good to me. Please merged to dev and pass to QA.

**Comment by sumitbuddyboss** [comment]
Hello @ngolwalkar 

Issue >
If I search with last name and nickname then it will give me different results as compared to the first name, Check below issue video.

**IssueVideo:**
https://www.loom.com/share/b29fa101c4534843bc22a3c76af979e7

Issue > 2
Content flow is different if I search with firstname.
https://www.loom.com/share/c039550926be436bad90aa25a63dfb96

cc @sourabhmatolia 

Thank you

**Comment by sumitbuddyboss** [comment]
Hello @ngolwalkar 

**Issue:**
Member order is not matching in "All Results" and "Member" tabs.

Issue Video:
https://www.loom.com/share/826766504dee411cb06b1e3e37076f24

cc @sourabhmatolia 

Thanks

**Review by KartikSuthar — APPROVED** [review]

**Comment by sumitbuddyboss** [comment]
Hello @ngolwalkar 

Fixed >
A related issue is resolved for the proof to check the below video:

Video proof:
https://www.loom.com/share/c039550926be436bad90aa25a63dfb96

Ready to release 🚀 


Thank you

**Comment by sumitbuddyboss** [comment]
Hello @ngolwalkar 

**Issue**
Member count is getting wrong.

Issue video
https://www.loom.com/share/03eb739f74dc453abd74ddc7f17e9829

**Comment by ngolwalkar** [comment]
> Hello @ngolwalkar
> 
> **Issue**
> Member count is getting wrong.
> 
> Issue video
> 
> https://www.loom.com/share/03eb739f74dc453abd74ddc7f17e9829

@sumitbuddyboss Fixed the conflict with members count. Please check.

**Comment by sumitbuddyboss** [comment]
Hello @ngolwalkar 

Fixed >

I have checked in the dev branch and the related issue is resolved now, the member count is getting properly, for the proof please check the below video.

Video:
https://www.loom.com/share/39887f8c507d406d97598120f88dd3c0

Ready to release 🚀 

Thank you
