### PR TITLE
PROD-827 PROD-931 Profile search is not working properly for Repeater field set dropdown - Fixed.

### LINKED ISSUE #2353: Profile search is not working properly for Repeater field set dropdown field value.
**Describe the bug**
Profile search is not working properly for Repeater field set dropdown field value. Please see my short video in order to replicate the problem: [https://www.loom.com/share/8610c6c62c5443d88d17337190de0d93](https://www.loom.com/share/8610c6c62c5443d88d17337190de0d93)

**Support ticket links**
[https://secure.helpscout.net/conversation/1486658790/137049?folderId=4314898](https://secure.helpscout.net/conversation/1486658790/137049?folderId=4314898)

**Jira issue** : [PROD-827]

[PROD-827]: https://buddyboss.atlassian.net/browse/PROD-827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by mahedihasannoman**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2353 .

### How to test the changes in this Pull Request:

1. Please see this video to reproduce this issue: https://www.loom.com/share/8610c6c62c5443d88d17337190de0d93

### Proof Screenshots or Video

https://www.loom.com/share/633027418e10475584b8df19cb04dfec

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Profile search issue for repeater field set - Fixed

### CODE REVIEW

**Review by dipskakadiya — CHANGES_REQUESTED** [review]

File: src/bp-core/profile-search/bps-xprofile.php [hunk 1]
```diff
@@ -87,7 +87,8 @@ function bp_ps_xprofile_search( $f ) {
 		'where'  => array(),
 	);
 	$sql['select']            = "SELECT user_id FROM {$bp->profile->table_name_data}";
-	$sql['where']['field_id'] = $wpdb->prepare( 'field_id = %d', $f->id );
+
+	$sql['where']['field_id'] = $wpdb->prepare( "field_id IN(SELECT id FROM {$bp->profile->table_name_fields} where 1 and group_id IN(SELECT group_id FROM {$bp->profile->table_name_fields} where 1 and id = %d))", $f->id );
```
Comment (dipskakadiya) [inline src/bp-core/profile-search/bps-xprofile.php:91]: I think `where 1` should be like where 1=1

**Review by dipskakadiya — CHANGES_REQUESTED** [review]

**Review by dipskakadiya — DISMISSED** [review]

**Comment by mckdlrs** [comment]
Retested in the QA ongoing branch
Status: Not yet fixed

Proof Screenshots or Video: https://www.loom.com/share/7a49a268b1ae42fe9ceee9c550a19dfa

**Review by KartikSuthar — DISMISSED** [review]

**Review by KartikSuthar — APPROVED** [review]
