### PR TITLE
PROD-858Fix :  #2129 Fixed private forum 404 issue

### LINKED ISSUE #2129: Forum visibility issue. .
**Describe the bug**
After creating a New forum and setting the visibility to Private, it shows a 404 page for logged out users. . . It should be redirected to the login page. . 

Even if you set the visibility to Public and Select a Private forum as Parent, it will be redirected to 404 for the logged out users. . 

**To Reproduce**

Create a Forum and select the setting like this https://i.imgur.com/vdP3AK8.png and open in an incognito window

Again on that Forum and select the setting like this https://i.imgur.com/11RrgeD.png and open in an incognito window

Same kind of issue from a client: https://www.loom.com/share/21a2dde176e9473dac8cc37151aa8021

**Expected behavior**
It should be redirected to Login page instead of taking to the 404 error page. . 

**Jira issue** : [PROD-858]

[PROD-858]: https://buddyboss.atlassian.net/browse/PROD-858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by ngolwalkar**
https://buddyboss.atlassian.net/browse/PROD-858

### Changes proposed in this Pull Request:

Fixes #2129.

### How to test the changes in this Pull Request:

1. Create a private forum
2. Try to visit this private forum without login to the site.
3. It will redirect you to the login page.

### Proof Screenshots or Video

https://www.loom.com/share/d3ef9b7ae469445f94e02017a891d23d

### CODE REVIEW

File: src/bp-forums/forums/functions.php [hunk 1]
```diff
@@ -2563,3 +2575,28 @@ function bbp_get_forums_per_page( $default = 15 ) {
...
+ * Redirect non-loggedin user to login page while viewing private forum
+ *
+ * @param object $posts array of post objects.
+ * @param object $wp_query WP_Query inatsnace.
+ */
+function bbp_redirect_private_forum( $posts, &$wp_query ) {
+	// remove filter now, so that on subsequent post querying we don't get involved!
+	remove_filter( 'the_posts', 'bbp_redirect_private_forum', 5, 2 );
+
+	$forum_slug = get_query_var( 'forum' );
```
Comment (chetansatasiya) [inline src/bp-forums/forums/functions.php:2589]: @ngolwalkar What happens if someone has another slug instead of the `forum`?

File: src/bp-forums/forums/functions.php [hunk 2]
```diff
@@ -2563,3 +2575,28 @@ function bbp_get_forums_per_page( $default = 15 ) {
 	// Filter and return
 	return (int) apply_filters( 'bbp_get_forums_per_page', $retval, $default );
 }
+
+/**
+ * Redirect non-loggedin user to login page while viewing private forum
+ *
+ * @param object $posts array of post objects.
+ * @param object $wp_query WP_Query inatsnace.
+ */
```
Comment (chetansatasiya) [inline src/bp-forums/forums/functions.php:2584]: where is since tag?

File: src/bp-forums/forums/functions.php [hunk 3]
```diff
@@ -2563,3 +2575,28 @@ function bbp_get_forums_per_page( $default = 15 ) {
...
+function bbp_redirect_private_forum( $posts, &$wp_query ) {
```
Comment (chetansatasiya) [inline src/bp-forums/forums/functions.php:2585]: Newly introduced function should start with `bb_`

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
Need changes

File: src/bp-forums/forums/functions.php (hunk 1 above)
Comment (ngolwalkar) [reply src/bp-forums/forums/functions.php:2591]: It will still work as the query var still be the forum.

File: src/bp-forums/forums/functions.php (hunk 2 above)
Comment (ngolwalkar) [reply src/bp-forums/forums/functions.php]: Added as @since Buddyboss x.x.x

File: src/bp-forums/forums/functions.php (hunk 3 above)
Comment (ngolwalkar) [reply src/bp-forums/forums/functions.php]: Updated the function name.

**Comment by scholary-tim** [comment]
Would be great to see this resolved soon! :)

**Review by KartikSuthar — DISMISSED** [review]
