### PR TITLE
PROD-860#2116 - fix - gif play issue in private message

### LINKED ISSUE #2116: GIFs on private messages won't play
**Describe the bug**
GIFs do not play on private messaging (user to user) and even when you click its "play button". The GIFs will only play when you scroll (up/down) on the outer window on the browser.

**To Reproduce**
Client provided this screen recording showing the issue: https://www.loom.com/share/0f362c68b0a84cc98b63d167cfad74c3
Screen recording showing the issue on the client site (on my end): https://www.loom.com/share/0f2b832424ea49a09336d5e5f54dbcf5
Screen recording showing the issue on our demo (on my end): https://www.loom.com/share/b2e16c7323314b688773cfff5badd620

**Expected behavior**
GIFs should play

**Screenshots**

**Support ticket links**
https://secure.helpscout.net/conversation/1417004533/123690/

**Jira issue** : [PROD-860]

[PROD-860]: https://buddyboss.atlassian.net/browse/PROD-860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by rmmehta**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2116.

### How to test the changes in this Pull Request:

1. Go to private message
2. Add gif on private message
3. Paly the gift via play button on gif

### Proof Screenshots or Video

Client provided this screen recording showing the issue: https://www.loom.com/share/0f362c68b0a84cc98b63d167cfad74c3

Now solved the issue on my dev site please refer this video link:  https://loom.com/share/2a5a753abd1c492d8f3dacd57f5d1e67

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

File: src/bp-templates/bp-nouveau/js/buddypress-media.js [hunk 1]
```diff
@@ -317,8 +317,6 @@ window.bp = window.bp || {};
 			$( '.groups.messages form#send_group_message_form #whats-new-toolbar .bp-group-messages-attached-gif-container .gif-search-results' ).scroll( this.loadMoreGroupMessagesGif.bind( this ) );
 			groupMessagesToolbarContainer.on( 'click', '.gif-image-remove', this.removeGroupMessagesSelectedGif.bind( this ) );
 
-			$( document ).on( 'click', '.gif-image-container', this.playVideo.bind( this ) );
```
Comment (dipskakadiya) [inline src/bp-templates/bp-nouveau/js/buddypress-media.js:320]: @rmmehta This line was added for `gif play pause button fix` so can you verify that is working with removing this line. 
This line added 2 times on the same function so might be it work just confirmation is needed before sending it to QA.

**Review by dipskakadiya — CHANGES_REQUESTED** [review]

**Review by jitendrabanjara1991 — DISMISSED** [review]
