### PR TITLE
Fixed the reporting for Activity content type

### LINKED ISSUE #2729: Report activity based on the content in it
**Describe the bug**
When creating an activity with one photo, document, and video it should have a report button based on the moderation settings. Below are the scenatrios.

**To Reproduce**
1. If there is only one photo then it should show the "Report Activity" on activity listing and open photo, document, and video.
2. If the activity moderation is disabled from the moderation settings it should say "Report photo"
3. If Photo, Document, Video moderation is disabled from the moderation settings it should say "Report Post"
4. If Activity and media relevant settings are disabled from the moderation settings it should not show the report button.

**Expected behavior**
The report button should show based on the moderation settings.

**Environment**
Which site did you replicate this issue on?

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

### PR DESCRIPTION
**Pull request by janakkaneriya007**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2729 .

### How to test the changes in this Pull Request:

Branch Master

- Activity + photo
	- Single photo ==> Report Photo ==> Internally report photo
- Activity
	- Report button is not visible
- Photo
	- Single photo ==> Report Photo ==> Internally report photo
	- Blank Activity is visible in listing

=====================================================================================	

Proposed changes in this PR

- Activity + photo
	- Single photo ==> Report Photo ==> Internally report photo
- Activity
	- Single photo ==> Report button is not visible
	- Reported photo shouls not show in photos tab
- Photo
	- Single photo ==> Report Photo ==> Internally report photo
	- Blank Activity should not visible in listing
	- Report button should show in activity/ Photo popup
- If the particular components is disable then the moderation item can be hide/unhide from the backend
- Above points should be checked with Activity Comments as well

### Proof Screenshots or Video

https://www.loom.com/share/0fe759815eb84940a79f7abacb5ec5eb

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

**BuddyBoss Platform API Github links**
Issue: https://github.com/buddyboss/buddyboss-platform-api/issues/305
PR: https://github.com/buddyboss/buddyboss-platform-api/pull/306

**BuddyBoss App Native Issue**
https://github.com/buddyboss/buddyboss-app-native/issues/1539

### CODE REVIEW

File: src/bp-moderation/classes/class-bp-moderation-activity-comment.php [hunk 1]
```diff
@@ -198,48 +198,66 @@ public function update_button_sub_items( $comment_id ) {
...
+				if ( ! bp_is_moderation_content_reporting_enable( 0, BP_Moderation_Video::$moderation_type ) ) {
+					$sub_items['id']   = false;
+					$sub_items['type'] = false;
 				}
-				$sub_items['id']   = $video_id;
-				$sub_items['type'] = BP_Moderation_Video::$moderation_type;
-				if ( 1 < count( $explode_videos ) ) {
+			} elseif ( bp_is_active( 'video' ) && ! empty( $video_ids ) ) {
+				$explode_videos = explode( ',', $video_ids );
+				if ( 1 === count( $explode_videos ) && ! empty( $explode_videos[0] ) && bp_is_moderation_content_reporting_enable( 0, BP_Moderation_Video::$moderation_type ) ) {
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-activity-comment.php:252]:
```suggestion
				if ( 1 === count( $explode_videos ) && ! empty( current( $explode_videos ) ) && bp_is_moderation_content_reporting_enable( 0, BP_Moderation_Video::$moderation_type ) ) {
```

File: src/bp-moderation/classes/class-bp-moderation-activity-comment.php [hunk 2]
```diff
@@ -198,48 +198,66 @@ public function update_button_sub_items( $comment_id ) {
...
+					$sub_items['id']   = $explode_videos[0];
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-activity-comment.php:253]:
```suggestion
					$sub_items['id']   = current( $explode_videos );
```

File: src/bp-moderation/classes/class-bp-moderation-activity.php [hunk 3]
```diff
@@ -238,48 +238,66 @@ public function update_button_sub_items( $item_id ) {
...
+				if ( ! bp_is_moderation_content_reporting_enable( 0, BP_Moderation_Media::$moderation_type ) ) {
+					$sub_items['id']   = false;
+					$sub_items['type'] = false;
 				}
-				$sub_items['id']   = $media_id;
-				$sub_items['type'] = BP_Moderation_Media::$moderation_type;
-				if ( 1 < count( $explode_medias ) ) {
+			} elseif ( bp_is_active( 'media' ) && ! empty( $media_ids ) ) {
+				$explode_medias = explode( ',', $media_ids );
+				if ( 1 === count( $explode_medias ) && ! empty( $explode_medias[0] ) && bp_is_moderation_content_reporting_enable( 0, BP_Moderation_Media::$moderation_type ) ) {
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-activity.php:248]:
```suggestion
				if ( 1 === count( $explode_medias ) && ! empty( current( $explode_medias ) ) && bp_is_moderation_content_reporting_enable( 0, BP_Moderation_Media::$moderation_type ) ) {
```

File: src/bp-moderation/classes/class-bp-moderation-activity.php [hunk 4]
```diff
@@ -238,48 +238,66 @@ public function update_button_sub_items( $item_id ) {
...
+					$sub_items['id']   = $explode_medias[0];
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-activity.php:249]:
```suggestion
					$sub_items['id']   = current( $explode_medias );
```

File: src/bp-moderation/classes/class-bp-moderation-activity.php [hunk 5]
```diff
@@ -238,48 +238,66 @@ public function update_button_sub_items( $item_id ) {
...
+				if ( ! bp_is_moderation_content_reporting_enable( 0, BP_Moderation_Document::$moderation_type ) ) {
+					$sub_items['id']   = false;
+					$sub_items['type'] = false;
 				}
-				$sub_items['id']   = $document_id;
-				$sub_items['type'] = BP_Moderation_Document::$moderation_type;
-				if ( 1 < count( $explode_documents ) ) {
+			} elseif ( bp_is_active( 'document' ) && ! empty( $document_ids ) ) {
+				$explode_documents = explode( ',', $document_ids );
+				if ( 1 === count( $explode_documents ) && ! empty( $explode_documents[0] ) && bp_is_moderation_content_reporting_enable( 0, BP_Moderation_Document::$moderation_type ) ) {
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-activity.php:270]:
```suggestion
				if ( 1 === count( $explode_documents ) && ! empty( current( $explode_documents ) ) && bp_is_moderation_content_reporting_enable( 0, BP_Moderation_Document::$moderation_type ) ) {
```

File: src/bp-moderation/classes/class-bp-moderation-activity.php [hunk 6]
```diff
@@ -238,48 +238,66 @@ public function update_button_sub_items( $item_id ) {
...
+					$sub_items['id']   = $explode_documents[0];
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-activity.php:271]:
```suggestion
					$sub_items['id']   = current( $explode_documents );
```

File: src/bp-moderation/classes/class-bp-moderation-activity.php [hunk 7]
```diff
@@ -238,48 +238,66 @@ public function update_button_sub_items( $item_id ) {
...
+				if ( ! bp_is_moderation_content_reporting_enable( 0, BP_Moderation_Video::$moderation_type ) ) {
+					$sub_items['id']   = false;
+					$sub_items['type'] = false;
 				}
-				$sub_items['id']   = $video_id;
-				$sub_items['type'] = BP_Moderation_Video::$moderation_type;
-				if ( 1 < count( $explode_videos ) ) {
+			} elseif ( bp_is_active( 'video' ) && ! empty( $video_ids ) ) {
+				$explode_videos = explode( ',', $video_ids );
+				if ( 1 === count( $explode_videos ) && ! empty( $explode_videos[0] ) && bp_is_moderation_content_reporting_enable( 0, BP_Moderation_Video::$moderation_type ) ) {
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-activity.php:292]:
```suggestion
				if ( 1 === count( $explode_videos ) && ! empty( current( $explode_videos ) ) && bp_is_moderation_content_reporting_enable( 0, BP_Moderation_Video::$moderation_type ) ) {
```

File: src/bp-moderation/classes/class-bp-moderation-activity.php [hunk 8]
```diff
@@ -238,48 +238,66 @@ public function update_button_sub_items( $item_id ) {
...
+					$sub_items['id']   = $explode_videos[0];
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-activity.php:293]:
```suggestion
					$sub_items['id']   = current( $explode_videos );
```

File: src/bp-moderation/classes/class-bp-moderation-document.php [hunk 9]
```diff
@@ -180,4 +190,33 @@ public function report_button_text( $button_text, $item_id ) {
...
 	}
+
+	/**
+	 * Function to update activity report button arguments.
+	 *
+	 * @param array $report_button Activity report button
+	 * @param array $args          Arguments
+	 *
+	 * @return array|string
+	 */
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-document.php:201]:
```suggestion

	/**
	 * Function to update activity report button arguments.
	 * @since BuddyBoss 1.7.6
	 *
	 * @param array $report_button Activity report button.
	 * @param array $args          Arguments.
	 *
	 * @return array|string
	 */
```

File: src/bp-moderation/classes/class-bp-moderation-document.php [hunk 10]
```diff
@@ -180,4 +190,33 @@ public function report_button_text( $button_text, $item_id ) {
...
+		$document_id  = bp_activity_get_meta( $args['button_attr']['data-bp-content-id'], 'bp_document_id', true );
+		$document_ids = bp_activity_get_meta( $args['button_attr']['data-bp-content-id'], 'bp_document_ids', true );
+
+		if ( ( ! empty( $document_id ) || ! empty( $document_ids ) ) ) {
+			$explode_documents = explode( ',', $document_ids );
+			if ( ! empty( $document_id ) ) {
+				$args['button_attr']['data-bp-content-id']   = $document_id;
+				$args['button_attr']['data-bp-content-type'] = self::$moderation_type;
+			}
+			if ( 1 === count( $explode_documents ) && ! empty( $explode_documents[0] ) ) {
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-document.php:213]:
```suggestion
			if ( 1 === count( $explode_documents ) && ! empty( current( $explode_documents ) ) ) {
```

File: src/bp-moderation/classes/class-bp-moderation-document.php [hunk 11]
```diff
@@ -180,4 +190,33 @@ public function report_button_text( $button_text, $item_id ) {
...
+				$args['button_attr']['data-bp-content-id']   = $explode_documents[0];
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-document.php:214]:
```suggestion
				$args['button_attr']['data-bp-content-id']   = current( $explode_documents );
```

File: src/bp-moderation/classes/class-bp-moderation-media.php [hunk 12]
```diff
@@ -180,4 +190,33 @@ public function report_button_text( $button_text, $item_id ) {
...
 	}
+
+	/**
+	 * Function to update activity report button arguments.
+	 *
+	 * @param array $report_button Activity report button
+	 * @param array $args          Arguments
+	 *
+	 * @return array|string
+	 */
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-media.php:201]:
```suggestion
	/**
	 * Function to update activity report button arguments.
	 * 
	 * @since BuddyBoss 1.7.6
	 *
	 * @param array $report_button Activity report button.
	 * @param array $args          Arguments.
	 *
	 * @return array|string
	 */
```

File: src/bp-moderation/classes/class-bp-moderation-media.php [hunk 13]
```diff
@@ -180,4 +190,33 @@ public function report_button_text( $button_text, $item_id ) {
...
+		$media_id  = bp_activity_get_meta( $args['button_attr']['data-bp-content-id'], 'bp_media_id', true );
+		$media_ids = bp_activity_get_meta( $args['button_attr']['data-bp-content-id'], 'bp_media_ids', true );
+
+		if ( ( ! empty( $media_id ) || ! empty( $media_ids ) ) ) {
+			$explode_medias = explode( ',', $media_ids );
+			if ( ! empty( $media_id ) ) {
+				$args['button_attr']['data-bp-content-id']   = $media_id;
+				$args['button_attr']['data-bp-content-type'] = self::$moderation_type;
+			}
+			if ( 1 === count( $explode_medias ) && ! empty( $explode_medias[0] ) ) {
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-media.php:213]:
```suggestion
			if ( 1 === count( $explode_medias ) && ! empty( current( $explode_medias ) ) ) {
```

File: src/bp-moderation/classes/class-bp-moderation-media.php [hunk 14]
```diff
@@ -180,4 +190,33 @@ public function report_button_text( $button_text, $item_id ) {
...
+				$args['button_attr']['data-bp-content-id']   = $explode_medias[0];
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-media.php:214]:
```suggestion
				$args['button_attr']['data-bp-content-id']   = current( $explode_medias );
```

File: src/bp-moderation/classes/class-bp-moderation-video.php [hunk 15]
```diff
@@ -180,4 +190,33 @@ public function report_button_text( $button_text, $item_id ) {
...
 	}
+
+	/**
+	 * Function to update activity report button arguments.
+	 *
+	 * @param array $report_button Activity report button
+	 * @param array $args          Arguments
+	 *
+	 * @return array|string
+	 */
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-video.php:201]:
```suggestion
	/**
	 * Function to update activity report button arguments.
	 *
	 * @since BuddyBoss 1.7.6
	 *
	 * @param array $report_button Activity report button.
	 * @param array $args          Arguments.
	 *
	 * @return array|string
	 */
```

File: src/bp-moderation/classes/class-bp-moderation-video.php [hunk 16]
```diff
@@ -180,4 +190,33 @@ public function report_button_text( $button_text, $item_id ) {
...
+		$video_id  = bp_activity_get_meta( $args['button_attr']['data-bp-content-id'], 'bp_video_id', true );
+		$video_ids = bp_activity_get_meta( $args['button_attr']['data-bp-content-id'], 'bp_video_ids', true );
+
+		if ( ( ! empty( $video_id ) || ! empty( $video_ids ) ) ) {
+			$explode_videos = explode( ',', $video_ids );
+			if ( ! empty( $video_id ) ) {
+				$args['button_attr']['data-bp-content-id']   = $video_id;
+				$args['button_attr']['data-bp-content-type'] = self::$moderation_type;
+			}
+			if ( 1 === count( $explode_videos ) && ! empty( $explode_videos[0] ) ) {
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-video.php:213]:
```suggestion
			if ( 1 === count( $explode_videos ) && ! empty( current( $explode_videos ) ) ) {
```

File: src/bp-moderation/classes/class-bp-moderation-video.php [hunk 17]
```diff
@@ -180,4 +190,33 @@ public function report_button_text( $button_text, $item_id ) {
...
+				$args['button_attr']['data-bp-content-id']   = $explode_videos[0];
```
Comment (KartikSuthar) [inline src/bp-moderation/classes/class-bp-moderation-video.php:214]:
```suggestion
				$args['button_attr']['data-bp-content-id']   = current( $explode_videos );
```

**Review by KartikSuthar — CHANGES_REQUESTED** [review]

**Review by KartikSuthar — DISMISSED** [review]
@janakkaneriya007 Changes look good to me. Please merge in dev and pass to QA.

**Comment by janakkaneriya007** [comment]
@mohit-buddyboss This one is ready for testing

**Review by KartikSuthar — APPROVED** [review]

**Comment by mohit-buddyboss** [comment]
@janakkaneriya007 

Kindly find all the issue related to it in below sheet:
https://docs.google.com/spreadsheets/d/1JPebxlYrbonSihQ2sp4pXkjWrQiU0xr6xRUdCLkyiXU/edit?usp=sharing

cc @sourabhmatolia @KartikSuthar @chetansatasiya @firozwp

**Review by KartikSuthar — APPROVED** [review]

**Review by KartikSuthar — APPROVED** [review]

**Review by KartikSuthar — DISMISSED** [review]

**Comment by mohit-buddyboss** [comment]
@janakkaneriya007 

All reported issues in below sheet are fixed except one issue for which we already have one issue: https://github.com/buddyboss/buddyboss-platform/issues/2208

Issue sheet: https://docs.google.com/spreadsheets/d/1JPebxlYrbonSihQ2sp4pXkjWrQiU0xr6xRUdCLkyiXU/edit#gid=567388300

cc @KartikSuthar @sourabhmatolia @firozwp @chetansatasiya

**Review by KartikSuthar — APPROVED** [review]

**Comment by JetalDobariya** [comment]
Hello @janakkaneriya007 

I did verify this PR in qa-approved branch and verified all those scenarios for the uploading single/multiple photos, videos, Documents with Enabled/Disabled settings from the backend moderation and every scenarios functionalities are working fine.

Thanks!
