### PR TITLE
PROD-771 Activity page doesn't protected by MemberPress- Fixed

### LINKED ISSUE #2755: MemberPress > Activity page and Widget doesn't protected
**Describe the bug**
Create Memberships and rules using the Memberpress plugin.
Set protected the activity page with membership. When we go to the activity page we can see all activities and widget as well.

**To Reproduce**

Set Membership & rules in the MemberPress plugin:
1. Go to MemberPress > Memberships
2. Click on "Add New" and create a new membership
3. Go to MemberPress > Rules
4. Click on "Add New" and create a rule
5. Set Activity page in the Protected Content section and assign membership to this rule

Set widget
1. Go to Appearance > Widget
2. Add "(BB) Latest Activities" widget to the activity page

Results
1. Go to the Activity page
2. Can see the activities and widget without login

**Expected behavior**
Activities and widgets should not appear without subscription/login if the activity page is set to protected.

**Screenshots**
https://vimeo.com/584862862/ed513ca7bd

**Environment**
Which site did you replicate this issue on?
My dev site: https://dev-milan.flywheelsites.com
The customer's site: https://testacademy.liferevival.com/

BuddyBoss Platform(Version 1.7.5)
BuddyBoss Platform Pro(Version 1.1.4)
MemberPress(Version 1.9.19)
MemberPress + BuddyPress Integration(Version 1.1.10)

**Support ticket links**
https://secure.helpscout.net/conversation/1564860794/151869/

**Jira issue** : [PROD-771]

[PROD-771]: https://buddyboss.atlassian.net/browse/PROD-771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by mahedihasannoman**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2755  .

### How to test the changes in this Pull Request:

1. Go to MemberPress > Memberships
2. Click on "Add New" and create a new membership
3. Go to MemberPress > Rules
4. Click on "Add New" and create a rule
5. Set Activity page in the Protected Content section and assign membership to this rule
6. See activity page is protected now.

### Proof Screenshots or Video

https://www.loom.com/share/990660449d9c4517b0d2657b3ab1d4d2

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by dipskakadiya — APPROVED** [review]

**Review by dipskakadiya — DISMISSED** [review]

File: src/bp-core/compatibility/bp-incompatible-plugins-helper.php [hunk 1]
```diff
@@ -266,6 +266,22 @@ function_exists( 'seopress_redirections_enabled' ) &&
...
+/**
+ * Allow activity page content restriction via MemberPress
+ * 
+ * @since BuddyBoss [BBVERSION]
+ *
+ * @return void
+ */
+function bb_core_allow_activity_page_content_restriction_memberpress() {
+
+	if ( bp_is_active( 'activity' ) && bp_is_activity_component() ) {
```
Comment (KartikSuthar) [inline src/bp-core/compatibility/bp-incompatible-plugins-helper.php:278]:
```suggestion
	if ( bp_is_active( 'activity' ) && bp_is_activity_component() && function_exists('is_bbpress') && is_bbpress() ) {
```

**Review by KartikSuthar — CHANGES_REQUESTED** [review]

**Review by KartikSuthar — APPROVED** [review]
