### PR TITLE
PROD-649 "is one of" search mode issue for gender field in profile search - Fixed

### LINKED ISSUE #3267: "is one of" search mode is not working for gender field in profile search
**Describe the bug**
When using "Gender" field for Profile Search, the "is one of" search mode is not working. See this video: http://somup.com/crlvjEZVd7

**To Reproduce**
1. enable Profile Search
2. create a Gender field in your Profile Fields
3. Create a Profile Search based on Gender and select "is one of" search mode
4. Try to search in directory and see error

**Expected behavior**
"is one of" search mode should work for Gender field

**Environment**
Demo, Localhost, Client's site

**Support ticket links**
https://support.buddyboss.com/a/tickets/150855

**Jira issue** : [PROD-649]

[PROD-649]: https://buddyboss.atlassian.net/browse/PROD-649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by mahedihasannoman**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #3267  .

### How to test the changes in this Pull Request:

1. enable Profile Search
2. create a Gender field in your Profile Fields
3. Create a Profile Search based on Gender and select "is one of" search mode
4. Try to search in directory and see it works

### Proof Screenshots or Video

https://share.vidyard.com/watch/FvJ33j4EewTtLnMHaP7eAJ?

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

File: src/bp-core/profile-search/bps-xprofile.php [hunk 1]
```diff
@@ -460,7 +460,12 @@ function bp_ps_xprofile_gender_users_search( $f ) {
 
 		$exists_gender = $wpdb->get_results( "SELECT COUNT(*) as count, id FROM {$table_profile_fields} a WHERE parent_id = 0 AND type = 'gender' " );
 
-		$custom_ids = $wpdb->get_col( "SELECT user_id FROM {$table_profile_data} WHERE field_id = {$exists_gender[0]->id} AND value = '{$gender}'" );
+		$where = " AND value = '{$gender}'";
+		if ( is_array( $gender ) ) {
+			$gender = "'" . implode( "', '", $gender ) . "'";
+			$where = " AND value IN({$gender})";
+		}
+		$custom_ids = $wpdb->get_col( "SELECT user_id FROM {$table_profile_data} WHERE field_id = {$exists_gender[0]->id} {$where}" );
```
Comment (KartikSuthar) [inline src/bp-core/profile-search/bps-xprofile.php:468]: @mahedihasannoman Please make it condtional that `$exists_gender` is not empty otherwise `$exists_gender[0]->id` gives fatal.

```suggestion
		if ( ! empty( $exists_gender ) ) {
			$where = " AND value = '{$gender}'";
			if ( is_array( $gender ) ) {
				$gender = "'" . implode( "', '", $gender ) . "'";
				$where  = " AND value IN({$gender})";
			}
			$custom_ids = $wpdb->get_col( "SELECT DISTINCT user_id FROM {$table_profile_data} WHERE field_id = {$exists_gender[0]->id} {$where}" );

			if ( ! empty( $custom_ids ) ) {
				return $custom_ids;
			} else {
				return array();
			}
		} 
```

Comment (mahedihasannoman) [reply src/bp-core/profile-search/bps-xprofile.php]: Done

File: src/bp-core/profile-search/bps-xprofile.php [hunk 2]
```diff
@@ -459,17 +459,22 @@ function bp_ps_xprofile_gender_users_search( $f ) {
...
 		$exists_gender = $wpdb->get_results( "SELECT COUNT(*) as count, id FROM {$table_profile_fields} a WHERE parent_id = 0 AND type = 'gender' " );
-
-		$custom_ids = $wpdb->get_col( "SELECT user_id FROM {$table_profile_data} WHERE field_id = {$exists_gender[0]->id} AND value = '{$gender}'" );
-
-		if ( isset( $custom_ids ) && ! empty( $custom_ids ) ) {
-			return $custom_ids;
-		} else {
-			return array();
+		if ( ! empty( $exists_gender ) ) {
+			$where = " AND value = '{$gender}'";
```
Comment (dipskakadiya) [inline src/bp-core/profile-search/bps-xprofile.php:463]: @mahedihasannoman What if `$gender` is ARRAY. I think the condition should be in else section.

**Review by dipskakadiya — CHANGES_REQUESTED** [review]

File: src/bp-core/profile-search/bps-xprofile.php (hunk 2 above)
Comment (mahedihasannoman) [reply src/bp-core/profile-search/bps-xprofile.php]: Yes it could be ARRAY so added else condition there.

**Review by dipskakadiya — APPROVED** [review]
@mahedihasannoman Please merge this in dev for QA

**Comment by mahedihasannoman** [comment]
Hi @dipskakadiya , It is already merged into dev. Should I merge in qa-ongoing?

**Comment by mahedihasannoman** [comment]
It is merged in qa-ongoing.
