### PR TITLE
Fixed the user nickmane already exist issue

### LINKED ISSUE #2123: Buddyboss platform does allow duplicate nickname when I edit a user through WP user edit page.
**Describe the bug**
Buddyboss platform does allow duplicate nickname when I edit a user through WP user edit page but it should not allow duplicate nickname since it brakes @mention &  messages.

**To Reproduce**
1. Edit a user through WP user edit page and it will allow you to add duplicate nickname.

**Expected behavior**
It should not allow duplicate nickname from WP user edit page

### PR DESCRIPTION
**Pull request by janakkaneriya007**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2123 .

### How to test the changes in this Pull Request:

1. Add or Edit a user through the WP user edit page and it will not allow you to add a duplicate nickname.

### Proof Screenshots or Video

https://www.loom.com/share/537f7606b1384be68c95c1d051313384

https://prnt.sc/13dxuns
https://prnt.sc/13dxxjn

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
Needs to do changes as requested.

File: src/bp-core/admin/bp-core-admin-actions.php [hunk 1]
```diff
@@ -65,6 +65,9 @@
 // Add a new separator.
 add_action( 'bp_admin_menu', 'bp_admin_separator' );
 
+// Check user nickname on backend user edit page.
+add_action( 'user_profile_update_errors', 'bp_check_user_nickname', 10, 3 );
```
Comment (chetansatasiya) [inline src/bp-core/admin/bp-core-admin-actions.php:69]:
```suggestion
add_action( 'user_profile_update_errors', 'bb_check_user_nickname', 10, 3 );
```

**Review by chetansatasiya — APPROVED** [review]

**Comment by mohit-buddyboss** [comment]
@janakkaneriya007 

FIXED>Tested this on dev branch of the platform.
Now admin user is not allowed to use duplicate "Nickname" while editing user details through back end also validation message appears in back end.
Also, tried to enter already exist username through front end and user is not allowed to enter duplicate nickname and validation message is appearing. 
Also, tested same scenario while adding new user. 
Video:> https://www.loom.com/share/2524b9e075684beea34b1007dd91d813

Related issue is resolve now and PR is ready to merge in release.

cc @sourabhmatolia @chetansatasiya
