### PR TITLE
1251 - Fixed the issue with notification mark read when visiting the …

### LINKED ISSUE #1251: Custom post type notifications not being marked read when clicked
**Describe the bug**
The following custom post type notifications are not being marked read when clicked:
- When someone commented on the activity feed of the CPT
- When someone mentioned you on the activity feed of the CPT

**To Reproduce**
1. Create a custom post type
2. Make sure to enable it on BuddyBoss > Settings > Activity > Custom Post Types
3. Add new item for the CPT you just created
4. Go to the activity feed, try to mention someone or comment using another account
5. Using the mentioned account, notice that the notification is not being marked as read after viewing it. For reference, please see, https://i.ibb.co/JsxCRtd/mentioned.png
6. Lastly, go to the creator's account and notice the the notification when some commented on your CPT activity will not marked as read too, for reference, please see https://i.ibb.co/fx7fszy/commented.png.

**Screencasts**
https://cutt.ly/Oso8HQZ
https://cutt.ly/gso8B1Z

**Support ticket links**
https://secure.helpscout.net/conversation/1231361754/84303

**Jira issue** : [PROD-933]

[PROD-933]: https://buddyboss.atlassian.net/browse/PROD-933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by janakkaneriya007**
…notification ilnk

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1251.

### How to test the changes in this Pull Request:

1. Create a custom post type
2. Make sure to enable it on BuddyBoss > Settings > Activity > Custom Post Types
3. Add new item for the CPT you just created
4. Go to the activity feed, try to mention someone or comment using another account
5. Using the mentioned account, notice that the notification is not being marked as read after viewing it. For reference, please see, https://i.ibb.co/JsxCRtd/mentioned.png
6. Lastly, go to the creator's account and notice the the notification when some commented on your CPT activity will not marked as read too, for reference, please see https://i.ibb.co/fx7fszy/commented.png.

### Proof Screenshots or Video
https://www.loom.com/share/ffe257d80a8c41378114f2f3cf090a4a

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

File: src/bp-activity/bp-activity-notifications.php [hunk 1]
```diff
@@ -293,6 +293,42 @@ function bp_activity_remove_screen_notifications_single_activity_permalink( $act
...
+function bp_activity_remove_screen_notifications_sing_post() {
+	global $post;
+
+	if ( ! is_user_logged_in() || empty( $post->post_type ) || ! bp_is_post_type_feed_enable( $post->post_type ) || ! is_singular( $post->post_type ) ) {
+		return;
+	}
+
+	$comment_id = 0;
+	// For replies to a parent update.
+	if ( ! empty( $_GET['rid'] ) ) {
```
Comment (dipskakadiya) [inline src/bp-activity/bp-activity-notifications.php:310]: @janakkaneriya007 Use `Input_filter` before use $_Request, $_GET or $_POST data

File: src/bp-activity/bp-activity-notifications.php [hunk 2]
```diff
@@ -293,6 +293,42 @@ function bp_activity_remove_screen_notifications_single_activity_permalink( $act
 }
 add_action( 'bp_activity_screen_single_activity_permalink', 'bp_activity_remove_screen_notifications_single_activity_permalink' );
 
+/**
+ * Mark notification read when user visit sing post page permalink
+ *
+ * @since BuddyPress 2.0.0
+ */
+function bp_activity_remove_screen_notifications_sing_post() {
```
Comment (dipskakadiya) [inline src/bp-activity/bp-activity-notifications.php:301]: @janakkaneriya007 Function name should be `bp_activity_mark_blog_post_notification_read`

**Review by dipskakadiya — CHANGES_REQUESTED** [review]
@janakkaneriya007 Thanks for PR. Requested some change.

**Review by dipskakadiya — APPROVED** [review]
@janakkaneriya007 Approved. @ankitguptaindia Ready for testing. PR merged in dev.
