### PR TITLE
#2690 - quick reply ajax

### LINKED ISSUE #2690: News feed page quick reply popup does not display media upload buttons when access control enabled
**Describe the bug**
When users don't have access to upload media/document/video, then quick reply of a group forum does not show these icons in news feed page. However, it should display because media access is not applicable for group related stuff

**To Reproduce**
1. Go to buddyboss > settings > media access
2. Set media access for target user
3. Login to a user who does not have access to upload media, documents and videos
4. Created a discussion from a group forum
5. Go to news feed page and find that post
6. click on quick reply and you will not see media upload buttons

**Expected behavior**
User should get media upload buttons for quick reply as media access does not applicable for group forums

**Screenshots**
https://www.loom.com/share/7202aee1000b4f1b85f9b354e7369496

**Related BuddyBoss Theme issue**
https://github.com/buddyboss/buddyboss-theme/issues/1581

### PR DESCRIPTION
**Pull request by sadrul**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Implemented ajax to load the popup for the quick reply as we need to pass topic id and group id if the forum is associated with a group

Fixes #2690  .

### How to test the changes in this Pull Request:

1. Go to buddyboss > settings > media access
2. Set media access for target user
3. Login to a user who does not have access to upload media, documents and videos
4. Created a discussion from a group forum
5. Go to news feed page and find that post
6. click on quick reply and test adding post including photos, video & documents

### Proof Screenshots or Video
https://www.loom.com/share/617147c2f53a4d00b36687bb29c0c31a

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Related Theme PR
https://github.com/buddyboss/buddyboss-theme/pull/1584

### CODE REVIEW

File: src/bp-forums/common/template.php [hunk 1]
```diff
@@ -1786,9 +1786,16 @@ function bbp_reply_form_fields() {
...
+		if ( isset ( $_POST['topic_id'] ) && ! empty( $_POST['topic_id'] ) ) {
+			$topic_id = $_POST['topic_id'];
+		}else{
+			$topic_id = bbp_get_topic_id();
+		}
+
 		?>
 
-		<input type="hidden" name="bbp_topic_id"    id="bbp_topic_id"    value="<?php bbp_topic_id(); ?>" />
+		<input type="hidden" name="bbp_topic_id"    id="bbp_topic_id"    value="<?php echo $topic_id; ?>" />
```
Comment (chetansatasiya) [inline src/bp-forums/common/template.php:1798]: Use the escaping function here

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
Need changes

**Comment by sadrul** [comment]
@chetansatasiya done with the change requests

**Comment by chetansatasiya** [comment]
@sadrul This is not working and even not opening the popup

File: src/bp-forums/common/template.php [hunk 2]
```diff
@@ -1786,9 +1786,16 @@ function bbp_reply_form_fields() {
 		wp_nonce_field( 'bbp-edit-reply_' . bbp_get_reply_id() );
 
 	else :
+
+		if ( isset ( $_POST['topic_id'] ) && ! empty( $_POST['topic_id'] ) ) {
+			$topic_id = $_POST['topic_id'];
+		} else {
+			$topic_id = bbp_get_topic_id();
+		}
+
```
Comment (KartikSuthar) [inline src/bp-forums/common/template.php:1795]: @sadrul Remove this change from here.

File: src/bp-forums/common/template.php [hunk 3]
```diff
@@ -1786,9 +1786,16 @@ function bbp_reply_form_fields() {
...
 		?>
 
-		<input type="hidden" name="bbp_topic_id"    id="bbp_topic_id"    value="<?php bbp_topic_id(); ?>" />
+		<input type="hidden" name="bbp_topic_id"    id="bbp_topic_id"    value="<?php echo esc_attr( $topic_id ); ?>" />
```
Comment (KartikSuthar) [inline src/bp-forums/common/template.php:1798]: @sadrul Remove this change from here.

File: src/bp-forums/templates/default/bbpress/form-attachments.php [hunk 4]
```diff
@@ -8,6 +8,14 @@
...
 $group_id = 0;
 $forum_id = 0;
+
+if ( isset ( $_POST['topic_id'] ) && ! empty( $_POST['topic_id'] ) ) {
+	$forum_id = bbp_get_topic_forum_id( $_POST['topic_id'] );
+}
+if ( isset ( $_POST['group_id'] ) && ! empty( $_POST['group_id'] ) ) {
+	$group_id = $_POST['group_id'];
+}
+
```
Comment (KartikSuthar) [inline src/bp-forums/templates/default/bbpress/form-attachments.php:18]: @sadrul Remove this change from here.

**Review by KartikSuthar — CHANGES_REQUESTED** [review]

**Comment by sadrul** [comment]
This PR is not needed as everything is done from theme PR - https://github.com/buddyboss/buddyboss-theme/pull/1584

**Comment by sadrul** [comment]
Reopening this PR as we need this

**Review by chetansatasiya — APPROVED** [review]
LGTM 🚀

**Comment by sadrul** [comment]
@sumitbuddyboss @mohit-buddyboss Merged into dev and ready for testing

**Comment by mohit-buddyboss** [comment]
@sadrul 

Tested using dev branch of the platform and master branch of the platform pro.

Now, users who don't have access to upload media, document or videos are getting option to upload all for group related forum discussion quick reply.
Tested by checking quick reply medium editor option for both individual and group forum related activity. Also, uploaded media ,doc and video through quick reply editor.

Video: https://loom.com/share/445b91db0de34a4e807611acc283864c

Related issue is resolve now and PR is ready for release.

cc @sourabhmatolia @chetansatasiya @KartikSuthar 

Related Theme PR
buddyboss/buddyboss-theme#1584

**Review by KartikSuthar — APPROVED** [review]

**Comment by sourabhmatolia** [comment]
@amincdev @sadrul 

Check the video here talking about the UI issue:
https://www.loom.com/share/618df528dd5a4f7ea79fb0e6ce9dcad2
Screenshot again for ref: https://prnt.sc/1qvnpoi

Please fix. Thanks.

**Comment by amincdev** [comment]
> @amincdev @sadrul
> 
> Check the video here talking about the UI issue:
> 
> https://www.loom.com/share/618df528dd5a4f7ea79fb0e6ce9dcad2
> Screenshot again for ref: https://prnt.sc/1qvnpoi
> 
> Please fix. Thanks.

@sourabhmatolia Changes are made and merged in `QA-approved` branch in theme repo PR: https://github.com/buddyboss/buddyboss-theme/pull/1584.
