### PR TITLE
1004 - Fixed the issue of send empty messages and extra spaces

### LINKED ISSUE #1004: User can send empty messages. Bug with extra spaces
**Describe the bug**
User can send empty messages. Can send extra spaces. 

**To Reproduce**
1. Go to messages and try to sent a messages to some user
2. Press a space button (one or several times) and send the message
3. Try to send `"       test             test        "` message (with using a lot of spaces, GitHub don't allow to do it here)
4. See the result
5. Also user can send empty activity feed post
image

**Expected behavior**
- Empty messages should not be sent
- Extra spaces should be removed (something like [trim()](https://www.php.net/manual/en/function.trim.php) function in PHP)

**Screenshots / GIF**
bb-spaces

---

## Another similar problem with extra spaces:
**To Reproduce**
1. Go to messages and try to sent a messages to some user
2. Try to send some link ("https://google.com " for example) with some spaces in the end

3. You will see extra `&nbsp;` symbol in the end of the link
image

4. With this symbol link is not working
image

**Expected behavior**
Link should not have `&nbsp;` symbol in the end. 

**GIF:**
bb-link-bug

**Solution:** 
- I think you can use [trim()](https://www.php.net/manual/en/function.trim.php) function before sending a message.
- If the message will be empty - do not send the message.
- link should not have any extra symbols in the end. 

**Notice:** 
All this bugs should be tested in activity feed too. Because user also can publish empty post in activity feed
bb-activity-posts

**Configuration:** 
- buddyboss-platform 1.4.1
- buddyboss-theme 1.5.0
- WordPress  5.4.1

### PR DESCRIPTION
**Pull request by buddy4kp**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1004 

https://github.com/buddyboss/buddyboss-theme/pull/860

### How to test the changes in this Pull Request:

1. Go to messages and try to sent a message to some user
2. Press a space button (one or several times) and send the message
3. Try to send a " test test " message (with using a lot of spaces, GitHub don't allow to do it here)
Also, Fix another issue as below
Steps to reproduce the behaviour:
1. Go to messages and try to sent a message to some user
2. Try to send some link ("https://google.com " for example) with some spaces in the end
3. You will see extra &nbsp; symbol at the end of the link

### Proof Screenshots or Video

https://www.loom.com/share/d57c98517c5c449c901e7d3a90228a69

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

File: src/bp-templates/bp-nouveau/js/buddypress-messages.js [hunk 1]
```diff
@@ -2702,6 +2702,7 @@ window.bp = window.bp || {};
 						}
 					);
 					content = bp.Nouveau.Messages.mediumEditor.getContent();
+					content = content.replace(/&nbsp;/g,'').trim();
```
Comment (mehulkaklotar) [inline src/bp-templates/bp-nouveau/js/buddypress-messages.js:2705]: @buddy4kp 
`content` variable is from 2 either cases. 1 is from tinyMCE condition above and other is here from mediumEditor You will need to put this outside conditions.

File: src/bp-templates/bp-nouveau/js/buddypress-messages.js [hunk 2]
```diff
@@ -2710,6 +2711,10 @@ window.bp = window.bp || {};
 					errors.push( 'message_content' );
 				}
 
+				if(jQuery(content).text().trim() == "") {
```
Comment (mehulkaklotar) [inline src/bp-templates/bp-nouveau/js/buddypress-messages.js:2714]:
```suggestion
				if($(content).text().trim() === '') {
```

File: src/bp-templates/bp-nouveau/js/buddypress-messages.js (hunk 1 above)
Comment (buddy4kp) [reply src/bp-templates/bp-nouveau/js/buddypress-messages.js:2705]: @mehulkaklotar 
I have applied below changes as per suggestion.
 - Put the `content` variable outside the condition to apply in both cases tinyMCE and mediumEditor
 - Applied the same changes in `sendMessage` for New Message form

**Comment by buddy4kp** [comment]
> @buddy4kp
> What about empty posts in activity feed and links in messages?
> Could you show the result?

@AiratHalitov  Yes, I have already fixed for links in messages. Please see below a video of the result.
https://www.loom.com/share/dfc4a222948440fea8368842fde02bd3
And for the empty posts in the activity feed, I have applied changes in my last commit. Please see the result of it in below video.
https://www.loom.com/share/40ffc9e052374f33ba33b1963ea6f20f

**Comment by AiratHalitov** [comment]
@buddy4kp
Thanks, looks good.

File: src/bp-templates/bp-nouveau/includes/activity/ajax.php [hunk 3]
```diff
@@ -532,6 +532,14 @@ function bp_nouveau_ajax_post_update() {
...
 	}
 
+	if ( ! strlen( trim( strip_tags($_POST['content'] ) ) ) ) {
+		wp_send_json_error(
+			array(
+				'message' => __( 'Please enter some content to post.', 'buddyboss' ),
+			)
+		);
+	}
+
```
Comment (mehulkaklotar) [inline src/bp-templates/bp-nouveau/includes/activity/ajax.php:542]: @buddy4kp You should have used the validation written below. This code check for content is empty striping tags but it will give errors even if we have content like media, link preview, document etc. we need to allow users to post only media without content. so this condition should always check with them.

File: src/bp-templates/bp-nouveau/js/buddypress-messages.js [hunk 4]
```diff
@@ -1759,6 +1759,11 @@ window.bp = window.bp || {};
 					errors.push( 'message_content' );
 				}
 
+				this.model.set('message_content', this.model.get('message_content').replace(/&nbsp;/g, '').trim(), { silent: true });
+				if ($(this.model.get('message_content')).text().trim() === '') {
+					errors.push('message_content');
+				}
+
```
Comment (mehulkaklotar) [inline src/bp-templates/bp-nouveau/js/buddypress-messages.js:1766]: @buddy4kp Here too, we have one validation code few lines below this to check for other toolbar options like media, document etc. if they are added then content should be allowed empty.

File: src/bp-templates/bp-nouveau/js/buddypress-messages.js [hunk 5]
```diff
@@ -2710,6 +2715,11 @@ window.bp = window.bp || {};
 					errors.push( 'message_content' );
 				}
 
+				content = content.replace(/&nbsp;/g,'').trim();
+				if($(content).text().trim() === '') {
+					errors.push( 'message_content' );
+				}
+
```
Comment (mehulkaklotar) [inline src/bp-templates/bp-nouveau/js/buddypress-messages.js:2722]: @buddy4kp here too, this condition should not check if condition written above is met. Please apply proper logic here.

**Comment by buddy4kp** [comment]
@mehulkaklotar 
I have applied changes as you have suggested and also we have discussed also tested locally it looks good for me now. Thanks.

**Comment by mohit-buddyboss** [comment]
@buddy4kp 
Tested this on the Branch `fix/1004`. Tested related issues on all pages where we are using the medium editor and also fond few issues.

**Issue 1:** Messages  - For messages, this PR fixes nothing and all issues are appearing here.  Kindly see this video:https://www.loom.com/share/90a357bfcc7a4da08fe56ecca282046b

**Issue 2:** Forum Discussions _ Only spaces are allowed if the user enters only spaces in Discussion content as well as in Replies.  Kindly see this video; https://www.loom.com/share/15ac3fd096804afa9178e7a8af71718b

**Issue 3** : (Activity page, Group feed, User Profile Feed) - Validation message is not properly appearing on all these pages. To understand issue kindly see this video : https://www.loom.com/share/b4dfa4bba3234de4a290e572e9de41e9

**Suggestion:-** If user enters only spaces then we must handle it on the front end without any ajax call. We can provide client-side validation for this.

cc @chetansatasiya  @mehulkaklotar

**Comment by mehulkaklotar** [comment]
> @buddy4kp
> Tested this on the Branch `fix/1004`. Tested related issues on all pages where we are using the medium editor and also fond few issues.
> 
> **Issue 1:** Messages - For messages, this PR fixes nothing and all issues are appearing here. Kindly see this video:https://www.loom.com/share/90a357bfcc7a4da08fe56ecca282046b
> 
> **Issue 2:** Forum Discussions _ Only spaces are allowed if the user enters only spaces in Discussion content as well as in Replies. Kindly see this video; https://www.loom.com/share/15ac3fd096804afa9178e7a8af71718b
> 
> **Issue 3** : (Activity page, Group feed, User Profile Feed) - Validation message is not properly appearing on all these pages. To understand issue kindly see this video : https://www.loom.com/share/b4dfa4bba3234de4a290e572e9de41e9
> 
> **Suggestion:-** If user enters only spaces then we must handle it on the front end without any ajax call. We can provide client-side validation for this.
> 
> cc @chetansatasiya @mehulkaklotar

@mohit-buddyboss 
Issue 1: Grunt wasn't run on this PR properly so min files weren't generated. so it was failing for you.
Issue 2: fixed now also theme PR https://github.com/buddyboss/buddyboss-theme/pull/860
Issue 3: fixed now

**Comment by mohit-buddyboss** [comment]
@mehulkaklotar 
Tested this using platform branch `fix/1004` and theme branch `fix/topic-reply-ajax-validation` . 

Old issues are resolved now but notice another issue.
**Issue:** For old thread sending messages functionality working fine with all implemented validations but if user tries to add start a new thread then messages are not getting send and the user is getting same validation error again and again that " Please enter some content." even though I've entered content. Please see this video: https://www.loom.com/share/8bfaa660f88d42e1952cf4c6a794e941

**Comment by mehulkaklotar** [comment]
> @mehulkaklotar
> Tested this using platform branch `fix/1004` and theme branch `fix/topic-reply-ajax-validation` .
> 
> Old issues are resolved now but notice another issue.
> **Issue:** For old thread sending messages functionality working fine with all implemented validations but if user tries to add start a new thread then messages are not getting send and the user is getting same validation error again and again that " Please enter some content." even though I've entered content. Please see this video: https://www.loom.com/share/8bfaa660f88d42e1952cf4c6a794e941

@mohit-buddyboss fixed now.

**Comment by mohit-buddyboss** [comment]
@mehulkaklotar 
FIXED. Tested this on the branch `fix/1004`. Issue with new thread of message is resolved now. For proof kindly see this video
https://www.loom.com/share/3e296ce1832f4025a1b4377bea105f26
