### PR TITLE
Wrong avatar on the new activity post form #1048

### LINKED ISSUE #1048: Wrong avatar on the new activity post form
**Describe the bug**
Wrong avatar on the new activity post form when using the auto-generated default avatar

**To Reproduce**
1. Go to Settings > Discussion > Avatara.
2. Set it to any generated Avatar
3. Go to the news feed and notice that the avatar in the new activity post form is displaying a wrong image.

**Screenshots**
settings
wrong-avatar

**Support ticket links**
https://secure.helpscout.net/conversation/1191601586/77330/

### PR DESCRIPTION
**Pull request by shohelbuddyboss**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1048 .

### How to test the changes in this Pull Request:

1. Checked core function, identified from where the issue comes, found in `wp-content/plugins/buddyboss-platform/src/bp-templates/bp-nouveau/buddypress/common/js-templates/activity/parts/bp-activity-post-form-avatar.php`
2. The issue was & to  &#038; issue and gravatar returned the wrong avatar for this issue. 
3.

### Proof Screenshots or Video

Fix 1040

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

Fixed: wrong avatar on the new activity post form #1048

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

File: src/bp-templates/bp-nouveau/buddypress/common/js-templates/activity/parts/bp-activity-post-form-avatar.php [hunk 1]
```diff
@@ -1,7 +1,7 @@
 <script type="text/html" id="tmpl-activity-post-form-avatar">
-	<# if ( data.display_avatar ) { #>
+	<# if ( data.display_avatar ) {  #>
 	<a class="activity-post-avatar" href="{{data.user_domain}}">
-		<img src="{{data.avatar_url}}" class="avatar user-{{data.user_id}}-avatar avatar-{{data.avatar_width}} photo" width="{{data.avatar_width}}" height="{{data.avatar_width}}" alt="{{data.avatar_alt}}" />
+		<img src="{{data.avatar_url.split("#038;").join("")}}" class="avatar user-{{data.user_id}}-avatar avatar-{{data.avatar_width}} photo" width="{{data.avatar_width}}" height="{{data.avatar_width}}" alt="{{data.avatar_alt}}" />
```
Comment (chetansatasiya) [inline src/bp-templates/bp-nouveau/buddypress/common/js-templates/activity/parts/bp-activity-post-form-avatar.php:4]:
```suggestion
		<img src="{{{data.avatar_url}}}" class="avatar user-{{data.user_id}}-avatar avatar-{{data.avatar_width}} photo" width="{{data.avatar_width}}" height="{{data.avatar_width}}" alt="{{data.avatar_alt}}" />
		
		
```

@shohel I don't think we need to split here anything just use the `{{{` insted of `{{` and let me know this will fix the issue or not.

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@shohelbuddyboss See my above suggestion and let me know.

File: src/bp-templates/bp-nouveau/buddypress/common/js-templates/activity/parts/bp-activity-post-form-avatar.php (hunk 1 above)
Comment (shohel) [reply src/bp-templates/bp-nouveau/buddypress/common/js-templates/activity/parts/bp-activity-post-form-avatar.php]: @chetansatasiya  It's working, made changes

**Review by chetansatasiya — APPROVED** [review]

**Review by mehulkaklotar — APPROVED** [review]
@chetansatasiya @shohel `fix-1048` was not merged to `dev`. I merged it.

Approved 🚀
