### PR TITLE
#2100 - Fixed the issue that Hidden Groups Appear in User Profiles

### LINKED ISSUE #2100: Hidden Groups Appear in User Profiles
**Describe the bug**
Hidden groups are visible to other member https://prnt.sc/x8ff6v
If you go to a profile, click groups you do see the groups that are hidden. If you click on a group you are not in that is hidden, you get an error page. https://www.loom.com/share/7945f71d22aa4557a4c5dcaf3e41e341

**Expected behavior**
Hidden group should not be visible to other member.

**Screenshots**
https://www.loom.com/share/9db56894f1c74d86a92bcf63ab62cd7c

**Support ticket links**
https://secure.helpscout.net/conversation/1400540208/120636/

### PR DESCRIPTION
**Pull request by krunal-buddyboss**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2100 , #1196 
### How to test the changes in this Pull Request:

https://www.loom.com/share/9db56894f1c74d86a92bcf63ab62cd7c

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

File: src/bp-groups/bp-groups-template.php [hunk 1]
```diff
@@ -414,6 +414,12 @@ function bp_has_groups( $args = '' ) {
 		$parent_id = 0;
     }
 
+	$show_hidden = true;
+	if( !empty( bp_displayed_user_id() ) && !empty( bp_current_user_id() ) &&
+		bp_displayed_user_id() == bp_current_user_id()
+	) {
+		$show_hidden = false;
+	}
```
Comment (chetansatasiya) [inline src/bp-groups/bp-groups-template.php:422]: @krunal-buddyboss We don't need to make any changes here it will always pass to `true` as per @mehulkaklotar reviewed check the SQL and see here https://github.com/buddyboss/buddyboss-platform/blob/32b924a2998e1d320cda8d679f7e4ef0762f8289/src/bp-groups/classes/class-bp-groups-group.php#L1167 as @dipskakadiya added a comment and then make the change accordingly.

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@krunal-buddyboss We don't need to make any changes here it will always pass to `true` as per @mehulkaklotar reviewed check the SQL and see here https://github.com/buddyboss/buddyboss-platform/blob/32b924a2998e1d320cda8d679f7e4ef0762f8289/src/bp-groups/classes/class-bp-groups-group.php#L1167 as @dipskakadiya added a comment and then make the change accordingly.

File: src/bp-groups/bp-groups-template.php (hunk 1 above)
Comment (krunal-buddyboss) [reply src/bp-groups/bp-groups-template.php:422]: @chetansatasiya 
I have applied this changes after discussed with @dipskakadiya as some scenario was failed to show hidden groups for logged in user on profile page. After apply these changes all scenarios looks good I have also checked and verified. Thanks.
+ @mehulkaklotar

**Review by mehulkaklotar — APPROVED** [review]
@krunal-buddyboss please merge this dev branch and put your comments regarding the changes requested by chetan and answers for them if any.

**Comment by krunal-buddyboss** [comment]
Thanks @mehulkaklotar , already replied to Chetan's comment at above.
Merged to Dev.

@chetansatasiya

**Review by chetansatasiya — APPROVED** [review]

**Comment by chetansatasiya** [comment]
@mohit-buddyboss make sure to test eveywhere we are listing the groups.

**Comment by mohit-buddyboss** [comment]
@krunal-buddyboss 

FIXED>

Tested on dev branch of the platform.
Now the hidden groups are not appearing under User Profile Groups tab if other user visit profile of the Hidden group member.
Also, checked group directory page Hidden groups are appearing only for users who are members of the hidden group.
Also checked Forums discussions listing. Hidden groups discussions listings are appearing only to members of the group.
Issue video on master branch : https://www.loom.com/share/84b4e3ccbac8456abac7ac398780e504
Issue Fix on Dev branch : https://www.loom.com/share/d2006964831f4dff8ec55ca356d1a67f

Related issue is resolve now and PR is ready to merge.

cc @chetansatasiya
