### PR TITLE
PROD-907 - #1594 - Fix reply notification redirects to the main comments instead of the exact reply

### LINKED ISSUE #1594: Reply notification redirects to the main comments instead of the exact reply
**Describe the bug**
When a user replies to a comment in the activity feed, the notification URL that is being created on this does not direct the user to the correct reply. It redirects to the main comments where the user replied.

**To Reproduce**
Steps to reproduce the behavior: https://drive.google.com/file/d/10xOMJ5jFiHvfFnXUgM1lSfZZPfHGmmYI/view?usp=sharing

**Expected behavior**
It should redirect the exact reply instead of the main comment

**Support ticket links**
https://secure.helpscout.net/conversation/1300354755/101906

### PR DESCRIPTION
**Pull request by kent-carlo**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1594.

### How to test the changes in this Pull Request:

https://www.loom.com/share/dca6561d7e9541ffba84b752dfe50982

### Proof Screenshots or Video

https://www.loom.com/share/dca6561d7e9541ffba84b752dfe50982

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Added support on navigating to the specific comment from URL hash when the loading single activity page

### CODE REVIEW

File: src/bp-templates/bp-nouveau/js/buddypress-activity.js [hunk 1]
```diff
@@ -451,8 +451,17 @@ window.bp = window.bp || {};
...
 						function( i, item ) {
 							if ( i < comment_items.length - 4 ) {
-								$( item ).addClass( 'bp-hidden' ).hide();
+								
+								//stop hiding elements if the id from hash url for specific comment matches
+								if( window.location.hash && "#" + $( item ).attr('id') === window.location.hash ){
+
+									//in case it's a reply from comment, show hidden parent elements for it to show
+									$( item ).parents( "li.comment-item" ).show();
+									return false;
```
Comment (dipskakadiya) [inline src/bp-templates/bp-nouveau/js/buddypress-activity.js:460]: @kent-carlo we need to add display all. Because of return might be it'll not execute `// Prepend a link to display all.` section.

**Review by dipskakadiya — CHANGES_REQUESTED** [review]

**Review by dipskakadiya — APPROVED** [review]

**Review by KartikSuthar — APPROVED** [review]
