### PR TITLE
PROD-739 #2947 - Fix: Profile edit > Field set issue in saving

### LINKED ISSUE #2947: Profile edit > Field set issue in saving
**Describe the bug**
It allows saving empty fields inside the fieldset even when the field is required. Also, the empty field set that is being saved can't be deleted.

**To Reproduce**
1. Setup fieldset and make the fields inside it required.
2. Go to profile > edit.
3. Try adding blank fieldsets.
4. Change some of the fields and you can see that it will let you save it.
5. Even the empty fieldsets remain.
6. You can also try to delete empty fieldsets and it will still stay after saving.

**Expected behavior**
I shouldn't allow fields to be saved inside fieldset if it's not empty especially if the fieldset is empty. Also, it should allow the empty field set to be deleted.

**Screenshots**
https://www.loom.com/share/c19734253cc04f7cbaca61373ee5378d

**Environment**
Which site did you replicate this issue on?
https://dev-kent.flywheelsites.com/

**Support ticket links**
https://secure.helpscout.net/conversation/1610180509/160293?folderId=3709081

**Jira issue** : [PROD-739]

[PROD-739]: https://buddyboss.atlassian.net/browse/PROD-739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by milanhirapra**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2947 .

### How to test the changes in this Pull Request:

1. Setup fieldset with repeater and make the fields inside it required.
2. Go to User profile > edit.
3. Try adding blank fieldsets.
4. Change some of the fields and delete empty fieldsets and save them.
5. Can see deleted fieldset will delete from the user profile.

### Proof Screenshots or Video
https://vimeo.com/624258970/c200ab761a

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by dipskakadiya — APPROVED** [review]

File: src/bp-xprofile/screens/edit.php [hunk 1]
```diff
@@ -16,6 +16,8 @@ function xprofile_screen_edit_profile() {
 
 	global $wpdb;
 
+	$bp = buddypress();
```
Comment (KartikSuthar) [inline src/bp-xprofile/screens/edit.php:19]: remove this as its not needed.

File: src/bp-xprofile/screens/edit.php [hunk 2]
```diff
@@ -46,6 +48,18 @@ function xprofile_screen_edit_profile() {
 			foreach ( $deleted_field_ids as $deleted_field_id ) {
 				xprofile_delete_field_data( $deleted_field_id, bp_displayed_user_id() );
 			}
+
+			if ( isset( $_POST['repeater_set_sequence'] ) && ! empty( $_POST['repeater_set_sequence'] ) ) {
+
+				$field_set_sequence = wp_parse_id_list( wp_unslash( $_POST['repeater_set_sequence'] ) );
+
+				$field_group_id = 0;
```
Comment (KartikSuthar) [inline src/bp-xprofile/screens/edit.php:56]:
```suggestion
				$field_group_id = (int) bp_action_variable( 1 );
```

File: src/bp-xprofile/screens/edit.php [hunk 3]
```diff
@@ -46,6 +48,18 @@ function xprofile_screen_edit_profile() {
...
+
+				if ( isset( $deleted_field_ids[0] ) ) {
+					$field_group_id = $wpdb->get_var( $wpdb->prepare( "SELECT group_id FROM {$bp->profile->table_name_fields} WHERE id = %d", $deleted_field_ids[0] ) );
+				}
```
Comment (KartikSuthar) [inline src/bp-xprofile/screens/edit.php:60]: Remove this as its not needed.

**Review by KartikSuthar — CHANGES_REQUESTED** [review]

**Review by KartikSuthar — APPROVED** [review]

**Review by jitendrabanjara1991 — APPROVED** [review]
