### PR TITLE
#761 Server goes away when activate platform plugin with 60000 users

### LINKED ISSUE #761: Server goes away when activate platform plugin with 60000 users
**Describe the bug**
When we activate the platform plugin with 60000 or more users server goes away.
Its happen due to function `bp_activity_favorites_upgrade_data()`

**To Reproduce**
1. Go to Admin
2. Click on Plugins
3. Activate BuddyBoss Platform

**Expected behavior**
When we activate the plugin it should be activated smoothly. 

**Screenshots**
http://prntscr.com/s18pqv

**Support ticket links**
https://secure.helpscout.net/conversation/1133557684/68047?folderId=3701249
https://secure.helpscout.net/conversation/1136798974/68727?folderId=3709080

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #761 .

### How to test the changes in this Pull Request:

1. Add 50000 or more users.
2. Try to activate the platform.
3. You can't activate due to the mysql service down.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Comment by chetansatasiya** [comment]
@ankitguptaindia We need to test this.

File: src/bp-activity/bp-activity-functions.php [hunk 1]
```diff
@@ -1253,7 +1253,22 @@ function ( $carry, $user_id ) use ( $current_user_id, $like_text ) {
 function bp_activity_favorites_upgrade_data() {
 	$bp_activity_favorites = bp_get_option( 'bp_activity_favorites', false );
 
-	if ( ! $bp_activity_favorites ) {
+	if ( ! $bp_activity_favorites && bp_is_active( 'activity' ) ) {
+
+		if ( bp_is_large_install( 100 ) ) {
```
Comment (mehulkaklotar) [inline src/bp-activity/bp-activity-functions.php:1258]: @chetansatasiya why do we need to check only 100 users as large network? is it neccessary. 100 users is not large network.

File: src/bp-core/admin/bp-core-admin-tools.php [hunk 2]
```diff
@@ -1126,7 +1135,84 @@ function bp_admin_repair_tools_wrapper_function() {
...
+			'number' => 50,
+			'offset' => $offset,
+		);
+
+		$users = get_users( $args );
+
+		if ( ! empty( $users ) ) {
+
+		    foreach ( $users as $user ) {
+			    $my_favs = bp_get_user_meta( $user->ID, 'bp_favorite_activities', true );
```
Comment (mehulkaklotar) [inline src/bp-core/admin/bp-core-admin-tools.php:1168]: @chetansatasiya change the name of variable to `$user_favs` here and other places as well.

File: src/bp-activity/bp-activity-functions.php (hunk 1 above)
Comment (chetansatasiya) [reply src/bp-activity/bp-activity-functions.php]: @mehulkaklotar made the changes.

File: src/bp-core/admin/bp-core-admin-tools.php (hunk 2 above)
Comment (chetansatasiya) [reply src/bp-core/admin/bp-core-admin-tools.php]: @mehulkaklotar made the changes.

File: src/bp-activity/bp-activity-functions.php (hunk 1 above)
Comment (chetansatasiya) [reply src/bp-activity/bp-activity-functions.php]: @mehulkaklotar At this moment we have a condition like `10000` users do you think on `init` action it will handle `9000` members will handle in single request?

Comment (chetansatasiya) [reply src/bp-activity/bp-activity-functions.php]: @mehulkaklotar If we processed via `10000` users I am sure like in many servers `mysql` service will go out of service and crashed and platform will not going to activate.

Comment (mehulkaklotar) [reply src/bp-activity/bp-activity-functions.php]: @chetansatasiya no it won't happen. because the query is only to count not fetching the rows. I have tested in my local with minimal config server with more than 10k users and count query doesn't even take more than a half second to execute.

**Comment by chetansatasiya** [comment]
@ankitguptaindia Need to test this.

**Comment by ankitguptaindia** [comment]
@chetansatasiya @mehulkaklotar @eisenwasser 

Tested this issue via creating **83,208 Users** on my local site. Plugin activated smoothly without any error and warning.

Error log and php log files also doesn't have any warning, notice, errors.  
https://prnt.sc/s97irj  https://prnt.sc/s97lsk

Proof- https://www.loom.com/share/5abde9714823484ba83a3ced82e16a56


Server/System Info On whch this issues tested:


Server architecture | Darwin 19.3.0 x86_64
-- | --
Web server | nginx/1.16.0
PHP version | 7.3.5 (Supports 64bit values)
PHP SAPI | fpm-fcgi
PHP max input variables | 4000
PHP time limit | 1200
PHP memory limit | 256M
Max input time | 600
Upload max filesize | 300M
PHP post max size | 1000M
cURL version | 7.54.0 LibreSSL/2.6.5
Is SUHOSIN installed? | No
Is the Imagick library available? | No

---

Extension | mysqli
-- | --
Server version | 8.0.16
Client version | mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
Database username | root
Database host | localhost
Database name | local
Table prefix | wp_
Database charset | utf8mb4
Database collation | utf8mb4_unicode_520_ci


----
NOTE- Negative Test- If using old version of plugin (plugin without this fix) then getting fatal error https://prnt.sc/s97p2a
