### PR TITLE
1299 - Fixed the notification date

### LINKED ISSUE #1299: Discussion reply notification incorrect timestamp
**Describe the bug**
When someone posted a reply in a particular discussion, the user created that discussion will get a notification about that reply, and when he/she views the notification the timestamp isn't correct.

**To Reproduce**
Here's a screencast on how to replicate the bug: https://www.loom.com/share/d050c4302f7d472cb6c3555a31246d28

1. Inside admin, Settings > General, set the timezone to UTC -4 or Los Angeles, or whatever timezone except UTC+0
2. Post a reply using a different account
3. Login to the account that started the discussion and you should see a notification
4. Click the notification bell located at the top right corner of the page and you'll see that the timestamp is incorrect.

**Expected behavior**
The timestamp of the notification should be correct.

**Support ticket links**
https://secure.helpscout.net/conversation/1234610398/84834
https://secure.helpscout.net/conversation/1239745664/85687

### PR DESCRIPTION
**Pull request by janakkaneriya007**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1299 

### How to test the changes in this Pull Request:

1. Inside admin, Settings > General, set the timezone to UTC -4 or Los Angeles, or whatever timezone except UTC+0
2. Post a reply using a different account
3. Login to the account that started the discussion and you should see a notification
4. Click the notification bell located at the top right corner of the page and you'll see that the timestamp is incorrect.

### Proof Screenshots or Video
https://www.loom.com/share/cc27a971ee6243c49cedcfdb4be68b19

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by dipskakadiya — APPROVED** [review]
@janakkaneriya007 Approved.  Please merge this branch to `dev` and then assign to @mehulkaklotar

File: src/bp-forums/notifications.php [hunk 1]
```diff
@@ -201,7 +201,7 @@ function bbp_buddypress_add_notification( $reply_id = 0, $topic_id = 0, $forum_i
 		'item_id'          => $reply_id,
 		'component_name'   => bbp_get_component_name(),
 		'component_action' => 'bbp_new_reply',
-		'date_notified'    => get_post( $reply_id )->post_date,
+		'date_notified'    => bp_core_current_time(),
```
Comment (mehulkaklotar) [inline src/bp-forums/notifications.php:204]: @janakkaneriya007 can we use `post_date_gmt` instead?

```suggestion
		'date_notified'    => get_post( $reply_id )->post_date_gmt,
```

**Review by mehulkaklotar — CHANGES_REQUESTED** [review]

**Review by mehulkaklotar — APPROVED** [review]
