### PR TITLE
PROD-934 I can not visualize code in plugin editor in the RTL language mode

### LINKED ISSUE #1237: I can not visualize code in plugin editor in the RTL language mode
**Describe the bug**

When RTL Language enabled, Unable to edit/visualize code in the plugin editor.

**To Reproduce**
1. Enable RTL language
2. Go to code edit page plugin/theme
3. See error

**Expected behavior**
The code editor should work as expected.

**Support ticket links**

https://secure.helpscout.net/conversation/1212123381/80933?folderId=3701248

**Jira issue** : [PROD-934]

[PROD-934]: https://buddyboss.atlassian.net/browse/PROD-934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by shohelbuddyboss**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

`wp-content/plugins/buddyboss-platform/src/bp-templates/bp-nouveau/buddypress-functions.php`
Checked if page is not plugin or theme editor page, then Enqueue css file

Fixes #1237 .

### Changelog entry

> Fixed: I can not visualize code in plugin editor in the RTL language mode #1237

### CODE REVIEW

File: src/bp-templates/bp-nouveau/buddypress-functions.php [hunk 1]
```diff
@@ -339,7 +339,12 @@ public function platform_login_scripts() {
 	 *
 	 * @since BuddyPress 3.0.0
 	 */
-	public function enqueue_styles() {
+	public function enqueue_styles( $page ) {
+
+		if ( $page == 'plugin-editor.php' || $page == 'theme-editor.php' ) {
```
Comment (mehulkaklotar) [inline src/bp-templates/bp-nouveau/buddypress-functions.php:344]:
```suggestion
		if ( $page === 'plugin-editor.php' || $page === 'theme-editor.php' ) {
```

File: src/bp-templates/bp-nouveau/buddypress-functions.php [hunk 2]
```diff
@@ -339,7 +339,12 @@ public function platform_login_scripts() {
 	 *
 	 * @since BuddyPress 3.0.0
 	 */
-	public function enqueue_styles() {
+	public function enqueue_styles( $page ) {
```
Comment (mehulkaklotar) [inline src/bp-templates/bp-nouveau/buddypress-functions.php:342]: @shohelbuddyboss `bp_enqueue_scripts` hook doesn't have `$page` param? is it going to work?

May be you will need global variable to check that? some thing like $current_screen. https://deluxeblogtips.com/get-admin-screen-information/

Check for network screen as well.

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@shohel Please do the changes requested by mehul.

**Review by KartikSuthar — APPROVED** [review]
