### PR TITLE
PROD-813 Fixed My groups link on a member profile page.

### LINKED ISSUE #2436: My groups link on a member profile page sends to the member groups instead of current logged in members.
**Describe the bug**
When adding the My groups link in the titlebar menu and view any other members' profile page and then click on my group link in the titlebar, it redirects you to that member's groups page instead of currently logged-in member's my group page.

**To Reproduce**
http://somup.com/crhtjtq2xA

**Expected behavior**
It should redirect to current logged-in members' "my group" page.

**Support ticket links**
https://secure.helpscout.net/conversation/1523587350/144126/

JIRA ISSUE: [PROD-813]

[PROD-813]: https://buddyboss.atlassian.net/browse/PROD-813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by ngolwalkar**
### Changes proposed in this Pull Request:

Fixes #2436

### How to test the changes in this Pull Request:

http://somup.com/crhtjtq2xA

### Proof Screenshots or Video

https://www.loom.com/share/507283b72ae14c198ee62ed31bf51ad9

### CODE REVIEW

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@ngolwalkar This will create an issue when you are not logged in to the site and if you go into any user profile it will hide the group's tab in the user profile.

**Comment by ngolwalkar** [comment]
> @ngolwalkar This will create an issue when you are not logged in to the site and if you go into any user profile it will hide the group's tab in the user profile.

I will check with this.

File: src/bp-groups/classes/class-bp-groups-component.php [hunk 1]
```diff
@@ -555,10 +555,11 @@ public function setup_nav( $main_nav = array(), $sub_nav = array() ) {
...
 		// Determine user to use.
-		if ( bp_displayed_user_domain() ) {
-			$user_domain = bp_displayed_user_domain();
-		} elseif ( bp_loggedin_user_domain() ) {
+		if ( bp_loggedin_user_domain() ) {
 			$user_domain = bp_loggedin_user_domain();
+		}
+		elseif ( bp_displayed_user_domain() ) {
+			$user_domain = bp_displayed_user_domain();
 		} else {
```
Comment (chetansatasiya) [inline src/bp-groups/classes/class-bp-groups-component.php:563]:
```suggestion
		} elseif ( bp_displayed_user_domain() ) {
			$user_domain = bp_displayed_user_domain();
		} else {
```

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
follow the proper spacing

File: src/bp-groups/classes/class-bp-groups-component.php [hunk 2]
```diff
@@ -555,10 +555,10 @@ public function setup_nav( $main_nav = array(), $sub_nav = array() ) {
 		$bp = buddypress();
 
 		// Determine user to use.
-		if ( bp_displayed_user_domain() ) {
-			$user_domain = bp_displayed_user_domain();
-		} elseif ( bp_loggedin_user_domain() ) {
+		if ( bp_loggedin_user_domain() ) {
 			$user_domain = bp_loggedin_user_domain();
+		} elseif ( bp_displayed_user_domain() ) {
+			$user_domain = bp_displayed_user_domain();
```
Comment (chetansatasiya) [inline src/bp-groups/classes/class-bp-groups-component.php:561]: @ngolwalkar Still, we can't make this change as it will create issues. I would suggest you make the change on that menu URL if someone added in the menu then add by logged in user in the menu link.

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
Need changes

**Review by chetansatasiya — DISMISSED** [review]
