### PR TITLE
Warning: DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, Error when Popup Builder Plugin install with #1152

### LINKED ISSUE #1152: Warning: DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity,  Error when Popup Builder Plugin install with
**Describe the bug**
When Popup Builder Plugin install, a warning comes below

Warning: DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 1 in `plugins/buddyboss-platform/src/bp-integrations/compatibility/bp-compatibility-integration.php on line 56`

**To Reproduce**
1. Install and activate Popup Builder Plugin, at header, check the warning.
2. Debug mode should be true
3. See error at the admin header or installed plugins page.

**Expected behavior**
There should be no warning

**Screenshots**

BuddyBoss Warning

### PR DESCRIPTION
**Pull request by shohelbuddyboss**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1152.

### Changelog entry

> Added @ at the line `$htmlDom->loadHTML($link['settings']);` on file `wp-content/plugins/buddyboss-platform/src/bp-integrations/compatibility/bp-compatibility-integration.php`

### CODE REVIEW

**Comment by sumitbuddyboss** [comment]
Fixed.
Fixed. I have tested on fix-1152 branch this issue is resolve now. For proof please check the below video.

**Video:**
https://www.loom.com/share/8be4f8e3d15e450696e57798812a4c88

File: src/bp-integrations/compatibility/bp-compatibility-integration.php [hunk 1]
```diff
@@ -53,7 +53,7 @@ public function action_links( $link, $file ) {
 		$htmlDom = new DOMDocument;
 
 		// Parse the HTML of the page using DOMDocument::loadHTML
-		$htmlDom->loadHTML($link['settings']);
+		@$htmlDom->loadHTML($link['settings']);
```
Comment (mehulkaklotar) [inline src/bp-integrations/compatibility/bp-compatibility-integration.php:56]: @shohelbuddyboss we don't want to just silence the errors. we want to fix them so that it doesn't come back again.
