### PR TITLE
The subscriber does not appear as a group leader from the Learndash dashboard, after creating group from the BB front-end.

### LINKED ISSUE #2223: BB platform  LD Integration> Group roles are not getting assign as per settings if the group organizer is non admin member.
**Describe the bug**
On Platform under integration we have settings to select user role which user will automatically get assign under LD group on creating group. As per this settings when admin user creates group in platform then that user will get role in LD as per the settings available in Integration but when any normal subscriber creates any group then as a organizer under the LD group that user is not getting role as per settings. Current settings are working only for admins and only admins have rights to become Group leader.

**To Reproduce**
1. Login as Subscriber.
2. Create group
3. Now login as admin
4. Go to LD group
5. Go to new created group.
6. Check user roles.

**Expected behavior**
Settings must apply to all users not only for admin users.

**Video**
https://www.loom.com/share/aee656c0515e40c6b8a56acac040ee53

### PR DESCRIPTION
**Pull request by asaquzzamanbb**
### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2223 

### How to test the changes in this Pull Request:

1. Login as Subscriber.
2. Create group
3. Now login as admin
4. Go to LD group
5. Go to new created group.
6. Check user roles.

https://www.loom.com/share/aee656c0515e40c6b8a56acac040ee53

### Proof Screenshots or Video

https://www.loom.com/share/352335e3a5274d58a0a175b321979064

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

File: src/bp-core/compatibility/bp-incompatible-plugins-helper.php [hunk 1]
```diff
@@ -694,3 +694,133 @@ function bb_rest_compatibility_loader() {
...
+function bb_learndash_delete_group( $post_id = 0 ) {
+	// Is Learndash active or not.
+	if ( ! defined( 'LEARNDASH_VERSION' ) ) {
+		return;
+	}
+
+	$post = get_post( $post_id );
+	
+	// Is it trash or not.
+	if ( 'revision' != $post->post_type ) {
```
Comment (chetansatasiya) [inline src/bp-core/compatibility/bp-incompatible-plugins-helper.php:721]:
```suggestion
	if ( 'revision' !== $post->post_type ) {
```

File: src/bp-core/compatibility/bp-incompatible-plugins-helper.php [hunk 2]
```diff
@@ -694,3 +694,133 @@ function bb_rest_compatibility_loader() {
...
+		return;
+	}
+
+	$post_parent = get_post( $post->post_parent );
+
+	if ( 'groups' != $post_parent->post_type ) {
```
Comment (chetansatasiya) [inline src/bp-core/compatibility/bp-incompatible-plugins-helper.php:727]:
```suggestion
	if ( 'groups' !== $post_parent->post_type ) {
```

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
@asaquzzamanbb Run the PHPCS and fix all the errors

**Comment by asaquzzamanbb** [comment]
@chetansatasiya 

Fixed all PHPCS issue. Could you please review it again.

File: src/bp-core/compatibility/bp-incompatible-plugins-helper.php [hunk 3]
```diff
@@ -694,3 +694,133 @@ function bb_rest_compatibility_loader() {
 	}
 }
 add_action( 'bp_rest_api_init', 'bb_rest_compatibility_loader', 5 );
+
+/**
+ * Remove the 'group_leader' role for Learndash group author.
+ * If the author is not the leader of any gorup.
+ *
+ * @since BuddyBoss 1.6.1
```
Comment (KartikSuthar) [inline src/bp-core/compatibility/bp-incompatible-plugins-helper.php:702]:
```suggestion
 * @since BuddyBoss 1.6.2
```

File: src/bp-core/compatibility/bp-incompatible-plugins-helper.php [hunk 4]
```diff
@@ -694,3 +694,133 @@ function bb_rest_compatibility_loader() {
...
+	// Add role.
+	$user->remove_role( 'group_leader' );
+}
+add_action( 'delete_post', 'bb_learndash_delete_group' );
+
+/**
+ * Add the 'group_leader' role for Learndash group author.
+ * When learndash group status change form trash to draft.
+ *
+ * @since BuddyBoss 1.6.1
```
Comment (KartikSuthar) [inline src/bp-core/compatibility/bp-incompatible-plugins-helper.php:766]:
```suggestion
 * @since BuddyBoss 1.6.2
```

File: src/bp-core/compatibility/bp-incompatible-plugins-helper.php [hunk 5]
```diff
@@ -694,3 +694,133 @@ function bb_rest_compatibility_loader() {
...
+	}
+
+	bb_learndash_role_add( $author );
+}
+add_action( 'untrash_post', 'bb_learndash_untrash_group' );
+
+/**
+ * Add user role as 'group_leader'
+ *
+ * @since BuddyBoss 1.6.1
```
Comment (KartikSuthar) [inline src/bp-core/compatibility/bp-incompatible-plugins-helper.php:811]:
```suggestion
 * @since BuddyBoss 1.6.2
```

File: src/bp-integrations/learndash/library/SyncGenerator.php [hunk 6]
```diff
@@ -139,11 +139,53 @@ function() use ( $bpGroupId ) {
...
 				wp_delete_post( $ldGroupId, true );
 			}
 		);
 	}
 
+	/**
+	 * Remove the 'group_leader' role for Learndash group author.
+	 * If the author is not the leader of any gorup.
+	 *
+	 * @since BuddyBoss 1.6.1
```
Comment (KartikSuthar) [inline src/bp-integrations/learndash/library/SyncGenerator.php:152]:
```suggestion
	 * @since BuddyBoss 1.6.2
```

File: src/bp-integrations/learndash/library/SyncGenerator.php [hunk 7]
```diff
@@ -346,6 +389,26 @@ function() use ( $userId, $remove ) {
 		return $this;
 	}
 
+	/**
+	 * Promote the uesr as a learndash group leader.
+	 *
+	 * @since BuddyBoss 1.6.1
```
Comment (KartikSuthar) [inline src/bp-integrations/learndash/library/SyncGenerator.php:395]:
```suggestion
	 * @since BuddyBoss 1.6.2
```

**Review by KartikSuthar — CHANGES_REQUESTED** [review]
@asaquzzamanbb Please do the below changes.

**Comment by asaquzzamanbb** [comment]
@KartikSuthar 

Changes done! Could you please review it again.

**Review by KartikSuthar — APPROVED** [review]
@asaquzzamanbb Approved. Merged to dev and pass to QA.

**Comment by asaquzzamanbb** [comment]
@KartikSuthar 

Merge done! https://github.com/buddyboss/buddyboss-platform/commit/8faf829b939f806e2a3495ccfd0439d6692d85eb

**Review by chetansatasiya — DISMISSED** [review]

**Comment by mohit-buddyboss** [comment]
@asaquzzamanbb 

Tested on the dev branch of the platform.
This issue is partially resolved. Now Organizer gets role in LearnDash group as mentioned in Integration setting.

Issue :  But for moderator it is not working. Group Moderator not getting the assigned role as per integration setting

Video: https://www.loom.com/share/2b4a285e680443369cc43cf956e6a27d

cc @sourabhmatolia @chetansatasiya

**Comment by asaquzzamanbb** [comment]
@chetansatasiya @KartikSuthar 

Could you please review this PR again.

**Review by chetansatasiya — APPROVED** [review]
LGTM

**Comment by asaquzzamanbb** [comment]
@chetansatasiya 
Merge done with dev branch https://github.com/buddyboss/buddyboss-platform/commit/494d0e7476cb45d96931a5245bc4f8a01a0ec381

**Comment by mohit-buddyboss** [comment]
@asaquzzamanbb 

Tested on dev branch of the platform 

FIXED> Now if group gets created by non admin users then group organizer and moderators are getting role in associated Learndash group as per selection in BuddyBoss integration settings. 
Video: https://www.loom.com/share/c41cc86c8e69488d8fd20a1639fc74fc

Related issue is resolve now and PR is ready to release.

cc @sourabhmatolia @chetansatasiya

**Review by chetansatasiya — APPROVED** [review]

**Review by chetansatasiya — APPROVED** [review]

**Review by chetansatasiya — APPROVED** [review]

**Review by KartikSuthar — APPROVED** [review]
