### PR TITLE
New Discussion modal window not working & TranslatePress select2 fix

### LINKED ISSUE #579: Messages not working with Translatepress after Platform update
**Describe the bug**
Composing a new message in Messages in not working when TranslatePress is activated on latest Platform update

**To Reproduce**
1. Make sure Platform1.2.7/Theme 1.3.6 is installed
2. Install Translatepress https://wordpress.org/plugins/translatepress-multilingual/
3. Go to Messages, try to compose a new message

**Expected behavior**
After clicking the compose message, it should prompt the textbox of selecting users to message, but when Translatepress is enabled, this prompts a scrollable box.

**Screenshots**
https://drive.google.com/open?id=13EFuArUSoCa6e2jBhunfTJy59VVpO3Lt

**Support ticket links**
https://buddyboss.zendesk.com/agent/tickets/61803
https://buddyboss.zendesk.com/agent/tickets/62593

### LINKED ISSUE #587: New Discussion modal window not working.
**Describe the bug**
New Discussion modal window is not opening because of a JS error when the plugin is activated with LearnDash Ratings, Reviews & Feedback plugin. 
`Uncaught ReferenceError: bp_select2 is not defined
    at HTMLDocument.<anonymous> (common.js?ver=2.5.14-6684:13)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4-wp:2)
    at Function.ready (jquery.js?ver=1.12.4-wp:2)
    at HTMLDocument.J (jquery.js?ver=1.12.4-wp:2)`

On further debugging found that the bp_select2 variable is only localized if wp_get_available_translations doesn't exist.

This code is present in bp-core/bp-core-cssjs.php. Please check the following link
https://github.com/buddyboss/buddyboss-platform/blob/dev/src/bp-core/bp-core-cssjs.php#L219

This issue is occurring because the LearnDash Ratings, Reviews & Feedback plugin also uses wp_get_available_translations function.

We can further extrapolate it to mean that if any plugin uses wp_get_available_translations in the frontend and its code is executed before buddyboss-platform then the code inside the "if condition" will not execute and all the js files which use bp_select2 variable will throw a JS error.

**Expected behavior**
The if condition should only wrap wp_get_available_translations function. The localization condition should be moved outside the if condition.
Alternatively, you can add checks in the js file for bp_select2 variable before using it. 

I am attaching a patch file with a fix for this and I would appreciate it if someone will review this and 
get the fix released as soon as possible.

[patch.zip](https://github.com/buddyboss/buddyboss-platform/files/4234779/patch.zip)

**Screenshots**
Screenshot from 2020-02-21 12-53-49

### PR DESCRIPTION
**Pull request by chetansatasiya**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #587 
Fixes #579

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> New Discussion modal window not working when LearnDash Ratings, Reviews & Feedback plugin used

### CODE REVIEW

File: src/bp-core/bp-core-cssjs.php [hunk 1]
```diff
@@ -212,35 +216,30 @@ function bp_core_register_common_scripts() {
...
-		} else if (
-			!empty( get_bloginfo( 'language' ) )
-			&& file_exists( $file_path . 'vendor/i18n/' . get_bloginfo( 'language' ) . '.js' )
-		) {
+		} elseif ( ! empty( get_bloginfo( 'language' ) ) && file_exists( $file_path . 'vendor/i18n/' . get_bloginfo( 'language' ) . '.js' ) ) {
 			$bp_select2['lang'] = get_bloginfo( 'language' );
 			wp_register_script( 'bp-select2-local', "{$url}vendor/i18n/{$bp_select2['lang']}.js", array( 'bp-select2' ), $version, false );
 		}
 
 		wp_localize_script( 'bp-select2', 'bp_select2', $bp_select2 );
```
Comment (mehulkaklotar) [inline src/bp-core/bp-core-cssjs.php]: This still needs to be outside of `if` condition. We need to localize script with `$bp_select2` variable any how. so if it is in if condition that means in some cases it would not localize. Though we have put a check in js as well to check if variable is set or not but at PHP level it should be outside if condition.

File: src/bp-forums/templates/default/js/common.js [hunk 2]
```diff
@@ -10,7 +10,7 @@ jQuery( document ).ready(
 			minimumInputLength: 1,
 			closeOnSelect: true,
 			tags: true,
-			language: bp_select2.lang,
+			language: ( typeof bp_select2 != 'undefined' && typeof bp_select2.lang != 'undefined' ) ? bp_select2.lang : 'en',
```
Comment (mehulkaklotar) [inline src/bp-forums/templates/default/js/common.js]:
```suggestion
			language: ( typeof bp_select2 !== 'undefined' && typeof bp_select2.lang !== 'undefined' ) ? bp_select2.lang : 'en',
```

File: src/bp-templates/bp-nouveau/js/buddypress-group-invites.js [hunk 3]
```diff
@@ -925,7 +925,7 @@ window.bp = window.bp || {};
 			$input.select2({
 				placeholder: '',
 				minimumInputLength: 1,
-				language: bp_select2.lang,
+				language: ( typeof bp_select2 != 'undefined' && typeof bp_select2.lang != 'undefined' ) ? bp_select2.lang : 'en',
```
Comment (mehulkaklotar) [inline src/bp-templates/bp-nouveau/js/buddypress-group-invites.js]:
```suggestion
				language: ( typeof bp_select2 !== 'undefined' && typeof bp_select2.lang !== 'undefined' ) ? bp_select2.lang : 'en',
```

File: src/bp-templates/bp-nouveau/js/buddypress-messages.js [hunk 4]
```diff
@@ -1133,7 +1133,7 @@ window.bp = window.bp || {};
 				minimumInputLength: 1,
 				dropdownCssClass: 'bb-select-dropdown',
 				containerCssClass: 'bb-select-container',
-				language: bp_select2.lang,
+				language: ( typeof bp_select2 != 'undefined' && typeof bp_select2.lang != 'undefined' ) ? bp_select2.lang : 'en',
```
Comment (mehulkaklotar) [inline src/bp-templates/bp-nouveau/js/buddypress-messages.js]:
```suggestion
				language: ( typeof bp_select2 !== 'undefined' && typeof bp_select2.lang !== 'undefined' ) ? bp_select2.lang : 'en',
```

File: src/bp-core/bp-core-cssjs.php (hunk 1 above)
Comment (chetansatasiya) [reply src/bp-core/bp-core-cssjs.php]: This is done 👍 Thanks @mehulkaklotar

File: src/bp-forums/templates/default/js/common.js (hunk 2 above)
Comment (chetansatasiya) [reply src/bp-forums/templates/default/js/common.js]: This is done 👍 Thanks @mehulkaklotar
