### PR TITLE
PROD-876 Memberpress signup bad nickname issue fixed

### LINKED ISSUE #1946: Bad Username and Nickname allowed when signup is done via Memberpress Plugin
**Describe the bug**
When Memberpress is used for user registration process, the user can choose their email as username. This is not a problem for wordpress or Memberpress but that leads to some errors in Buddyboss.

Examples of errors : Mention and messaging don't work anymore because the nickname is the email ( the nickname looks like : @john.doe@email.com)

Here is the solution I've found for the moment (still need some tests) : 

```
function pf_validate_bb_nickname_from_memberpress( $errors ) {
    $nickname   = (string) sanitize_text_field( $_POST[ 'user_login' ] );
	$field_id   = bp_xprofile_nickname_field_id();
	$field_name = xprofile_get_field( $field_id )->name;

	$message    = bp_xprofile_validate_nickname_value('', $field_id, $nickname, '');

	if (! empty( $message ) ){
		$errors[ 'user_login' ] = str_replace( $field_name, __('Username', 'memberpress'), $message);
	}

	return $errors;
}
add_filter('mepr-validate-signup', 'pf_validate_bb_nickname_from_memberpress');
```

**To Reproduce**
1. Register a new user using Memberpress
2. Fill the email address as Username

**Expected behavior**
User should not be able to register an account using an email as the username.

**Screenshots**
none

**Support ticket links**
none

**Jira issue** : [PROD-876]

[PROD-876]: https://buddyboss.atlassian.net/browse/PROD-876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by mahedihasannoman**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1946 .

### How to test the changes in this Pull Request:

1. Make sure memberpress is activated.
2. Also make sure "Members must use their email address for their Username" option is checked from MemberPress > Settings > Account page
3. Now register for a membership tier
4. See it is now preventing user to signup because email cannot not be used as nickname.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by chetansatasiya — APPROVED** [review]

**Review by dipskakadiya — APPROVED** [review]

**Review by dipskakadiya — APPROVED** [review]

File: src/bp-core/compatibility/bp-incompatible-plugins-helper.php [hunk 1]
```diff
@@ -562,21 +562,46 @@ function bp_core_add_support_for_google_captcha_pro( $section_notice, $section_s
...
+		$nickname = sanitize_text_field( $_POST['user_login'] );
+		}
+		$field_id   = bp_xprofile_nickname_field_id();
+		$message    = bp_xprofile_validate_nickname_value( '', $field_id, $nickname, '' );
+		if ( ! empty( $message ) ) {
+		$errors['user_login'] =  $message;
+		}
+	}
+	return $errors;
+}
```
Comment (KartikSuthar) [inline src/bp-core/compatibility/bp-incompatible-plugins-helper.php:602]: @mahedihasannoman please follow the phpcs here.

Comment (mahedihasannoman) [reply src/bp-core/compatibility/bp-incompatible-plugins-helper.php]: Done

**Review by dipskakadiya — APPROVED** [review]
@mahedihasannoman Please merge this in Dev for final review

**Review by chetansatasiya — DISMISSED** [review]
