### PR TITLE
Documents API, Edit Activity support + small fixes

### LINKED ISSUE #1275: BP REST Media Endpoint does not support additional REST fields
**Describe the bug**
Fields added to the 'bp_media' object type via `register_rest_field()` are not present in REST response.
The `prepare_item_for_response` function does not call `add_additional_fields_to_object()`

**To Reproduce**
1. Register a REST field for bp_media
2. Send request to endpoint
3. View response

**Expected behavior**
The registered REST field to be present in the REST response.

### LINKED ISSUE #1496: BB REST API - Activity Endpoint : Missing display_comments in documentation of get_item
**Describe the bug**
This is not a bug but rather a documentation issue. 

When you display available arguments for the rest api request `GET {{host}}/wp-json/buddyboss/v1/activity/932`, there're only 2 arguments availables : id and context.

But when you look into the method `get_item` and `prepare_item_for_response` in the file "_class-bp-rest-activity-endpoint.php_", you can see that there's another argument that you can use : **display_comments**

Could you update the documention of that endpoint ?

Ps : Please, do not remove that argument because it is very usefull to be able to get main activity + comments in one single request.

**To Reproduce**
Execute `OPTIONS {{host}}/wp-json/buddyboss/v1/activity/932`. 
You only see 2 args : id, context.

**Expected behavior**
You should also list display_comments as available argument

**Screenshots**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

### PR DESCRIPTION
**Pull request by KartikSuthar**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #1496 
Fixes #1275

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

File: src/bp-media/classes/class-bp-rest-media-details-endpoint.php [hunk 1]
```diff
@@ -0,0 +1,250 @@
...
+		 * @since 0.1.0
+		 *
+		 * @param int $count Total number of media.
+		 */
+		return apply_filters( 'bp_rest_get_total_media_count', (int) $count );
+	}
+
+	/**
+	 * Media results all scope.
+	 * - from bp_media_object_results_media_all_scope().
```
Comment (mehulkaklotar) [inline src/bp-media/classes/class-bp-rest-media-details-endpoint.php:228]: 👍

File: src/bp-media/classes/class-bp-rest-media-endpoint.php [hunk 2]
```diff
@@ -1838,6 +1858,7 @@ protected function bp_media_ids_get_rest_field_callback( $activity, $attribute )
 
 	/**
 	 * The function to use to update the medias's value of the activity REST Field.
+	 * - from bp_media_update_activity_media_meta();
```
Comment (mehulkaklotar) [inline src/bp-media/classes/class-bp-rest-media-endpoint.php:1861]: great 👍

**Review by mehulkaklotar — APPROVED** [review]
@KartikSuthar 🚀
