### PR TITLE
PROD-844 - Fix #2243 : Past events not showing in search results

### LINKED ISSUE #2243: Events: past events not showing in search results
**Describe the bug**
Past events ob search does not showing in search results on demo site

**To Reproduce**
1. Past events are not showing in search results: https://snipboard.io/tCrz5k.jpg Already tested on sandbox site

**Expected behavior**
Events should show 

**Screenshots**
https://snipboard.io/tCrz5k.jpg

**Support ticket links**
https://secure.helpscout.net/conversation/1453031290/130543/
https://secure.helpscout.net/conversation/1423881407/124835

**Jira issue** : [PROD-844]

[PROD-844]: https://buddyboss.atlassian.net/browse/PROD-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by ngolwalkar**
### Changes proposed in this Pull Request:

Fixes #2243

### How to test the changes in this Pull Request:

1. Need to have the BB demo DB to reproduce this issue. 
2. After installing the BB demo DB to your local instance, search for an event named "Songkran".
3. You will see all the events named with "Songkran" will be shown.

### Proof Screenshots or Video

https://www.loom.com/share/1f6f0d54ed8449bcb6ecf016aecdc461

### CODE REVIEW

File: src/bp-search/plugins/search-cpt/class-bp-search-cpt.php [hunk 1]
```diff
@@ -29,6 +29,15 @@ public function __construct( $cpt_name, $search_type ) {
...
+			add_filter( "parse_query", array( $this, 'parse_query' ) );
+		}
+
+		// To bypass "The Event Calendar" plugin's parse_query filter
+		public function parse_query( $query ){
+			if( is_search() || ( defined('DOING_AJAX') && DOING_AJAX && $_REQUEST['action'] == 'bp_search_ajax' ) )  {
+				$query->set( 'tribe_suppress_query_filters', true );
+			}
+			return $query;
 		}
```
Comment (chetansatasiya) [inline src/bp-search/plugins/search-cpt/class-bp-search-cpt.php:41]: @ngolwalkar This is about the third-party plugin compatibility and we have a file here `src/bp-core/compatibility/bp-incompatible-plugins-helper.php` so this code should be in `/bp-incompatible-plugins-helper.php` instead of here and run the PHPCS and fix all the errors.

**Review by chetansatasiya — CHANGES_REQUESTED** [review]
See my comment

**Review by chetansatasiya — APPROVED** [review]
