### PR TITLE
PROD-938 #1136 - Fix PHP Error: Add fix for About Forum link of dashboard

### LINKED ISSUE #1136: WordPress > About Forums inaccessible when BuddyBoss Platform is activated
**Describe the bug**
When BuddyBoss Platform is activated, the link of Wordpress > About Forums (located on top left of the WP Dashboard with WP Logo) is rendering a no access permit to the user

**To Reproduce**
1. Install BuddyBoss Platform
2. On Wordpress dashboard, go to far top left Wordpress Icon, then click About Forums
3. See error

**Expected behavior**
This should give access to Admin on the About Forums page

**Screenshots**
https://drive.google.com/file/d/1cL2VBLa07G0dvijplhJEAhnpyU_mix8b/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1205454838/79870?folderId=3701258

**Jira issue** : [PROD-938]

[PROD-938]: https://buddyboss.atlassian.net/browse/PROD-938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by kishanjasani**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1136 

### How to test the changes in this Pull Request:

1. Go to dashboard.
2. Click on the WordPress icon located in the Top Left corner.
3. Select BuddyBoss

### Proof Screenshots or Video

Screenshot 2021-09-13 at 4 34 17 PM

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

File: src/bp-forums/admin/admin.php [hunk 1]
```diff
@@ -460,8 +460,8 @@ public function admin_bar_about_link( $wp_admin_bar ) {
 					array(
 						'parent' => 'wp-logo',
 						'id'     => 'bbp-about',
-						'title'  => esc_html__( 'About Forums', 'buddyboss' ),
-						'href'   => add_query_arg( array( 'page' => 'bbp-about' ), admin_url( 'index.php' ) ),
+						'title'  => esc_html__( 'About BuddyBoss', 'buddyboss' ),
```
Comment (dipskakadiya) [inline src/bp-forums/admin/admin.php:463]: @kishanjasani 
1. function docs need to update according to functionality 
2. Can you explain why we need the `hello` query param.

**Review by dipskakadiya — CHANGES_REQUESTED** [review]

File: src/bp-forums/admin/admin.php (hunk 1 above)
Comment (kishanjasani) [reply src/bp-forums/admin/admin.php:463]: This page is not available on the BuddyBoss Platform. It's a BuddyPress plugin page.

I add a hello param because we use it when we install the BuddyBoss plugin. It has a description video of the plugin.

**Review by dipskakadiya — APPROVED** [review]

File: src/bp-forums/admin/admin.php [hunk 2]
```diff
@@ -460,8 +460,8 @@ public function admin_bar_about_link( $wp_admin_bar ) {
...
+						'href'   => add_query_arg( array( 'hello' => 'buddyboss' ), admin_url( 'index.php' ) ),
```
Comment (jitendrabanjara1991) [inline src/bp-forums/admin/admin.php:464]: 'href'   => esc_url( bp_get_admin_url( '?hello=buddyboss' ) ),

**Review by jitendrabanjara1991 — CHANGES_REQUESTED** [review]
Need changes

File: src/bp-forums/admin/admin.php (hunk 2 above)
Comment (kishanjasani) [reply src/bp-forums/admin/admin.php]: @jitendrabanjara1991 Added changes!

**Review by jitendrabanjara1991 — APPROVED** [review]
