### PR TITLE
PROD-812 #2456 - Fix: Messages > Default content &nbsp; enters when in messages user sent only image,doc or GIF.

### LINKED ISSUE #2456: Messages > Default content &nbsp; enters when in messages user sent only image,doc or GIF.
**Describe the bug**
In messages when user send only GIF, Image or doc then we are adding &nbsp; into the content by default.

**To Reproduce**
1. Go to 'Messages'
2. Select recipient.
3. Send only GIF , image or doc in message without text.
4. Change entry in database.

**Expected behavior**
It should not add &nbsp in content.

**Video**
https://www.loom.com/share/1b90575d92e64c9a9e638ad0cb2a1640

**Support ticket links**
N/A reported internally by QA

**Jira issue** : [PROD-812]

[PROD-812]: https://buddyboss.atlassian.net/browse/PROD-812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by milanhirapra**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2456 .

### How to test the changes in this Pull Request:

1. Go to 'Messages'
2. Select recipient.
3. Send only GIF , image or doc in message without text.
4. Change entry in database.

### Proof Screenshots or Video
https://vimeo.com/598910933/cd04eab070

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

File: src/bp-messages/bp-messages-filters.php [hunk 1]
```diff
@@ -727,6 +730,77 @@ function bp_recipients_recipient_get_where_conditions_callback( $where_condition
...
+ *
+ * @return bool
+ */
+function bb_check_is_get_message_content_empty( $validated_content, $content = '', $message_id ) {
+
+	if ( ! empty( $content ) ) {
+		return true;
+	}
+
+	if ( bp_is_active( 'media' ) && bp_is_messages_media_support_enabled() ) {
```
Comment (dipskakadiya) [inline src/bp-messages/bp-messages-filters.php:769]: @milanhirapra Instead of adding media-related code here, this should be added in the media file. 
You can apply filters multiple times with different piority.

**Review by dipskakadiya — CHANGES_REQUESTED** [review]

File: src/bp-messages/bp-messages-filters.php (hunk 1 above)
Comment (milanhirapra) [reply src/bp-messages/bp-messages-filters.php]: @dipskakadiya I added filters to related component files instead of message filter file. Please check this video: https://vimeo.com/600805119/fdd080abeb

File: src/bp-document/bp-document-filters.php [hunk 2]
```diff
@@ -1937,3 +1939,29 @@ function bb_setup_template_for_document_preview( $template ) {
...
+ * If content will empty then return true and allow empty content in DB for the document.
+ *
+ * @param bool         $validated_content Boolean from filter.
+ * @param string       $content           Message content.
+ * @param array|object $id                Message ID.
+ *
+ * @return bool
+ */
+function bb_check_is_get_message_content_validate_with_document( $validated_content, $content = '', $message_id ) {
+	if ( ! empty( $content ) ) {
```
Comment (dipskakadiya) [inline src/bp-document/bp-document-filters.php:1954]: @milanhirapra Why we need to check empty content again it's already checked before

File: src/bp-media/bp-media-filters.php [hunk 3]
```diff
@@ -2677,3 +2679,29 @@ function bb_setup_template_for_media_preview( $template ) {
...
+ * If content will empty then return true and allow empty content in DB for the media.
+ *
+ * @param bool         $validated_content Boolean from filter.
+ * @param string       $content           Message content.
+ * @param array|object $id                Message ID.
+ *
+ * @return bool
+ */
+function bb_check_is_get_message_content_validate_with_media( $validated_content, $content = '', $message_id ) {
+	if ( ! empty( $content ) ) {
```
Comment (dipskakadiya) [inline src/bp-media/bp-media-filters.php:2694]: @milanhirapra Why we need to check empty content again it's already checked before

**Review by dipskakadiya — CHANGES_REQUESTED** [review]

File: src/bp-media/bp-media-filters.php (hunk 3 above)
Comment (milanhirapra) [reply src/bp-media/bp-media-filters.php]: @dipskakadiya I removed this condition from the add filters.

**Review by dipskakadiya — CHANGES_REQUESTED** [review]

File: src/bp-messages/bp-messages-filters.php [hunk 4]
```diff
@@ -727,6 +730,28 @@ function bp_recipients_recipient_get_where_conditions_callback( $where_condition
...
+ *
+ * @since BuddyBoss [BBVERSION]
+ *
+ * @param bool         $validated_content Boolean from filter.
+ * @param string       $content           Message content.
+ * @param array|object $post              Request object.
+ *
+ * @return bool
+ */
+function bb_check_is_message_content_empty( $validated_content, $content, $post ) {
```
Comment (dipskakadiya) [inline src/bp-messages/bp-messages-filters.php:745]: @milanhirapra This is still wrong. As I requested before we should check for every component into the specific component. What if a particular component is disabled.

**Review by dipskakadiya — CHANGES_REQUESTED** [review]

File: src/bp-messages/bp-messages-filters.php (hunk 4 above)
Comment (milanhirapra) [reply src/bp-messages/bp-messages-filters.php:827]: @dipskakadiya I had added filters, but you suggested to remove those filters.
Please check this commit: https://github.com/buddyboss/buddyboss-platform/pull/2886/commits/27c7cff4d4865b183e4ca8e3fea48468370299d7

**Review by chetansatasiya — DISMISSED** [review]
