### PR TITLE
PROD-725 Group type shortcode empty space at titlebar - fixed

### LINKED ISSUE #3033: Showing empty space on title bar when group type shortcode is added and buddypanel is disabled
**Describe the bug**
Showing empty space on title bar when group type shortcode is added and buddypanel is disabled. This issue is happening on our demo as well.

**To Reproduce**
1. Disable buddypanel
2. Add a group type shortcode in a page
3. View the page

**Expected behavior**
Empty space should not show up.

**Screenshots**

image

**Environment**
Localhost, Demo & and everywhere

**Support ticket links**
https://secure.helpscout.net/conversation/1633198246/164400?folderId=3709082

**Jira issue** : [PROD-725]

[PROD-725]: https://buddyboss.atlassian.net/browse/PROD-725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by mahedihasannoman**
### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #3033  .

### How to test the changes in this Pull Request:

1. Disable buddypanel
2. Add a group type shortcode in a page
3. View the page
4. See issue not happening

### Proof Screenshots or Video

screenshot-localhost-2021 10 08-01_25_03

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by dipskakadiya — APPROVED** [review]

File: src/bp-groups/bp-groups-functions.php [hunk 1]
```diff
@@ -3844,7 +3844,11 @@ function bp_group_type_short_code_add_body_class( $class ) {
 		$class[] = 'groups';
 		$class[] = 'buddypress';
 		$class[] = 'buddyboss';
-		$class[] = 'bb-buddypanel';
+		/**
+		 *This class commented because this class will add when buddypanel enable
+		 *and this condition already in the theme
+		 */
+		//$class[] = 'bb-buddypanel';
```
Comment (KartikSuthar) [inline src/bp-groups/bp-groups-functions.php:3851]: @mahedihasannoman @dipskakadiya 

We can not remove this class as so many CSS is written into the theme based on the class.
So, You can make it conditional here OR create PR for the theme to add this class from the theme itself.

**Review by KartikSuthar — CHANGES_REQUESTED** [review]

File: src/bp-groups/bp-groups-functions.php (hunk 1 above)
Comment (mahedihasannoman) [reply src/bp-groups/bp-groups-functions.php:3851]: @KartikSuthar , We are already adding this class “bb-buddypanel” from theme conditionally. https://nimb.ws/ZSniPA

**Review by KartikSuthar — APPROVED** [review]
