### PR TITLE
#1645 - Fixed Custom Notification returns blank text in notification …

### LINKED ISSUE #1645: Custom Notification returns blank text in notification
When we add custom notification, then notification message becomes blank in the notification popup & notification page.

**To Reproduce**
1. Add this code snippet to your theme or plugin https://www.codepile.net/pile/nNz16GvR
2. Refresh page
3. Check notification popup & notification page > https://prnt.sc/v0pyx9

**Expected behavior**
It should display custom notification text on notification popup & notification page

**Screenshots**
https://prnt.sc/v0pyx9

**Reason**
- In the file `/buddyboss-platform/src/bp-forums/notifications.php` at line 163  https://prnt.sc/v0q1de
- We have to return $action by default. Because in this filter, $action is becoming blank if these conditions are not satisfy > https://prnt.sc/v0q2id
- In that case, we have to return default action. So that that action will be used in other filters

### PR DESCRIPTION
**Pull request by krunal-buddyboss**
…issue

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1645  .

### How to test the changes in this Pull Request:

1. Add this code snippet to your theme or plugin https://www.codepile.net/pile/nNz16GvR
2. Refresh page
3. Check notification popup & notification page > https://prnt.sc/v0pyx9

### Proof Screenshots or Video

image

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

### CODE REVIEW

**Review by dipskakadiya — APPROVED** [review]
@krunal-buddyboss Approve. Merge this PR into `dev` and assign to @mehulkaklotar

File: src/bp-forums/notifications.php [hunk 1]
```diff
@@ -159,6 +159,10 @@ function bbp_format_buddypress_notifications( $action, $item_id, $secondary_item
 
 		return $return;
 	}
+
+	do_action( 'bbp_format_buddypress_notifications', $action, $item_id, $secondary_item_id, $total_items );
+
+	return $action;
```
Comment (mehulkaklotar) [inline src/bp-forums/notifications.php:165]: @krunal-buddyboss How is it related to bbPress or forums here? I don't understand. We can just return `$action` from here and it will be fine.

```suggestion
	return $action;
```

**Review by mehulkaklotar — CHANGES_REQUESTED** [review]

**Review by mehulkaklotar — APPROVED** [review]
